// !!!! DO NOT EDIT THIS FILE -- It was automatically generated by gen.py -- DO NOT EDIT THIS FILE !!!!

#if defined(BNG_VERSION)
  #include "imguiApiHost.h"
#else
  #define STANDALONE 1
  #include "imgui.h"
  #include <cstdint>
  #include <cstdarg>

  #if defined(_WIN32)
    #define PLATFORM_WINDOWS
  #endif
#endif // BNG_VERSION

extern "C" {

#if defined(_WIN32)
    #define FFI_EXPORT __declspec(dllexport)
#else
    #define FFI_EXPORT __attribute__((visibility("default")))
#endif

#if defined(STANDALONE)
  typedef struct { float x, y; } ImVec2_C;
  typedef struct { float x, y, z, w; } ImVec4_C;
  typedef ImU64 ImTextureID;
#endif // STANDALONE

FFI_EXPORT ImGuiContext * imgui_GetCurrentContext() {
  return ImGui::GetCurrentContext();
}

FFI_EXPORT void imgui_SetCurrentContext(ImGuiContext* ctx) {
  ImGui::SetCurrentContext(ctx);
}

FFI_EXPORT ImGuiIO & imgui_GetIO() {
  return ImGui::GetIO();
}

FFI_EXPORT ImGuiPlatformIO & imgui_GetPlatformIO() {
  return ImGui::GetPlatformIO();
}

FFI_EXPORT ImGuiStyle & imgui_GetStyle() {
  return ImGui::GetStyle();
}

FFI_EXPORT void imgui_NewFrame() {
  ImGui::NewFrame();
}

FFI_EXPORT void imgui_EndFrame() {
  ImGui::EndFrame();
}

FFI_EXPORT void imgui_Render() {
  ImGui::Render();
}

FFI_EXPORT ImDrawData * imgui_GetDrawData() {
  return ImGui::GetDrawData();
}

FFI_EXPORT void imgui_ShowDemoWindow(bool* p_open) {
  ImGui::ShowDemoWindow(p_open);
}

FFI_EXPORT void imgui_ShowMetricsWindow(bool* p_open) {
  ImGui::ShowMetricsWindow(p_open);
}

FFI_EXPORT void imgui_ShowDebugLogWindow(bool* p_open) {
  ImGui::ShowDebugLogWindow(p_open);
}

FFI_EXPORT void imgui_ShowIDStackToolWindow(bool* p_open) {
  ImGui::ShowIDStackToolWindow(p_open);
}

FFI_EXPORT void imgui_ShowAboutWindow(bool* p_open) {
  ImGui::ShowAboutWindow(p_open);
}

FFI_EXPORT void imgui_ShowStyleEditor(ImGuiStyle* ref) {
  ImGui::ShowStyleEditor(ref);
}

FFI_EXPORT bool imgui_ShowStyleSelector(const char* label) {
  return ImGui::ShowStyleSelector(label);
}

FFI_EXPORT void imgui_ShowFontSelector(const char* label) {
  ImGui::ShowFontSelector(label);
}

FFI_EXPORT void imgui_ShowUserGuide() {
  ImGui::ShowUserGuide();
}

FFI_EXPORT const char * imgui_GetVersion() {
  return ImGui::GetVersion();
}

FFI_EXPORT void imgui_StyleColorsDark(ImGuiStyle* dst) {
  ImGui::StyleColorsDark(dst);
}

FFI_EXPORT void imgui_StyleColorsLight(ImGuiStyle* dst) {
  ImGui::StyleColorsLight(dst);
}

FFI_EXPORT void imgui_StyleColorsClassic(ImGuiStyle* dst) {
  ImGui::StyleColorsClassic(dst);
}

FFI_EXPORT bool imgui_Begin(const char* name, bool* p_open, ImGuiWindowFlags flags) {
  return ImGui::Begin(name, p_open, flags);
}

FFI_EXPORT void imgui_End() {
  ImGui::End();
}

FFI_EXPORT bool imgui_BeginChild1(const char* str_id, const ImVec2* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags) {
  return ImGui::BeginChild(str_id, *size, child_flags, window_flags);
}

FFI_EXPORT bool imgui_BeginChild2(ImGuiID id, const ImVec2* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags) {
  return ImGui::BeginChild(id, *size, child_flags, window_flags);
}

FFI_EXPORT void imgui_EndChild() {
  ImGui::EndChild();
}

FFI_EXPORT bool imgui_IsWindowAppearing() {
  return ImGui::IsWindowAppearing();
}

FFI_EXPORT bool imgui_IsWindowCollapsed() {
  return ImGui::IsWindowCollapsed();
}

FFI_EXPORT bool imgui_IsWindowFocused(ImGuiFocusedFlags flags) {
  return ImGui::IsWindowFocused(flags);
}

FFI_EXPORT bool imgui_IsWindowHovered(ImGuiHoveredFlags flags) {
  return ImGui::IsWindowHovered(flags);
}

FFI_EXPORT ImDrawList * imgui_GetWindowDrawList() {
  return ImGui::GetWindowDrawList();
}

FFI_EXPORT ImVec2_C imgui_GetWindowPos() {
  const ImVec2& res_cxx = ImGui::GetWindowPos();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_GetWindowSize() {
  const ImVec2& res_cxx = ImGui::GetWindowSize();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT float imgui_GetWindowWidth() {
  return ImGui::GetWindowWidth();
}

FFI_EXPORT float imgui_GetWindowHeight() {
  return ImGui::GetWindowHeight();
}

FFI_EXPORT void imgui_SetNextWindowPos(const ImVec2* pos, ImGuiCond cond, const ImVec2* pivot) {
  ImGui::SetNextWindowPos(*pos, cond, *pivot);
}

FFI_EXPORT void imgui_SetNextWindowSize(const ImVec2* size, ImGuiCond cond) {
  ImGui::SetNextWindowSize(*size, cond);
}

FFI_EXPORT void imgui_SetNextWindowSizeConstraints(const ImVec2* size_min, const ImVec2* size_max, ImGuiSizeCallback custom_callback, void* custom_callback_data) {
  ImGui::SetNextWindowSizeConstraints(*size_min, *size_max, custom_callback, custom_callback_data);
}

FFI_EXPORT void imgui_SetNextWindowContentSize(const ImVec2* size) {
  ImGui::SetNextWindowContentSize(*size);
}

FFI_EXPORT void imgui_SetNextWindowCollapsed(bool collapsed, ImGuiCond cond) {
  ImGui::SetNextWindowCollapsed(collapsed, cond);
}

FFI_EXPORT void imgui_SetNextWindowFocus() {
  ImGui::SetNextWindowFocus();
}

FFI_EXPORT void imgui_SetNextWindowScroll(const ImVec2* scroll) {
  ImGui::SetNextWindowScroll(*scroll);
}

FFI_EXPORT void imgui_SetNextWindowBgAlpha(float alpha) {
  ImGui::SetNextWindowBgAlpha(alpha);
}

FFI_EXPORT void imgui_SetWindowPos1(const ImVec2* pos, ImGuiCond cond) {
  ImGui::SetWindowPos(*pos, cond);
}

FFI_EXPORT void imgui_SetWindowSize1(const ImVec2* size, ImGuiCond cond) {
  ImGui::SetWindowSize(*size, cond);
}

FFI_EXPORT void imgui_SetWindowCollapsed1(bool collapsed, ImGuiCond cond) {
  ImGui::SetWindowCollapsed(collapsed, cond);
}

FFI_EXPORT void imgui_SetWindowFocus1() {
  ImGui::SetWindowFocus();
}

FFI_EXPORT void imgui_SetWindowPos2(const char* name, const ImVec2* pos, ImGuiCond cond) {
  ImGui::SetWindowPos(name, *pos, cond);
}

FFI_EXPORT void imgui_SetWindowSize2(const char* name, const ImVec2* size, ImGuiCond cond) {
  ImGui::SetWindowSize(name, *size, cond);
}

FFI_EXPORT void imgui_SetWindowCollapsed2(const char* name, bool collapsed, ImGuiCond cond) {
  ImGui::SetWindowCollapsed(name, collapsed, cond);
}

FFI_EXPORT void imgui_SetWindowFocus2(const char* name) {
  ImGui::SetWindowFocus(name);
}

FFI_EXPORT float imgui_GetScrollX() {
  return ImGui::GetScrollX();
}

FFI_EXPORT float imgui_GetScrollY() {
  return ImGui::GetScrollY();
}

FFI_EXPORT void imgui_SetScrollX(float scroll_x) {
  ImGui::SetScrollX(scroll_x);
}

FFI_EXPORT void imgui_SetScrollY(float scroll_y) {
  ImGui::SetScrollY(scroll_y);
}

FFI_EXPORT float imgui_GetScrollMaxX() {
  return ImGui::GetScrollMaxX();
}

FFI_EXPORT float imgui_GetScrollMaxY() {
  return ImGui::GetScrollMaxY();
}

FFI_EXPORT void imgui_SetScrollHereX(float center_x_ratio) {
  ImGui::SetScrollHereX(center_x_ratio);
}

FFI_EXPORT void imgui_SetScrollHereY(float center_y_ratio) {
  ImGui::SetScrollHereY(center_y_ratio);
}

FFI_EXPORT void imgui_SetScrollFromPosX(float local_x, float center_x_ratio) {
  ImGui::SetScrollFromPosX(local_x, center_x_ratio);
}

FFI_EXPORT void imgui_SetScrollFromPosY(float local_y, float center_y_ratio) {
  ImGui::SetScrollFromPosY(local_y, center_y_ratio);
}

FFI_EXPORT void imgui_PushFont(ImFont* font, float font_size_base_unscaled) {
  ImGui::PushFont(font, font_size_base_unscaled);
}

FFI_EXPORT void imgui_PopFont() {
  ImGui::PopFont();
}

FFI_EXPORT ImFont * imgui_GetFont() {
  return ImGui::GetFont();
}

FFI_EXPORT float imgui_GetFontSize() {
  return ImGui::GetFontSize();
}

FFI_EXPORT ImFontBaked * imgui_GetFontBaked() {
  return ImGui::GetFontBaked();
}

FFI_EXPORT void imgui_PushStyleColor1(ImGuiCol idx, ImU32 col) {
  ImGui::PushStyleColor(idx, col);
}

FFI_EXPORT void imgui_PushStyleColor2(ImGuiCol idx, const ImVec4* col) {
  ImGui::PushStyleColor(idx, *col);
}

FFI_EXPORT void imgui_PopStyleColor(int count) {
  ImGui::PopStyleColor(count);
}

FFI_EXPORT void imgui_PushStyleVar1(ImGuiStyleVar idx, float val) {
  ImGui::PushStyleVar(idx, val);
}

FFI_EXPORT void imgui_PushStyleVar2(ImGuiStyleVar idx, const ImVec2* val) {
  ImGui::PushStyleVar(idx, *val);
}

FFI_EXPORT void imgui_PushStyleVarX(ImGuiStyleVar idx, float val_x) {
  ImGui::PushStyleVarX(idx, val_x);
}

FFI_EXPORT void imgui_PushStyleVarY(ImGuiStyleVar idx, float val_y) {
  ImGui::PushStyleVarY(idx, val_y);
}

FFI_EXPORT void imgui_PopStyleVar(int count) {
  ImGui::PopStyleVar(count);
}

FFI_EXPORT void imgui_PushItemFlag(ImGuiItemFlags option, bool enabled) {
  ImGui::PushItemFlag(option, enabled);
}

FFI_EXPORT void imgui_PopItemFlag() {
  ImGui::PopItemFlag();
}

FFI_EXPORT void imgui_PushItemWidth(float item_width) {
  ImGui::PushItemWidth(item_width);
}

FFI_EXPORT void imgui_PopItemWidth() {
  ImGui::PopItemWidth();
}

FFI_EXPORT void imgui_SetNextItemWidth(float item_width) {
  ImGui::SetNextItemWidth(item_width);
}

FFI_EXPORT float imgui_CalcItemWidth() {
  return ImGui::CalcItemWidth();
}

FFI_EXPORT void imgui_PushTextWrapPos(float wrap_local_pos_x) {
  ImGui::PushTextWrapPos(wrap_local_pos_x);
}

FFI_EXPORT void imgui_PopTextWrapPos() {
  ImGui::PopTextWrapPos();
}

FFI_EXPORT ImVec2_C imgui_GetFontTexUvWhitePixel() {
  const ImVec2& res_cxx = ImGui::GetFontTexUvWhitePixel();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImU32 imgui_GetColorU321(ImGuiCol idx, float alpha_mul) {
  return ImGui::GetColorU32(idx, alpha_mul);
}

FFI_EXPORT ImU32 imgui_GetColorU322(const ImVec4* col) {
  return ImGui::GetColorU32(*col);
}

FFI_EXPORT ImU32 imgui_GetColorU323(ImU32 col, float alpha_mul) {
  return ImGui::GetColorU32(col, alpha_mul);
}

FFI_EXPORT const ImVec4 & imgui_GetStyleColorVec4(ImGuiCol idx) {
  return ImGui::GetStyleColorVec4(idx);
}

FFI_EXPORT ImVec2_C imgui_GetCursorScreenPos() {
  const ImVec2& res_cxx = ImGui::GetCursorScreenPos();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT void imgui_SetCursorScreenPos(const ImVec2* pos) {
  ImGui::SetCursorScreenPos(*pos);
}

FFI_EXPORT ImVec2_C imgui_GetContentRegionAvail() {
  const ImVec2& res_cxx = ImGui::GetContentRegionAvail();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_GetCursorPos() {
  const ImVec2& res_cxx = ImGui::GetCursorPos();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT float imgui_GetCursorPosX() {
  return ImGui::GetCursorPosX();
}

FFI_EXPORT float imgui_GetCursorPosY() {
  return ImGui::GetCursorPosY();
}

FFI_EXPORT void imgui_SetCursorPos(const ImVec2* local_pos) {
  ImGui::SetCursorPos(*local_pos);
}

FFI_EXPORT void imgui_SetCursorPosX(float local_x) {
  ImGui::SetCursorPosX(local_x);
}

FFI_EXPORT void imgui_SetCursorPosY(float local_y) {
  ImGui::SetCursorPosY(local_y);
}

FFI_EXPORT ImVec2_C imgui_GetCursorStartPos() {
  const ImVec2& res_cxx = ImGui::GetCursorStartPos();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT void imgui_Separator() {
  ImGui::Separator();
}

FFI_EXPORT void imgui_SameLine(float offset_from_start_x, float spacing) {
  ImGui::SameLine(offset_from_start_x, spacing);
}

FFI_EXPORT void imgui_NewLine() {
  ImGui::NewLine();
}

FFI_EXPORT void imgui_Spacing() {
  ImGui::Spacing();
}

FFI_EXPORT void imgui_Dummy(const ImVec2* size) {
  ImGui::Dummy(*size);
}

FFI_EXPORT void imgui_Indent(float indent_w) {
  ImGui::Indent(indent_w);
}

FFI_EXPORT void imgui_Unindent(float indent_w) {
  ImGui::Unindent(indent_w);
}

FFI_EXPORT void imgui_BeginGroup() {
  ImGui::BeginGroup();
}

FFI_EXPORT void imgui_EndGroup() {
  ImGui::EndGroup();
}

FFI_EXPORT void imgui_AlignTextToFramePadding() {
  ImGui::AlignTextToFramePadding();
}

FFI_EXPORT float imgui_GetTextLineHeight() {
  return ImGui::GetTextLineHeight();
}

FFI_EXPORT float imgui_GetTextLineHeightWithSpacing() {
  return ImGui::GetTextLineHeightWithSpacing();
}

FFI_EXPORT float imgui_GetFrameHeight() {
  return ImGui::GetFrameHeight();
}

FFI_EXPORT float imgui_GetFrameHeightWithSpacing() {
  return ImGui::GetFrameHeightWithSpacing();
}

FFI_EXPORT void imgui_PushID1(const char* str_id) {
  ImGui::PushID(str_id);
}

FFI_EXPORT void imgui_PushID2(const char* str_id_begin, const char* str_id_end) {
  ImGui::PushID(str_id_begin, str_id_end);
}

FFI_EXPORT void imgui_PushID3(const void* ptr_id) {
  ImGui::PushID(ptr_id);
}

FFI_EXPORT void imgui_PushID4(int int_id) {
  ImGui::PushID(int_id);
}

FFI_EXPORT void imgui_PopID() {
  ImGui::PopID();
}

FFI_EXPORT ImGuiID imgui_GetID1(const char* str_id) {
  return ImGui::GetID(str_id);
}

FFI_EXPORT ImGuiID imgui_GetID2(const char* str_id_begin, const char* str_id_end) {
  return ImGui::GetID(str_id_begin, str_id_end);
}

FFI_EXPORT ImGuiID imgui_GetID3(const void* ptr_id) {
  return ImGui::GetID(ptr_id);
}

FFI_EXPORT ImGuiID imgui_GetID4(int int_id) {
  return ImGui::GetID(int_id);
}

FFI_EXPORT void imgui_TextUnformatted(const char* text, const char* text_end) {
  ImGui::TextUnformatted(text, text_end);
}

FFI_EXPORT void imgui_Text(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::TextV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_TextV(const char* fmt, va_list args) {
  ImGui::TextV(fmt, args);
}

FFI_EXPORT void imgui_TextColored(const ImVec4* col, const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::TextColoredV(*col, fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_TextColoredV(const ImVec4* col, const char* fmt, va_list args) {
  ImGui::TextColoredV(*col, fmt, args);
}

FFI_EXPORT void imgui_TextDisabled(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::TextDisabledV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_TextDisabledV(const char* fmt, va_list args) {
  ImGui::TextDisabledV(fmt, args);
}

FFI_EXPORT void imgui_TextWrapped(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::TextWrappedV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_TextWrappedV(const char* fmt, va_list args) {
  ImGui::TextWrappedV(fmt, args);
}

FFI_EXPORT void imgui_LabelText(const char* label, const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::LabelTextV(label, fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_LabelTextV(const char* label, const char* fmt, va_list args) {
  ImGui::LabelTextV(label, fmt, args);
}

FFI_EXPORT void imgui_BulletText(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::BulletTextV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_BulletTextV(const char* fmt, va_list args) {
  ImGui::BulletTextV(fmt, args);
}

FFI_EXPORT void imgui_SeparatorText(const char* label) {
  ImGui::SeparatorText(label);
}

FFI_EXPORT bool imgui_Button(const char* label, const ImVec2* size) {
  return ImGui::Button(label, *size);
}

FFI_EXPORT bool imgui_SmallButton(const char* label) {
  return ImGui::SmallButton(label);
}

FFI_EXPORT bool imgui_InvisibleButton(const char* str_id, const ImVec2* size, ImGuiButtonFlags flags) {
  return ImGui::InvisibleButton(str_id, *size, flags);
}

FFI_EXPORT bool imgui_ArrowButton(const char* str_id, ImGuiDir dir) {
  return ImGui::ArrowButton(str_id, dir);
}

FFI_EXPORT bool imgui_Checkbox(const char* label, bool* v) {
  return ImGui::Checkbox(label, v);
}

FFI_EXPORT bool imgui_CheckboxFlags1(const char* label, int* flags, int flags_value) {
  return ImGui::CheckboxFlags(label, flags, flags_value);
}

FFI_EXPORT bool imgui_CheckboxFlags2(const char* label, unsigned int* flags, unsigned int flags_value) {
  return ImGui::CheckboxFlags(label, flags, flags_value);
}

FFI_EXPORT bool imgui_RadioButton1(const char* label, bool active) {
  return ImGui::RadioButton(label, active);
}

FFI_EXPORT bool imgui_RadioButton2(const char* label, int* v, int v_button) {
  return ImGui::RadioButton(label, v, v_button);
}

FFI_EXPORT void imgui_ProgressBar(float fraction, const ImVec2* size_arg, const char* overlay) {
  ImGui::ProgressBar(fraction, *size_arg, overlay);
}

FFI_EXPORT void imgui_Bullet() {
  ImGui::Bullet();
}

FFI_EXPORT bool imgui_TextLink(const char* label) {
  return ImGui::TextLink(label);
}

FFI_EXPORT bool imgui_TextLinkOpenURL(const char* label, const char* url) {
  return ImGui::TextLinkOpenURL(label, url);
}

FFI_EXPORT void imgui_Image(ImTextureID tex_ref, const ImVec2* image_size, const ImVec2* uv0, const ImVec2* uv1) {
  ImGui::Image(ImTextureRef(tex_ref), *image_size, *uv0, *uv1);
}

FFI_EXPORT void imgui_ImageWithBg(ImTextureID tex_ref, const ImVec2* image_size, const ImVec2* uv0, const ImVec2* uv1, const ImVec4* bg_col, const ImVec4* tint_col) {
  ImGui::ImageWithBg(ImTextureRef(tex_ref), *image_size, *uv0, *uv1, *bg_col, *tint_col);
}

FFI_EXPORT bool imgui_ImageButton(const char* str_id, ImTextureID tex_ref, const ImVec2* image_size, const ImVec2* uv0, const ImVec2* uv1, const ImVec4* bg_col, const ImVec4* tint_col) {
  return ImGui::ImageButton(str_id, ImTextureRef(tex_ref), *image_size, *uv0, *uv1, *bg_col, *tint_col);
}

FFI_EXPORT bool imgui_BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags) {
  return ImGui::BeginCombo(label, preview_value, flags);
}

FFI_EXPORT void imgui_EndCombo() {
  ImGui::EndCombo();
}

FFI_EXPORT bool imgui_Combo1(const char* label, int* current_item, const char*const items[], int items_count, int popup_max_height_in_items) {
  return ImGui::Combo(label, current_item, items, items_count, popup_max_height_in_items);
}

FFI_EXPORT bool imgui_Combo2(const char* label, int* current_item, const char* items_separated_by_zeros, int popup_max_height_in_items) {
  return ImGui::Combo(label, current_item, items_separated_by_zeros, popup_max_height_in_items);
}

FFI_EXPORT bool imgui_Combo3(const char* label, int* current_item, const char*(*getter)(void*, int), void* user_data, int items_count, int popup_max_height_in_items) {
  return ImGui::Combo(label, current_item, getter, user_data, items_count, popup_max_height_in_items);
}

FFI_EXPORT bool imgui_DragFloat(const char* label, float* v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragFloat(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragFloat2(const char* label, float v[2], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragFloat2(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragFloat3(const char* label, float v[3], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragFloat3(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragFloat4(const char* label, float v[4], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragFloat4(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragFloatRange2(const char* label, float* v_current_min, float* v_current_max, float v_speed, float v_min, float v_max, const char* format, const char* format_max, ImGuiSliderFlags flags) {
  return ImGui::DragFloatRange2(label, v_current_min, v_current_max, v_speed, v_min, v_max, format, format_max, flags);
}

FFI_EXPORT bool imgui_DragInt(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragInt(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragInt2(const char* label, int v[2], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragInt2(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragInt3(const char* label, int v[3], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragInt3(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragInt4(const char* label, int v[4], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragInt4(label, v, v_speed, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_DragIntRange2(const char* label, int* v_current_min, int* v_current_max, float v_speed, int v_min, int v_max, const char* format, const char* format_max, ImGuiSliderFlags flags) {
  return ImGui::DragIntRange2(label, v_current_min, v_current_max, v_speed, v_min, v_max, format, format_max, flags);
}

FFI_EXPORT bool imgui_DragScalar(const char* label, ImGuiDataType data_type, void* p_data, float v_speed, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragScalar(label, data_type, p_data, v_speed, p_min, p_max, format, flags);
}

FFI_EXPORT bool imgui_DragScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, float v_speed, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::DragScalarN(label, data_type, p_data, components, v_speed, p_min, p_max, format, flags);
}

FFI_EXPORT bool imgui_SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderFloat(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderFloat2(const char* label, float v[2], float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderFloat2(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderFloat3(const char* label, float v[3], float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderFloat3(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderFloat4(const char* label, float v[4], float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderFloat4(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderAngle(const char* label, float* v_rad, float v_degrees_min, float v_degrees_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderAngle(label, v_rad, v_degrees_min, v_degrees_max, format, flags);
}

FFI_EXPORT bool imgui_SliderInt(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderInt(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderInt2(const char* label, int v[2], int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderInt2(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderInt3(const char* label, int v[3], int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderInt3(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderInt4(const char* label, int v[4], int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderInt4(label, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_SliderScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderScalar(label, data_type, p_data, p_min, p_max, format, flags);
}

FFI_EXPORT bool imgui_SliderScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::SliderScalarN(label, data_type, p_data, components, p_min, p_max, format, flags);
}

FFI_EXPORT bool imgui_VSliderFloat(const char* label, const ImVec2* size, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::VSliderFloat(label, *size, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_VSliderInt(const char* label, const ImVec2* size, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::VSliderInt(label, *size, v, v_min, v_max, format, flags);
}

FFI_EXPORT bool imgui_VSliderScalar(const char* label, const ImVec2* size, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags) {
  return ImGui::VSliderScalar(label, *size, data_type, p_data, p_min, p_max, format, flags);
}

FFI_EXPORT bool imgui_InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data) {
  return ImGui::InputText(label, buf, buf_size, flags, callback, user_data);
}

FFI_EXPORT bool imgui_InputTextMultiline(const char* label, char* buf, size_t buf_size, const ImVec2* size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data) {
  return ImGui::InputTextMultiline(label, buf, buf_size, *size, flags, callback, user_data);
}

FFI_EXPORT bool imgui_InputTextWithHint(const char* label, const char* hint, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data) {
  return ImGui::InputTextWithHint(label, hint, buf, buf_size, flags, callback, user_data);
}

FFI_EXPORT bool imgui_InputFloat(const char* label, float* v, float step, float step_fast, const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputFloat(label, v, step, step_fast, format, flags);
}

FFI_EXPORT bool imgui_InputFloat2(const char* label, float v[2], const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputFloat2(label, v, format, flags);
}

FFI_EXPORT bool imgui_InputFloat3(const char* label, float v[3], const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputFloat3(label, v, format, flags);
}

FFI_EXPORT bool imgui_InputFloat4(const char* label, float v[4], const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputFloat4(label, v, format, flags);
}

FFI_EXPORT bool imgui_InputInt(const char* label, int* v, int step, int step_fast, ImGuiInputTextFlags flags) {
  return ImGui::InputInt(label, v, step, step_fast, flags);
}

FFI_EXPORT bool imgui_InputInt2(const char* label, int v[2], ImGuiInputTextFlags flags) {
  return ImGui::InputInt2(label, v, flags);
}

FFI_EXPORT bool imgui_InputInt3(const char* label, int v[3], ImGuiInputTextFlags flags) {
  return ImGui::InputInt3(label, v, flags);
}

FFI_EXPORT bool imgui_InputInt4(const char* label, int v[4], ImGuiInputTextFlags flags) {
  return ImGui::InputInt4(label, v, flags);
}

FFI_EXPORT bool imgui_InputDouble(const char* label, double* v, double step, double step_fast, const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputDouble(label, v, step, step_fast, format, flags);
}

FFI_EXPORT bool imgui_InputScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_step, const void* p_step_fast, const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputScalar(label, data_type, p_data, p_step, p_step_fast, format, flags);
}

FFI_EXPORT bool imgui_InputScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, const void* p_step, const void* p_step_fast, const char* format, ImGuiInputTextFlags flags) {
  return ImGui::InputScalarN(label, data_type, p_data, components, p_step, p_step_fast, format, flags);
}

FFI_EXPORT bool imgui_ColorEdit3(const char* label, float col[3], ImGuiColorEditFlags flags) {
  return ImGui::ColorEdit3(label, col, flags);
}

FFI_EXPORT bool imgui_ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags) {
  return ImGui::ColorEdit4(label, col, flags);
}

FFI_EXPORT bool imgui_ColorPicker3(const char* label, float col[3], ImGuiColorEditFlags flags) {
  return ImGui::ColorPicker3(label, col, flags);
}

FFI_EXPORT bool imgui_ColorPicker4(const char* label, float col[4], ImGuiColorEditFlags flags, const float* ref_col) {
  return ImGui::ColorPicker4(label, col, flags, ref_col);
}

FFI_EXPORT bool imgui_ColorButton(const char* desc_id, const ImVec4* col, ImGuiColorEditFlags flags, const ImVec2* size) {
  return ImGui::ColorButton(desc_id, *col, flags, *size);
}

FFI_EXPORT void imgui_SetColorEditOptions(ImGuiColorEditFlags flags) {
  ImGui::SetColorEditOptions(flags);
}

FFI_EXPORT bool imgui_TreeNode1(const char* label) {
  return ImGui::TreeNode(label);
}

FFI_EXPORT bool imgui_TreeNode2(const char* str_id, const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  return ImGui::TreeNodeV(str_id, fmt, args);
  va_end(args);
}

FFI_EXPORT bool imgui_TreeNode3(const void* ptr_id, const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  return ImGui::TreeNodeV(ptr_id, fmt, args);
  va_end(args);
}

FFI_EXPORT bool imgui_TreeNodeV1(const char* str_id, const char* fmt, va_list args) {
  return ImGui::TreeNodeV(str_id, fmt, args);
}

FFI_EXPORT bool imgui_TreeNodeV2(const void* ptr_id, const char* fmt, va_list args) {
  return ImGui::TreeNodeV(ptr_id, fmt, args);
}

FFI_EXPORT bool imgui_TreeNodeEx1(const char* label, ImGuiTreeNodeFlags flags) {
  return ImGui::TreeNodeEx(label, flags);
}

FFI_EXPORT bool imgui_TreeNodeEx2(const char* str_id, ImGuiTreeNodeFlags flags, const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  return ImGui::TreeNodeExV(str_id, flags, fmt, args);
  va_end(args);
}

FFI_EXPORT bool imgui_TreeNodeEx3(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  return ImGui::TreeNodeExV(ptr_id, flags, fmt, args);
  va_end(args);
}

FFI_EXPORT bool imgui_TreeNodeExV1(const char* str_id, ImGuiTreeNodeFlags flags, const char* fmt, va_list args) {
  return ImGui::TreeNodeExV(str_id, flags, fmt, args);
}

FFI_EXPORT bool imgui_TreeNodeExV2(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* fmt, va_list args) {
  return ImGui::TreeNodeExV(ptr_id, flags, fmt, args);
}

FFI_EXPORT void imgui_TreePush1(const char* str_id) {
  ImGui::TreePush(str_id);
}

FFI_EXPORT void imgui_TreePush2(const void* ptr_id) {
  ImGui::TreePush(ptr_id);
}

FFI_EXPORT void imgui_TreePop() {
  ImGui::TreePop();
}

FFI_EXPORT float imgui_GetTreeNodeToLabelSpacing() {
  return ImGui::GetTreeNodeToLabelSpacing();
}

FFI_EXPORT bool imgui_CollapsingHeader1(const char* label, ImGuiTreeNodeFlags flags) {
  return ImGui::CollapsingHeader(label, flags);
}

FFI_EXPORT bool imgui_CollapsingHeader2(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags) {
  return ImGui::CollapsingHeader(label, p_visible, flags);
}

FFI_EXPORT void imgui_SetNextItemOpen(bool is_open, ImGuiCond cond) {
  ImGui::SetNextItemOpen(is_open, cond);
}

FFI_EXPORT void imgui_SetNextItemStorageID(ImGuiID storage_id) {
  ImGui::SetNextItemStorageID(storage_id);
}

FFI_EXPORT bool imgui_Selectable1(const char* label, bool selected, ImGuiSelectableFlags flags, const ImVec2* size) {
  return ImGui::Selectable(label, selected, flags, *size);
}

FFI_EXPORT bool imgui_Selectable2(const char* label, bool* p_selected, ImGuiSelectableFlags flags, const ImVec2* size) {
  return ImGui::Selectable(label, p_selected, flags, *size);
}

FFI_EXPORT ImGuiMultiSelectIO * imgui_BeginMultiSelect(ImGuiMultiSelectFlags flags, int selection_size, int items_count) {
  return ImGui::BeginMultiSelect(flags, selection_size, items_count);
}

FFI_EXPORT ImGuiMultiSelectIO * imgui_EndMultiSelect() {
  return ImGui::EndMultiSelect();
}

FFI_EXPORT void imgui_SetNextItemSelectionUserData(ImGuiSelectionUserData selection_user_data) {
  ImGui::SetNextItemSelectionUserData(selection_user_data);
}

FFI_EXPORT bool imgui_IsItemToggledSelection() {
  return ImGui::IsItemToggledSelection();
}

FFI_EXPORT bool imgui_BeginListBox(const char* label, const ImVec2* size) {
  return ImGui::BeginListBox(label, *size);
}

FFI_EXPORT void imgui_EndListBox() {
  ImGui::EndListBox();
}

FFI_EXPORT bool imgui_ListBox1(const char* label, int* current_item, const char*const items[], int items_count, int height_in_items) {
  return ImGui::ListBox(label, current_item, items, items_count, height_in_items);
}

FFI_EXPORT bool imgui_ListBox2(const char* label, int* current_item, const char*(*getter)(void*, int), void* user_data, int items_count, int height_in_items) {
  return ImGui::ListBox(label, current_item, getter, user_data, items_count, height_in_items);
}

FFI_EXPORT void imgui_PlotLines1(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 graph_size, int stride) {
  ImGui::PlotLines(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size, stride);
}

FFI_EXPORT void imgui_PlotLines2(const char* label, float (*values_getter)(void*, int), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 graph_size) {
  ImGui::PlotLines(label, values_getter, data, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size);
}

FFI_EXPORT void imgui_PlotHistogram1(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 graph_size, int stride) {
  ImGui::PlotHistogram(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size, stride);
}

FFI_EXPORT void imgui_PlotHistogram2(const char* label, float (*values_getter)(void*, int), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2 graph_size) {
  ImGui::PlotHistogram(label, values_getter, data, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size);
}

FFI_EXPORT void imgui_Value1(const char* prefix, bool b) {
  ImGui::Value(prefix, b);
}

FFI_EXPORT void imgui_Value2(const char* prefix, int v) {
  ImGui::Value(prefix, v);
}

FFI_EXPORT void imgui_Value3(const char* prefix, unsigned int v) {
  ImGui::Value(prefix, v);
}

FFI_EXPORT void imgui_Value4(const char* prefix, float v, const char* float_format) {
  ImGui::Value(prefix, v, float_format);
}

FFI_EXPORT bool imgui_BeginMenuBar() {
  return ImGui::BeginMenuBar();
}

FFI_EXPORT void imgui_EndMenuBar() {
  ImGui::EndMenuBar();
}

FFI_EXPORT bool imgui_BeginMainMenuBar() {
  return ImGui::BeginMainMenuBar();
}

FFI_EXPORT void imgui_EndMainMenuBar() {
  ImGui::EndMainMenuBar();
}

FFI_EXPORT bool imgui_BeginMenu(const char* label, bool enabled) {
  return ImGui::BeginMenu(label, enabled);
}

FFI_EXPORT void imgui_EndMenu() {
  ImGui::EndMenu();
}

FFI_EXPORT bool imgui_MenuItem1(const char* label, const char* shortcut, bool selected, bool enabled) {
  return ImGui::MenuItem(label, shortcut, selected, enabled);
}

FFI_EXPORT bool imgui_MenuItem2(const char* label, const char* shortcut, bool* p_selected, bool enabled) {
  return ImGui::MenuItem(label, shortcut, p_selected, enabled);
}

FFI_EXPORT bool imgui_BeginTooltip() {
  return ImGui::BeginTooltip();
}

FFI_EXPORT void imgui_EndTooltip() {
  ImGui::EndTooltip();
}

FFI_EXPORT void imgui_SetTooltip(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::SetTooltipV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_SetTooltipV(const char* fmt, va_list args) {
  ImGui::SetTooltipV(fmt, args);
}

FFI_EXPORT bool imgui_BeginItemTooltip() {
  return ImGui::BeginItemTooltip();
}

FFI_EXPORT void imgui_SetItemTooltip(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::SetItemTooltipV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_SetItemTooltipV(const char* fmt, va_list args) {
  ImGui::SetItemTooltipV(fmt, args);
}

FFI_EXPORT bool imgui_BeginPopup(const char* str_id, ImGuiWindowFlags flags) {
  return ImGui::BeginPopup(str_id, flags);
}

FFI_EXPORT bool imgui_BeginPopupModal(const char* name, bool* p_open, ImGuiWindowFlags flags) {
  return ImGui::BeginPopupModal(name, p_open, flags);
}

FFI_EXPORT void imgui_EndPopup() {
  ImGui::EndPopup();
}

FFI_EXPORT void imgui_OpenPopup1(const char* str_id, ImGuiPopupFlags popup_flags) {
  ImGui::OpenPopup(str_id, popup_flags);
}

FFI_EXPORT void imgui_OpenPopup2(ImGuiID id, ImGuiPopupFlags popup_flags) {
  ImGui::OpenPopup(id, popup_flags);
}

FFI_EXPORT void imgui_OpenPopupOnItemClick(const char* str_id, ImGuiPopupFlags popup_flags) {
  ImGui::OpenPopupOnItemClick(str_id, popup_flags);
}

FFI_EXPORT void imgui_CloseCurrentPopup() {
  ImGui::CloseCurrentPopup();
}

FFI_EXPORT bool imgui_BeginPopupContextItem(const char* str_id, ImGuiPopupFlags popup_flags) {
  return ImGui::BeginPopupContextItem(str_id, popup_flags);
}

FFI_EXPORT bool imgui_BeginPopupContextWindow(const char* str_id, ImGuiPopupFlags popup_flags) {
  return ImGui::BeginPopupContextWindow(str_id, popup_flags);
}

FFI_EXPORT bool imgui_BeginPopupContextVoid(const char* str_id, ImGuiPopupFlags popup_flags) {
  return ImGui::BeginPopupContextVoid(str_id, popup_flags);
}

FFI_EXPORT bool imgui_IsPopupOpen(const char* str_id, ImGuiPopupFlags flags) {
  return ImGui::IsPopupOpen(str_id, flags);
}

FFI_EXPORT bool imgui_BeginTable(const char* str_id, int columns, ImGuiTableFlags flags, const ImVec2* outer_size, float inner_width) {
  return ImGui::BeginTable(str_id, columns, flags, *outer_size, inner_width);
}

FFI_EXPORT void imgui_EndTable() {
  ImGui::EndTable();
}

FFI_EXPORT void imgui_TableNextRow(ImGuiTableRowFlags row_flags, float min_row_height) {
  ImGui::TableNextRow(row_flags, min_row_height);
}

FFI_EXPORT bool imgui_TableNextColumn() {
  return ImGui::TableNextColumn();
}

FFI_EXPORT bool imgui_TableSetColumnIndex(int column_n) {
  return ImGui::TableSetColumnIndex(column_n);
}

FFI_EXPORT void imgui_TableSetupColumn(const char* label, ImGuiTableColumnFlags flags, float init_width_or_weight, ImGuiID user_id) {
  ImGui::TableSetupColumn(label, flags, init_width_or_weight, user_id);
}

FFI_EXPORT void imgui_TableSetupScrollFreeze(int cols, int rows) {
  ImGui::TableSetupScrollFreeze(cols, rows);
}

FFI_EXPORT void imgui_TableHeader(const char* label) {
  ImGui::TableHeader(label);
}

FFI_EXPORT void imgui_TableHeadersRow() {
  ImGui::TableHeadersRow();
}

FFI_EXPORT void imgui_TableAngledHeadersRow() {
  ImGui::TableAngledHeadersRow();
}

FFI_EXPORT ImGuiTableSortSpecs * imgui_TableGetSortSpecs() {
  return ImGui::TableGetSortSpecs();
}

FFI_EXPORT int imgui_TableGetColumnCount() {
  return ImGui::TableGetColumnCount();
}

FFI_EXPORT int imgui_TableGetColumnIndex() {
  return ImGui::TableGetColumnIndex();
}

FFI_EXPORT int imgui_TableGetRowIndex() {
  return ImGui::TableGetRowIndex();
}

FFI_EXPORT const char * imgui_TableGetColumnName(int column_n) {
  return ImGui::TableGetColumnName(column_n);
}

FFI_EXPORT ImGuiTableColumnFlags imgui_TableGetColumnFlags(int column_n) {
  return ImGui::TableGetColumnFlags(column_n);
}

FFI_EXPORT void imgui_TableSetColumnEnabled(int column_n, bool v) {
  ImGui::TableSetColumnEnabled(column_n, v);
}

FFI_EXPORT int imgui_TableGetHoveredColumn() {
  return ImGui::TableGetHoveredColumn();
}

FFI_EXPORT void imgui_TableSetBgColor(ImGuiTableBgTarget target, ImU32 color, int column_n) {
  ImGui::TableSetBgColor(target, color, column_n);
}

FFI_EXPORT void imgui_Columns(int count, const char* id, bool borders) {
  ImGui::Columns(count, id, borders);
}

FFI_EXPORT void imgui_NextColumn() {
  ImGui::NextColumn();
}

FFI_EXPORT int imgui_GetColumnIndex() {
  return ImGui::GetColumnIndex();
}

FFI_EXPORT float imgui_GetColumnWidth(int column_index) {
  return ImGui::GetColumnWidth(column_index);
}

FFI_EXPORT void imgui_SetColumnWidth(int column_index, float width) {
  ImGui::SetColumnWidth(column_index, width);
}

FFI_EXPORT float imgui_GetColumnOffset(int column_index) {
  return ImGui::GetColumnOffset(column_index);
}

FFI_EXPORT void imgui_SetColumnOffset(int column_index, float offset_x) {
  ImGui::SetColumnOffset(column_index, offset_x);
}

FFI_EXPORT int imgui_GetColumnsCount() {
  return ImGui::GetColumnsCount();
}

FFI_EXPORT bool imgui_BeginTabBar(const char* str_id, ImGuiTabBarFlags flags) {
  return ImGui::BeginTabBar(str_id, flags);
}

FFI_EXPORT void imgui_EndTabBar() {
  ImGui::EndTabBar();
}

FFI_EXPORT bool imgui_BeginTabItem(const char* label, bool* p_open, ImGuiTabItemFlags flags) {
  return ImGui::BeginTabItem(label, p_open, flags);
}

FFI_EXPORT void imgui_EndTabItem() {
  ImGui::EndTabItem();
}

FFI_EXPORT bool imgui_TabItemButton(const char* label, ImGuiTabItemFlags flags) {
  return ImGui::TabItemButton(label, flags);
}

FFI_EXPORT void imgui_SetTabItemClosed(const char* tab_or_docked_window_label) {
  ImGui::SetTabItemClosed(tab_or_docked_window_label);
}

FFI_EXPORT void imgui_LogToTTY(int auto_open_depth) {
  ImGui::LogToTTY(auto_open_depth);
}

FFI_EXPORT void imgui_LogToFile(int auto_open_depth, const char* filename) {
  ImGui::LogToFile(auto_open_depth, filename);
}

FFI_EXPORT void imgui_LogToClipboard(int auto_open_depth) {
  ImGui::LogToClipboard(auto_open_depth);
}

FFI_EXPORT void imgui_LogFinish() {
  ImGui::LogFinish();
}

FFI_EXPORT void imgui_LogButtons() {
  ImGui::LogButtons();
}

FFI_EXPORT void imgui_LogText(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::LogTextV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_LogTextV(const char* fmt, va_list args) {
  ImGui::LogTextV(fmt, args);
}

FFI_EXPORT bool imgui_BeginDragDropSource(ImGuiDragDropFlags flags) {
  return ImGui::BeginDragDropSource(flags);
}

FFI_EXPORT bool imgui_SetDragDropPayload(const char* type, const void* data, size_t sz, ImGuiCond cond) {
  return ImGui::SetDragDropPayload(type, data, sz, cond);
}

FFI_EXPORT void imgui_EndDragDropSource() {
  ImGui::EndDragDropSource();
}

FFI_EXPORT bool imgui_BeginDragDropTarget() {
  return ImGui::BeginDragDropTarget();
}

FFI_EXPORT const ImGuiPayload * imgui_AcceptDragDropPayload(const char* type, ImGuiDragDropFlags flags) {
  return ImGui::AcceptDragDropPayload(type, flags);
}

FFI_EXPORT void imgui_EndDragDropTarget() {
  ImGui::EndDragDropTarget();
}

FFI_EXPORT const ImGuiPayload * imgui_GetDragDropPayload() {
  return ImGui::GetDragDropPayload();
}

FFI_EXPORT void imgui_BeginDisabled(bool disabled) {
  ImGui::BeginDisabled(disabled);
}

FFI_EXPORT void imgui_EndDisabled() {
  ImGui::EndDisabled();
}

FFI_EXPORT void imgui_PushClipRect(const ImVec2* clip_rect_min, const ImVec2* clip_rect_max, bool intersect_with_current_clip_rect) {
  ImGui::PushClipRect(*clip_rect_min, *clip_rect_max, intersect_with_current_clip_rect);
}

FFI_EXPORT void imgui_PopClipRect() {
  ImGui::PopClipRect();
}

FFI_EXPORT void imgui_SetItemDefaultFocus() {
  ImGui::SetItemDefaultFocus();
}

FFI_EXPORT void imgui_SetKeyboardFocusHere(int offset) {
  ImGui::SetKeyboardFocusHere(offset);
}

FFI_EXPORT void imgui_SetNavCursorVisible(bool visible) {
  ImGui::SetNavCursorVisible(visible);
}

FFI_EXPORT void imgui_SetNextItemAllowOverlap() {
  ImGui::SetNextItemAllowOverlap();
}

FFI_EXPORT bool imgui_IsItemHovered(ImGuiHoveredFlags flags) {
  return ImGui::IsItemHovered(flags);
}

FFI_EXPORT bool imgui_IsItemActive() {
  return ImGui::IsItemActive();
}

FFI_EXPORT bool imgui_IsItemFocused() {
  return ImGui::IsItemFocused();
}

FFI_EXPORT bool imgui_IsItemClicked(ImGuiMouseButton mouse_button) {
  return ImGui::IsItemClicked(mouse_button);
}

FFI_EXPORT bool imgui_IsItemVisible() {
  return ImGui::IsItemVisible();
}

FFI_EXPORT bool imgui_IsItemEdited() {
  return ImGui::IsItemEdited();
}

FFI_EXPORT bool imgui_IsItemActivated() {
  return ImGui::IsItemActivated();
}

FFI_EXPORT bool imgui_IsItemDeactivated() {
  return ImGui::IsItemDeactivated();
}

FFI_EXPORT bool imgui_IsItemDeactivatedAfterEdit() {
  return ImGui::IsItemDeactivatedAfterEdit();
}

FFI_EXPORT bool imgui_IsItemToggledOpen() {
  return ImGui::IsItemToggledOpen();
}

FFI_EXPORT bool imgui_IsAnyItemHovered() {
  return ImGui::IsAnyItemHovered();
}

FFI_EXPORT bool imgui_IsAnyItemActive() {
  return ImGui::IsAnyItemActive();
}

FFI_EXPORT bool imgui_IsAnyItemFocused() {
  return ImGui::IsAnyItemFocused();
}

FFI_EXPORT ImGuiID imgui_GetItemID() {
  return ImGui::GetItemID();
}

FFI_EXPORT ImVec2_C imgui_GetItemRectMin() {
  const ImVec2& res_cxx = ImGui::GetItemRectMin();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_GetItemRectMax() {
  const ImVec2& res_cxx = ImGui::GetItemRectMax();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_GetItemRectSize() {
  const ImVec2& res_cxx = ImGui::GetItemRectSize();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImGuiViewport * imgui_GetMainViewport() {
  return ImGui::GetMainViewport();
}

FFI_EXPORT ImDrawList * imgui_GetBackgroundDrawList() {
  return ImGui::GetBackgroundDrawList();
}

FFI_EXPORT ImDrawList * imgui_GetForegroundDrawList() {
  return ImGui::GetForegroundDrawList();
}

FFI_EXPORT bool imgui_IsRectVisible1(const ImVec2* size) {
  return ImGui::IsRectVisible(*size);
}

FFI_EXPORT bool imgui_IsRectVisible2(const ImVec2* rect_min, const ImVec2* rect_max) {
  return ImGui::IsRectVisible(*rect_min, *rect_max);
}

FFI_EXPORT double imgui_GetTime() {
  return ImGui::GetTime();
}

FFI_EXPORT int imgui_GetFrameCount() {
  return ImGui::GetFrameCount();
}

FFI_EXPORT ImDrawListSharedData * imgui_GetDrawListSharedData() {
  return ImGui::GetDrawListSharedData();
}

FFI_EXPORT const char * imgui_GetStyleColorName(ImGuiCol idx) {
  return ImGui::GetStyleColorName(idx);
}

FFI_EXPORT void imgui_SetStateStorage(ImGuiStorage* storage) {
  ImGui::SetStateStorage(storage);
}

FFI_EXPORT ImGuiStorage * imgui_GetStateStorage() {
  return ImGui::GetStateStorage();
}

FFI_EXPORT ImVec2_C imgui_CalcTextSize(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width) {
  const ImVec2& res_cxx = ImGui::CalcTextSize(text, text_end, hide_text_after_double_hash, wrap_width);
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec4_C imgui_ColorConvertU32ToFloat4(ImU32 _in) {
  const ImVec4& res_cxx = ImGui::ColorConvertU32ToFloat4(_in);
  ImVec4_C res_c = {res_cxx.x, res_cxx.y, res_cxx.z, res_cxx.w};
  return res_c;
}

FFI_EXPORT ImU32 imgui_ColorConvertFloat4ToU32(const ImVec4* _in) {
  return ImGui::ColorConvertFloat4ToU32(*_in);
}

FFI_EXPORT void imgui_ColorConvertRGBtoHSV(float r, float g, float b, float* out_h, float* out_s, float* out_v) {
  ImGui::ColorConvertRGBtoHSV(r, g, b, *out_h, *out_s, *out_v);
}

FFI_EXPORT void imgui_ColorConvertHSVtoRGB(float h, float s, float v, float* out_r, float* out_g, float* out_b) {
  ImGui::ColorConvertHSVtoRGB(h, s, v, *out_r, *out_g, *out_b);
}

FFI_EXPORT bool imgui_IsKeyDown(ImGuiKey key) {
  return ImGui::IsKeyDown(key);
}

FFI_EXPORT bool imgui_IsKeyPressed(ImGuiKey key, bool _repeat) {
  return ImGui::IsKeyPressed(key, _repeat);
}

FFI_EXPORT bool imgui_IsKeyReleased(ImGuiKey key) {
  return ImGui::IsKeyReleased(key);
}

FFI_EXPORT bool imgui_IsKeyChordPressed(ImGuiKeyChord key_chord) {
  return ImGui::IsKeyChordPressed(key_chord);
}

FFI_EXPORT int imgui_GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate) {
  return ImGui::GetKeyPressedAmount(key, repeat_delay, rate);
}

FFI_EXPORT const char * imgui_GetKeyName(ImGuiKey key) {
  return ImGui::GetKeyName(key);
}

FFI_EXPORT void imgui_SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard) {
  ImGui::SetNextFrameWantCaptureKeyboard(want_capture_keyboard);
}

FFI_EXPORT bool imgui_Shortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags) {
  return ImGui::Shortcut(key_chord, flags);
}

FFI_EXPORT void imgui_SetNextItemShortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags) {
  ImGui::SetNextItemShortcut(key_chord, flags);
}

FFI_EXPORT void imgui_SetItemKeyOwner(ImGuiKey key) {
  ImGui::SetItemKeyOwner(key);
}

FFI_EXPORT bool imgui_IsMouseDown(ImGuiMouseButton button) {
  return ImGui::IsMouseDown(button);
}

FFI_EXPORT bool imgui_IsMouseClicked(ImGuiMouseButton button, bool _repeat) {
  return ImGui::IsMouseClicked(button, _repeat);
}

FFI_EXPORT bool imgui_IsMouseReleased(ImGuiMouseButton button) {
  return ImGui::IsMouseReleased(button);
}

FFI_EXPORT bool imgui_IsMouseDoubleClicked(ImGuiMouseButton button) {
  return ImGui::IsMouseDoubleClicked(button);
}

FFI_EXPORT bool imgui_IsMouseReleasedWithDelay(ImGuiMouseButton button, float delay) {
  return ImGui::IsMouseReleasedWithDelay(button, delay);
}

FFI_EXPORT int imgui_GetMouseClickedCount(ImGuiMouseButton button) {
  return ImGui::GetMouseClickedCount(button);
}

FFI_EXPORT bool imgui_IsMouseHoveringRect(const ImVec2* r_min, const ImVec2* r_max, bool clip) {
  return ImGui::IsMouseHoveringRect(*r_min, *r_max, clip);
}

FFI_EXPORT bool imgui_IsMousePosValid(const ImVec2* mouse_pos) {
  return ImGui::IsMousePosValid(mouse_pos);
}

FFI_EXPORT bool imgui_IsAnyMouseDown() {
  return ImGui::IsAnyMouseDown();
}

FFI_EXPORT ImVec2_C imgui_GetMousePos() {
  const ImVec2& res_cxx = ImGui::GetMousePos();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_GetMousePosOnOpeningCurrentPopup() {
  const ImVec2& res_cxx = ImGui::GetMousePosOnOpeningCurrentPopup();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT bool imgui_IsMouseDragging(ImGuiMouseButton button, float lock_threshold) {
  return ImGui::IsMouseDragging(button, lock_threshold);
}

FFI_EXPORT ImVec2_C imgui_GetMouseDragDelta(ImGuiMouseButton button, float lock_threshold) {
  const ImVec2& res_cxx = ImGui::GetMouseDragDelta(button, lock_threshold);
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT void imgui_ResetMouseDragDelta(ImGuiMouseButton button) {
  ImGui::ResetMouseDragDelta(button);
}

FFI_EXPORT ImGuiMouseCursor imgui_GetMouseCursor() {
  return ImGui::GetMouseCursor();
}

FFI_EXPORT void imgui_SetMouseCursor(ImGuiMouseCursor cursor_type) {
  ImGui::SetMouseCursor(cursor_type);
}

FFI_EXPORT void imgui_SetNextFrameWantCaptureMouse(bool want_capture_mouse) {
  ImGui::SetNextFrameWantCaptureMouse(want_capture_mouse);
}

FFI_EXPORT const char * imgui_GetClipboardText() {
  return ImGui::GetClipboardText();
}

FFI_EXPORT void imgui_SetClipboardText(const char* text) {
  ImGui::SetClipboardText(text);
}

FFI_EXPORT void imgui_DebugTextEncoding(const char* text) {
  ImGui::DebugTextEncoding(text);
}

FFI_EXPORT void imgui_DebugFlashStyleColor(ImGuiCol idx) {
  ImGui::DebugFlashStyleColor(idx);
}

FFI_EXPORT void imgui_DebugStartItemPicker() {
  ImGui::DebugStartItemPicker();
}

FFI_EXPORT bool imgui_DebugCheckVersionAndDataLayout(const char* version_str, size_t sz_io, size_t sz_style, size_t sz_vec2, size_t sz_vec4, size_t sz_drawvert, size_t sz_drawidx) {
  return ImGui::DebugCheckVersionAndDataLayout(version_str, sz_io, sz_style, sz_vec2, sz_vec4, sz_drawvert, sz_drawidx);
}

FFI_EXPORT void imgui_DebugLog(const char* fmt, ...) {
  va_list args;
  va_start(args, fmt);
  ImGui::DebugLogV(fmt, args);
  va_end(args);
}

FFI_EXPORT void imgui_DebugLogV(const char* fmt, va_list args) {
  ImGui::DebugLogV(fmt, args);
}

FFI_EXPORT void imgui_GetAllocatorFunctions(ImGuiMemAllocFunc* p_alloc_func, ImGuiMemFreeFunc* p_free_func, void** p_user_data) {
  ImGui::GetAllocatorFunctions(p_alloc_func, p_free_func, p_user_data);
}

FFI_EXPORT void imgui_ImGuiStyle_ScaleAllSizes(ImGuiStyle* ImGuiStyle_ctx, float scale_factor) {
  ImGuiStyle_ctx->ScaleAllSizes(scale_factor);
}

FFI_EXPORT void imgui_ImGuiIO_AddKeyEvent(ImGuiIO* ImGuiIO_ctx, ImGuiKey key, bool down) {
  ImGuiIO_ctx->AddKeyEvent(key, down);
}

FFI_EXPORT void imgui_ImGuiIO_AddKeyAnalogEvent(ImGuiIO* ImGuiIO_ctx, ImGuiKey key, bool down, float v) {
  ImGuiIO_ctx->AddKeyAnalogEvent(key, down, v);
}

FFI_EXPORT void imgui_ImGuiIO_AddMousePosEvent(ImGuiIO* ImGuiIO_ctx, float x, float y) {
  ImGuiIO_ctx->AddMousePosEvent(x, y);
}

FFI_EXPORT void imgui_ImGuiIO_AddMouseButtonEvent(ImGuiIO* ImGuiIO_ctx, int button, bool down) {
  ImGuiIO_ctx->AddMouseButtonEvent(button, down);
}

FFI_EXPORT void imgui_ImGuiIO_AddMouseWheelEvent(ImGuiIO* ImGuiIO_ctx, float wheel_x, float wheel_y) {
  ImGuiIO_ctx->AddMouseWheelEvent(wheel_x, wheel_y);
}

FFI_EXPORT void imgui_ImGuiIO_AddMouseSourceEvent(ImGuiIO* ImGuiIO_ctx, ImGuiMouseSource source) {
  ImGuiIO_ctx->AddMouseSourceEvent(source);
}

FFI_EXPORT void imgui_ImGuiIO_AddFocusEvent(ImGuiIO* ImGuiIO_ctx, bool focused) {
  ImGuiIO_ctx->AddFocusEvent(focused);
}

FFI_EXPORT void imgui_ImGuiIO_AddInputCharacter(ImGuiIO* ImGuiIO_ctx, unsigned int c) {
  ImGuiIO_ctx->AddInputCharacter(c);
}

FFI_EXPORT void imgui_ImGuiIO_AddInputCharacterUTF16(ImGuiIO* ImGuiIO_ctx, ImWchar16 c) {
  ImGuiIO_ctx->AddInputCharacterUTF16(c);
}

FFI_EXPORT void imgui_ImGuiIO_AddInputCharactersUTF8(ImGuiIO* ImGuiIO_ctx, const char* str) {
  ImGuiIO_ctx->AddInputCharactersUTF8(str);
}

FFI_EXPORT void imgui_ImGuiIO_SetKeyEventNativeData(ImGuiIO* ImGuiIO_ctx, ImGuiKey key, int native_keycode, int native_scancode, int native_legacy_index) {
  ImGuiIO_ctx->SetKeyEventNativeData(key, native_keycode, native_scancode, native_legacy_index);
}

FFI_EXPORT void imgui_ImGuiIO_SetAppAcceptingEvents(ImGuiIO* ImGuiIO_ctx, bool accepting_events) {
  ImGuiIO_ctx->SetAppAcceptingEvents(accepting_events);
}

FFI_EXPORT void imgui_ImGuiIO_ClearEventsQueue(ImGuiIO* ImGuiIO_ctx) {
  ImGuiIO_ctx->ClearEventsQueue();
}

FFI_EXPORT void imgui_ImGuiIO_ClearInputKeys(ImGuiIO* ImGuiIO_ctx) {
  ImGuiIO_ctx->ClearInputKeys();
}

FFI_EXPORT void imgui_ImGuiIO_ClearInputMouse(ImGuiIO* ImGuiIO_ctx) {
  ImGuiIO_ctx->ClearInputMouse();
}

FFI_EXPORT void imgui_ImGuiInputTextCallbackData_DeleteChars(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx, int pos, int bytes_count) {
  ImGuiInputTextCallbackData_ctx->DeleteChars(pos, bytes_count);
}

FFI_EXPORT void imgui_ImGuiInputTextCallbackData_InsertChars(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx, int pos, const char* text, const char* text_end) {
  ImGuiInputTextCallbackData_ctx->InsertChars(pos, text, text_end);
}

FFI_EXPORT void imgui_ImGuiInputTextCallbackData_SelectAll(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx) {
  ImGuiInputTextCallbackData_ctx->SelectAll();
}

FFI_EXPORT void imgui_ImGuiInputTextCallbackData_ClearSelection(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx) {
  ImGuiInputTextCallbackData_ctx->ClearSelection();
}

FFI_EXPORT bool imgui_ImGuiInputTextCallbackData_HasSelection(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx) {
  return ImGuiInputTextCallbackData_ctx->HasSelection();
}

FFI_EXPORT void imgui_ImGuiPayload_Clear(ImGuiPayload* ImGuiPayload_ctx) {
  ImGuiPayload_ctx->Clear();
}

FFI_EXPORT bool imgui_ImGuiPayload_IsDataType(ImGuiPayload* ImGuiPayload_ctx, const char* type) {
  return ImGuiPayload_ctx->IsDataType(type);
}

FFI_EXPORT bool imgui_ImGuiPayload_IsPreview(ImGuiPayload* ImGuiPayload_ctx) {
  return ImGuiPayload_ctx->IsPreview();
}

FFI_EXPORT bool imgui_ImGuiPayload_IsDelivery(ImGuiPayload* ImGuiPayload_ctx) {
  return ImGuiPayload_ctx->IsDelivery();
}

FFI_EXPORT bool imgui_ImGuiTextFilter_Draw(ImGuiTextFilter* ImGuiTextFilter_ctx, const char* label, float width) {
  return ImGuiTextFilter_ctx->Draw(label, width);
}

FFI_EXPORT bool imgui_ImGuiTextFilter_PassFilter(ImGuiTextFilter* ImGuiTextFilter_ctx, const char* text, const char* text_end) {
  return ImGuiTextFilter_ctx->PassFilter(text, text_end);
}

FFI_EXPORT void imgui_ImGuiTextFilter_Build(ImGuiTextFilter* ImGuiTextFilter_ctx) {
  ImGuiTextFilter_ctx->Build();
}

FFI_EXPORT void imgui_ImGuiTextFilter_Clear(ImGuiTextFilter* ImGuiTextFilter_ctx) {
  ImGuiTextFilter_ctx->Clear();
}

FFI_EXPORT bool imgui_ImGuiTextFilter_IsActive(ImGuiTextFilter* ImGuiTextFilter_ctx) {
  return ImGuiTextFilter_ctx->IsActive();
}

FFI_EXPORT const char * imgui_ImGuiTextBuffer_begin(ImGuiTextBuffer* ImGuiTextBuffer_ctx) {
  return ImGuiTextBuffer_ctx->begin();
}

FFI_EXPORT const char * imgui_ImGuiTextBuffer_end(ImGuiTextBuffer* ImGuiTextBuffer_ctx) {
  return ImGuiTextBuffer_ctx->end();
}

FFI_EXPORT int imgui_ImGuiTextBuffer_size(ImGuiTextBuffer* ImGuiTextBuffer_ctx) {
  return ImGuiTextBuffer_ctx->size();
}

FFI_EXPORT bool imgui_ImGuiTextBuffer_empty(ImGuiTextBuffer* ImGuiTextBuffer_ctx) {
  return ImGuiTextBuffer_ctx->empty();
}

FFI_EXPORT void imgui_ImGuiTextBuffer_clear(ImGuiTextBuffer* ImGuiTextBuffer_ctx) {
  ImGuiTextBuffer_ctx->clear();
}

FFI_EXPORT void imgui_ImGuiTextBuffer_resize(ImGuiTextBuffer* ImGuiTextBuffer_ctx, int size) {
  ImGuiTextBuffer_ctx->resize(size);
}

FFI_EXPORT void imgui_ImGuiTextBuffer_reserve(ImGuiTextBuffer* ImGuiTextBuffer_ctx, int capacity) {
  ImGuiTextBuffer_ctx->reserve(capacity);
}

FFI_EXPORT const char * imgui_ImGuiTextBuffer_c_str(ImGuiTextBuffer* ImGuiTextBuffer_ctx) {
  return ImGuiTextBuffer_ctx->c_str();
}

FFI_EXPORT void imgui_ImGuiTextBuffer_append(ImGuiTextBuffer* ImGuiTextBuffer_ctx, const char* str, const char* str_end) {
  ImGuiTextBuffer_ctx->append(str, str_end);
}

FFI_EXPORT void imgui_ImGuiTextBuffer_appendfv(ImGuiTextBuffer* ImGuiTextBuffer_ctx, const char* fmt, va_list args) {
  ImGuiTextBuffer_ctx->appendfv(fmt, args);
}

FFI_EXPORT void imgui_ImGuiStorage_Clear(ImGuiStorage* ImGuiStorage_ctx) {
  ImGuiStorage_ctx->Clear();
}

FFI_EXPORT int imgui_ImGuiStorage_GetInt(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, int default_val) {
  return ImGuiStorage_ctx->GetInt(key, default_val);
}

FFI_EXPORT void imgui_ImGuiStorage_SetInt(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, int val) {
  ImGuiStorage_ctx->SetInt(key, val);
}

FFI_EXPORT bool imgui_ImGuiStorage_GetBool(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, bool default_val) {
  return ImGuiStorage_ctx->GetBool(key, default_val);
}

FFI_EXPORT void imgui_ImGuiStorage_SetBool(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, bool val) {
  ImGuiStorage_ctx->SetBool(key, val);
}

FFI_EXPORT float imgui_ImGuiStorage_GetFloat(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, float default_val) {
  return ImGuiStorage_ctx->GetFloat(key, default_val);
}

FFI_EXPORT void imgui_ImGuiStorage_SetFloat(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, float val) {
  ImGuiStorage_ctx->SetFloat(key, val);
}

FFI_EXPORT void * imgui_ImGuiStorage_GetVoidPtr(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key) {
  return ImGuiStorage_ctx->GetVoidPtr(key);
}

FFI_EXPORT void imgui_ImGuiStorage_SetVoidPtr(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, void* val) {
  ImGuiStorage_ctx->SetVoidPtr(key, val);
}

FFI_EXPORT int * imgui_ImGuiStorage_GetIntRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, int default_val) {
  return ImGuiStorage_ctx->GetIntRef(key, default_val);
}

FFI_EXPORT bool * imgui_ImGuiStorage_GetBoolRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, bool default_val) {
  return ImGuiStorage_ctx->GetBoolRef(key, default_val);
}

FFI_EXPORT float * imgui_ImGuiStorage_GetFloatRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, float default_val) {
  return ImGuiStorage_ctx->GetFloatRef(key, default_val);
}

FFI_EXPORT void ** imgui_ImGuiStorage_GetVoidPtrRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, void* default_val) {
  return ImGuiStorage_ctx->GetVoidPtrRef(key, default_val);
}

FFI_EXPORT void imgui_ImGuiStorage_BuildSortByKey(ImGuiStorage* ImGuiStorage_ctx) {
  ImGuiStorage_ctx->BuildSortByKey();
}

FFI_EXPORT void imgui_ImGuiStorage_SetAllInt(ImGuiStorage* ImGuiStorage_ctx, int val) {
  ImGuiStorage_ctx->SetAllInt(val);
}

FFI_EXPORT void imgui_ImGuiListClipper_Begin(ImGuiListClipper* ImGuiListClipper_ctx, int items_count, float items_height) {
  ImGuiListClipper_ctx->Begin(items_count, items_height);
}

FFI_EXPORT void imgui_ImGuiListClipper_End(ImGuiListClipper* ImGuiListClipper_ctx) {
  ImGuiListClipper_ctx->End();
}

FFI_EXPORT bool imgui_ImGuiListClipper_Step(ImGuiListClipper* ImGuiListClipper_ctx) {
  return ImGuiListClipper_ctx->Step();
}

FFI_EXPORT void imgui_ImGuiListClipper_IncludeItemByIndex(ImGuiListClipper* ImGuiListClipper_ctx, int item_index) {
  ImGuiListClipper_ctx->IncludeItemByIndex(item_index);
}

FFI_EXPORT void imgui_ImGuiListClipper_IncludeItemsByIndex(ImGuiListClipper* ImGuiListClipper_ctx, int item_begin, int item_end) {
  ImGuiListClipper_ctx->IncludeItemsByIndex(item_begin, item_end);
}

FFI_EXPORT void imgui_ImGuiListClipper_SeekCursorForItem(ImGuiListClipper* ImGuiListClipper_ctx, int item_index) {
  ImGuiListClipper_ctx->SeekCursorForItem(item_index);
}

FFI_EXPORT void imgui_ImColor_SetHSV(ImColor* ImColor_ctx, float h, float s, float v, float a) {
  ImColor_ctx->SetHSV(h, s, v, a);
}

FFI_EXPORT ImVec4_C imgui_ImColor_HSV(ImColor* ImColor_ctx, float h, float s, float v, float a) {
  const ImVec4& res_cxx = ImColor_ctx->HSV(h, s, v, a);
  ImVec4_C res_c = {res_cxx.x, res_cxx.y, res_cxx.z, res_cxx.w};
  return res_c;
}

FFI_EXPORT void imgui_ImGuiSelectionBasicStorage_ApplyRequests(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiMultiSelectIO* ms_io) {
  ImGuiSelectionBasicStorage_ctx->ApplyRequests(ms_io);
}

FFI_EXPORT bool imgui_ImGuiSelectionBasicStorage_Contains(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiID id) {
  return ImGuiSelectionBasicStorage_ctx->Contains(id);
}

FFI_EXPORT void imgui_ImGuiSelectionBasicStorage_Clear(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx) {
  ImGuiSelectionBasicStorage_ctx->Clear();
}

FFI_EXPORT void imgui_ImGuiSelectionBasicStorage_Swap(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiSelectionBasicStorage* r) {
  ImGuiSelectionBasicStorage_ctx->Swap(*r);
}

FFI_EXPORT void imgui_ImGuiSelectionBasicStorage_SetItemSelected(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiID id, bool selected) {
  ImGuiSelectionBasicStorage_ctx->SetItemSelected(id, selected);
}

FFI_EXPORT bool imgui_ImGuiSelectionBasicStorage_GetNextSelectedItem(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, void** opaque_it, ImGuiID* out_id) {
  return ImGuiSelectionBasicStorage_ctx->GetNextSelectedItem(opaque_it, out_id);
}

FFI_EXPORT ImGuiID imgui_ImGuiSelectionBasicStorage_GetStorageIdFromIndex(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, int idx) {
  return ImGuiSelectionBasicStorage_ctx->GetStorageIdFromIndex(idx);
}

FFI_EXPORT void imgui_ImGuiSelectionExternalStorage_ApplyRequests(ImGuiSelectionExternalStorage* ImGuiSelectionExternalStorage_ctx, ImGuiMultiSelectIO* ms_io) {
  ImGuiSelectionExternalStorage_ctx->ApplyRequests(ms_io);
}

FFI_EXPORT void imgui_ImDrawListSplitter_Clear(ImDrawListSplitter* ImDrawListSplitter_ctx) {
  ImDrawListSplitter_ctx->Clear();
}

FFI_EXPORT void imgui_ImDrawListSplitter_ClearFreeMemory(ImDrawListSplitter* ImDrawListSplitter_ctx) {
  ImDrawListSplitter_ctx->ClearFreeMemory();
}

FFI_EXPORT void imgui_ImDrawListSplitter_Split(ImDrawListSplitter* ImDrawListSplitter_ctx, ImDrawList* draw_list, int count) {
  ImDrawListSplitter_ctx->Split(draw_list, count);
}

FFI_EXPORT void imgui_ImDrawListSplitter_Merge(ImDrawListSplitter* ImDrawListSplitter_ctx, ImDrawList* draw_list) {
  ImDrawListSplitter_ctx->Merge(draw_list);
}

FFI_EXPORT void imgui_ImDrawListSplitter_SetCurrentChannel(ImDrawListSplitter* ImDrawListSplitter_ctx, ImDrawList* draw_list, int channel_idx) {
  ImDrawListSplitter_ctx->SetCurrentChannel(draw_list, channel_idx);
}

FFI_EXPORT void imgui_ImDrawList_PushClipRect(ImDrawList* ImDrawList_ctx, const ImVec2* clip_rect_min, const ImVec2* clip_rect_max, bool intersect_with_current_clip_rect) {
  ImDrawList_ctx->PushClipRect(*clip_rect_min, *clip_rect_max, intersect_with_current_clip_rect);
}

FFI_EXPORT void imgui_ImDrawList_PushClipRectFullScreen(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->PushClipRectFullScreen();
}

FFI_EXPORT void imgui_ImDrawList_PopClipRect(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->PopClipRect();
}

FFI_EXPORT void imgui_ImDrawList_PushTexture(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref) {
  ImDrawList_ctx->PushTexture(ImTextureRef(tex_ref));
}

FFI_EXPORT void imgui_ImDrawList_PopTexture(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->PopTexture();
}

FFI_EXPORT ImVec2_C imgui_ImDrawList_GetClipRectMin(ImDrawList* ImDrawList_ctx) {
  const ImVec2& res_cxx = ImDrawList_ctx->GetClipRectMin();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_ImDrawList_GetClipRectMax(ImDrawList* ImDrawList_ctx) {
  const ImVec2& res_cxx = ImDrawList_ctx->GetClipRectMax();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT void imgui_ImDrawList_AddLine(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, ImU32 col, float thickness) {
  ImDrawList_ctx->AddLine(*p1, *p2, col, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddRect(ImDrawList* ImDrawList_ctx, const ImVec2* p_min, const ImVec2* p_max, ImU32 col, float rounding, ImDrawFlags flags, float thickness) {
  ImDrawList_ctx->AddRect(*p_min, *p_max, col, rounding, flags, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddRectFilled(ImDrawList* ImDrawList_ctx, const ImVec2* p_min, const ImVec2* p_max, ImU32 col, float rounding, ImDrawFlags flags) {
  ImDrawList_ctx->AddRectFilled(*p_min, *p_max, col, rounding, flags);
}

FFI_EXPORT void imgui_ImDrawList_AddRectFilledMultiColor(ImDrawList* ImDrawList_ctx, const ImVec2* p_min, const ImVec2* p_max, ImU32 col_upr_left, ImU32 col_upr_right, ImU32 col_bot_right, ImU32 col_bot_left) {
  ImDrawList_ctx->AddRectFilledMultiColor(*p_min, *p_max, col_upr_left, col_upr_right, col_bot_right, col_bot_left);
}

FFI_EXPORT void imgui_ImDrawList_AddQuad(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, const ImVec2* p4, ImU32 col, float thickness) {
  ImDrawList_ctx->AddQuad(*p1, *p2, *p3, *p4, col, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddQuadFilled(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, const ImVec2* p4, ImU32 col) {
  ImDrawList_ctx->AddQuadFilled(*p1, *p2, *p3, *p4, col);
}

FFI_EXPORT void imgui_ImDrawList_AddTriangle(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, ImU32 col, float thickness) {
  ImDrawList_ctx->AddTriangle(*p1, *p2, *p3, col, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddTriangleFilled(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, ImU32 col) {
  ImDrawList_ctx->AddTriangleFilled(*p1, *p2, *p3, col);
}

FFI_EXPORT void imgui_ImDrawList_AddCircle(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, ImU32 col, int num_segments, float thickness) {
  ImDrawList_ctx->AddCircle(*center, radius, col, num_segments, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddCircleFilled(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, ImU32 col, int num_segments) {
  ImDrawList_ctx->AddCircleFilled(*center, radius, col, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_AddNgon(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, ImU32 col, int num_segments, float thickness) {
  ImDrawList_ctx->AddNgon(*center, radius, col, num_segments, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddNgonFilled(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, ImU32 col, int num_segments) {
  ImDrawList_ctx->AddNgonFilled(*center, radius, col, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_AddEllipse(ImDrawList* ImDrawList_ctx, const ImVec2* center, const ImVec2* radius, ImU32 col, float rot, int num_segments, float thickness) {
  ImDrawList_ctx->AddEllipse(*center, *radius, col, rot, num_segments, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddEllipseFilled(ImDrawList* ImDrawList_ctx, const ImVec2* center, const ImVec2* radius, ImU32 col, float rot, int num_segments) {
  ImDrawList_ctx->AddEllipseFilled(*center, *radius, col, rot, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_AddText1(ImDrawList* ImDrawList_ctx, const ImVec2* pos, ImU32 col, const char* text_begin, const char* text_end) {
  ImDrawList_ctx->AddText(*pos, col, text_begin, text_end);
}

FFI_EXPORT void imgui_ImDrawList_AddText2(ImDrawList* ImDrawList_ctx, ImFont* font, float font_size, const ImVec2* pos, ImU32 col, const char* text_begin, const char* text_end, float wrap_width, const ImVec4* cpu_fine_clip_rect) {
  ImDrawList_ctx->AddText(font, font_size, *pos, col, text_begin, text_end, wrap_width, cpu_fine_clip_rect);
}

FFI_EXPORT void imgui_ImDrawList_AddBezierCubic(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, const ImVec2* p4, ImU32 col, float thickness, int num_segments) {
  ImDrawList_ctx->AddBezierCubic(*p1, *p2, *p3, *p4, col, thickness, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_AddBezierQuadratic(ImDrawList* ImDrawList_ctx, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, ImU32 col, float thickness, int num_segments) {
  ImDrawList_ctx->AddBezierQuadratic(*p1, *p2, *p3, col, thickness, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_AddPolyline(ImDrawList* ImDrawList_ctx, const ImVec2* points, int num_points, ImU32 col, ImDrawFlags flags, float thickness) {
  ImDrawList_ctx->AddPolyline(points, num_points, col, flags, thickness);
}

FFI_EXPORT void imgui_ImDrawList_AddConvexPolyFilled(ImDrawList* ImDrawList_ctx, const ImVec2* points, int num_points, ImU32 col) {
  ImDrawList_ctx->AddConvexPolyFilled(points, num_points, col);
}

FFI_EXPORT void imgui_ImDrawList_AddConcavePolyFilled(ImDrawList* ImDrawList_ctx, const ImVec2* points, int num_points, ImU32 col) {
  ImDrawList_ctx->AddConcavePolyFilled(points, num_points, col);
}

FFI_EXPORT void imgui_ImDrawList_AddImage(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref, const ImVec2* p_min, const ImVec2* p_max, const ImVec2* uv_min, const ImVec2* uv_max, ImU32 col) {
  ImDrawList_ctx->AddImage(ImTextureRef(tex_ref), *p_min, *p_max, *uv_min, *uv_max, col);
}

FFI_EXPORT void imgui_ImDrawList_AddImageQuad(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref, const ImVec2* p1, const ImVec2* p2, const ImVec2* p3, const ImVec2* p4, const ImVec2* uv1, const ImVec2* uv2, const ImVec2* uv3, const ImVec2* uv4, ImU32 col) {
  ImDrawList_ctx->AddImageQuad(ImTextureRef(tex_ref), *p1, *p2, *p3, *p4, *uv1, *uv2, *uv3, *uv4, col);
}

FFI_EXPORT void imgui_ImDrawList_AddImageRounded(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref, const ImVec2* p_min, const ImVec2* p_max, const ImVec2* uv_min, const ImVec2* uv_max, ImU32 col, float rounding, ImDrawFlags flags) {
  ImDrawList_ctx->AddImageRounded(ImTextureRef(tex_ref), *p_min, *p_max, *uv_min, *uv_max, col, rounding, flags);
}

FFI_EXPORT void imgui_ImDrawList_PathClear(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->PathClear();
}

FFI_EXPORT void imgui_ImDrawList_PathLineTo(ImDrawList* ImDrawList_ctx, const ImVec2* pos) {
  ImDrawList_ctx->PathLineTo(*pos);
}

FFI_EXPORT void imgui_ImDrawList_PathLineToMergeDuplicate(ImDrawList* ImDrawList_ctx, const ImVec2* pos) {
  ImDrawList_ctx->PathLineToMergeDuplicate(*pos);
}

FFI_EXPORT void imgui_ImDrawList_PathFillConvex(ImDrawList* ImDrawList_ctx, ImU32 col) {
  ImDrawList_ctx->PathFillConvex(col);
}

FFI_EXPORT void imgui_ImDrawList_PathFillConcave(ImDrawList* ImDrawList_ctx, ImU32 col) {
  ImDrawList_ctx->PathFillConcave(col);
}

FFI_EXPORT void imgui_ImDrawList_PathStroke(ImDrawList* ImDrawList_ctx, ImU32 col, ImDrawFlags flags, float thickness) {
  ImDrawList_ctx->PathStroke(col, flags, thickness);
}

FFI_EXPORT void imgui_ImDrawList_PathArcTo(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, float a_min, float a_max, int num_segments) {
  ImDrawList_ctx->PathArcTo(*center, radius, a_min, a_max, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_PathArcToFast(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, int a_min_of_12, int a_max_of_12) {
  ImDrawList_ctx->PathArcToFast(*center, radius, a_min_of_12, a_max_of_12);
}

FFI_EXPORT void imgui_ImDrawList_PathEllipticalArcTo(ImDrawList* ImDrawList_ctx, const ImVec2* center, const ImVec2* radius, float rot, float a_min, float a_max, int num_segments) {
  ImDrawList_ctx->PathEllipticalArcTo(*center, *radius, rot, a_min, a_max, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_PathBezierCubicCurveTo(ImDrawList* ImDrawList_ctx, const ImVec2* p2, const ImVec2* p3, const ImVec2* p4, int num_segments) {
  ImDrawList_ctx->PathBezierCubicCurveTo(*p2, *p3, *p4, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_PathBezierQuadraticCurveTo(ImDrawList* ImDrawList_ctx, const ImVec2* p2, const ImVec2* p3, int num_segments) {
  ImDrawList_ctx->PathBezierQuadraticCurveTo(*p2, *p3, num_segments);
}

FFI_EXPORT void imgui_ImDrawList_PathRect(ImDrawList* ImDrawList_ctx, const ImVec2* rect_min, const ImVec2* rect_max, float rounding, ImDrawFlags flags) {
  ImDrawList_ctx->PathRect(*rect_min, *rect_max, rounding, flags);
}

FFI_EXPORT void imgui_ImDrawList_AddCallback(ImDrawList* ImDrawList_ctx, ImDrawCallback callback, void* userdata, size_t userdata_size) {
  ImDrawList_ctx->AddCallback(callback, userdata, userdata_size);
}

FFI_EXPORT void imgui_ImDrawList_AddDrawCmd(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->AddDrawCmd();
}

FFI_EXPORT ImDrawList * imgui_ImDrawList_CloneOutput(ImDrawList* ImDrawList_ctx) {
  return ImDrawList_ctx->CloneOutput();
}

FFI_EXPORT void imgui_ImDrawList_ChannelsSplit(ImDrawList* ImDrawList_ctx, int count) {
  ImDrawList_ctx->ChannelsSplit(count);
}

FFI_EXPORT void imgui_ImDrawList_ChannelsMerge(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->ChannelsMerge();
}

FFI_EXPORT void imgui_ImDrawList_ChannelsSetCurrent(ImDrawList* ImDrawList_ctx, int n) {
  ImDrawList_ctx->ChannelsSetCurrent(n);
}

FFI_EXPORT void imgui_ImDrawList_PrimReserve(ImDrawList* ImDrawList_ctx, int idx_count, int vtx_count) {
  ImDrawList_ctx->PrimReserve(idx_count, vtx_count);
}

FFI_EXPORT void imgui_ImDrawList_PrimUnreserve(ImDrawList* ImDrawList_ctx, int idx_count, int vtx_count) {
  ImDrawList_ctx->PrimUnreserve(idx_count, vtx_count);
}

FFI_EXPORT void imgui_ImDrawList_PrimRect(ImDrawList* ImDrawList_ctx, const ImVec2* a, const ImVec2* b, ImU32 col) {
  ImDrawList_ctx->PrimRect(*a, *b, col);
}

FFI_EXPORT void imgui_ImDrawList_PrimRectUV(ImDrawList* ImDrawList_ctx, const ImVec2* a, const ImVec2* b, const ImVec2* uv_a, const ImVec2* uv_b, ImU32 col) {
  ImDrawList_ctx->PrimRectUV(*a, *b, *uv_a, *uv_b, col);
}

FFI_EXPORT void imgui_ImDrawList_PrimQuadUV(ImDrawList* ImDrawList_ctx, const ImVec2* a, const ImVec2* b, const ImVec2* c, const ImVec2* d, const ImVec2* uv_a, const ImVec2* uv_b, const ImVec2* uv_c, const ImVec2* uv_d, ImU32 col) {
  ImDrawList_ctx->PrimQuadUV(*a, *b, *c, *d, *uv_a, *uv_b, *uv_c, *uv_d, col);
}

FFI_EXPORT void imgui_ImDrawList_PrimWriteVtx(ImDrawList* ImDrawList_ctx, const ImVec2* pos, const ImVec2* uv, ImU32 col) {
  ImDrawList_ctx->PrimWriteVtx(*pos, *uv, col);
}

FFI_EXPORT void imgui_ImDrawList_PrimWriteIdx(ImDrawList* ImDrawList_ctx, ImDrawIdx idx) {
  ImDrawList_ctx->PrimWriteIdx(idx);
}

FFI_EXPORT void imgui_ImDrawList_PrimVtx(ImDrawList* ImDrawList_ctx, const ImVec2* pos, const ImVec2* uv, ImU32 col) {
  ImDrawList_ctx->PrimVtx(*pos, *uv, col);
}

FFI_EXPORT void imgui_ImDrawList__SetDrawListSharedData(ImDrawList* ImDrawList_ctx, ImDrawListSharedData* data) {
  ImDrawList_ctx->_SetDrawListSharedData(data);
}

FFI_EXPORT void imgui_ImDrawList__ResetForNewFrame(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_ResetForNewFrame();
}

FFI_EXPORT void imgui_ImDrawList__ClearFreeMemory(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_ClearFreeMemory();
}

FFI_EXPORT void imgui_ImDrawList__PopUnusedDrawCmd(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_PopUnusedDrawCmd();
}

FFI_EXPORT void imgui_ImDrawList__TryMergeDrawCmds(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_TryMergeDrawCmds();
}

FFI_EXPORT void imgui_ImDrawList__OnChangedClipRect(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_OnChangedClipRect();
}

FFI_EXPORT void imgui_ImDrawList__OnChangedTexture(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_OnChangedTexture();
}

FFI_EXPORT void imgui_ImDrawList__OnChangedVtxOffset(ImDrawList* ImDrawList_ctx) {
  ImDrawList_ctx->_OnChangedVtxOffset();
}

FFI_EXPORT void imgui_ImDrawList__SetTexture(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref) {
  ImDrawList_ctx->_SetTexture(ImTextureRef(tex_ref));
}

FFI_EXPORT int imgui_ImDrawList__CalcCircleAutoSegmentCount(ImDrawList* ImDrawList_ctx, float radius) {
  return ImDrawList_ctx->_CalcCircleAutoSegmentCount(radius);
}

FFI_EXPORT void imgui_ImDrawList__PathArcToFastEx(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, int a_min_sample, int a_max_sample, int a_step) {
  ImDrawList_ctx->_PathArcToFastEx(*center, radius, a_min_sample, a_max_sample, a_step);
}

FFI_EXPORT void imgui_ImDrawList__PathArcToN(ImDrawList* ImDrawList_ctx, const ImVec2* center, float radius, float a_min, float a_max, int num_segments) {
  ImDrawList_ctx->_PathArcToN(*center, radius, a_min, a_max, num_segments);
}

FFI_EXPORT void imgui_ImDrawData_Clear(ImDrawData* ImDrawData_ctx) {
  ImDrawData_ctx->Clear();
}

FFI_EXPORT void imgui_ImDrawData_AddDrawList(ImDrawData* ImDrawData_ctx, ImDrawList* draw_list) {
  ImDrawData_ctx->AddDrawList(draw_list);
}

FFI_EXPORT void imgui_ImDrawData_DeIndexAllBuffers(ImDrawData* ImDrawData_ctx) {
  ImDrawData_ctx->DeIndexAllBuffers();
}

FFI_EXPORT void imgui_ImDrawData_ScaleClipRects(ImDrawData* ImDrawData_ctx, const ImVec2* fb_scale) {
  ImDrawData_ctx->ScaleClipRects(*fb_scale);
}

FFI_EXPORT void imgui_ImTextureData_Create(ImTextureData* ImTextureData_ctx, ImTextureFormat format, int w, int h) {
  ImTextureData_ctx->Create(format, w, h);
}

FFI_EXPORT void imgui_ImTextureData_DestroyPixels(ImTextureData* ImTextureData_ctx) {
  ImTextureData_ctx->DestroyPixels();
}

FFI_EXPORT void * imgui_ImTextureData_GetPixels(ImTextureData* ImTextureData_ctx) {
  return ImTextureData_ctx->GetPixels();
}

FFI_EXPORT void * imgui_ImTextureData_GetPixelsAt(ImTextureData* ImTextureData_ctx, int x, int y) {
  return ImTextureData_ctx->GetPixelsAt(x, y);
}

FFI_EXPORT int imgui_ImTextureData_GetSizeInBytes(ImTextureData* ImTextureData_ctx) {
  return ImTextureData_ctx->GetSizeInBytes();
}

FFI_EXPORT int imgui_ImTextureData_GetPitch(ImTextureData* ImTextureData_ctx) {
  return ImTextureData_ctx->GetPitch();
}

FFI_EXPORT ImTextureRef imgui_ImTextureData_GetTexRef(ImTextureData* ImTextureData_ctx) {
  return ImTextureData_ctx->GetTexRef();
}

FFI_EXPORT void imgui_ImTextureData_SetTexID(ImTextureData* ImTextureData_ctx, ImTextureID tex_id) {
  ImTextureData_ctx->SetTexID(tex_id);
}

FFI_EXPORT void imgui_ImTextureData_SetStatus(ImTextureData* ImTextureData_ctx, ImTextureStatus status) {
  ImTextureData_ctx->SetStatus(status);
}

FFI_EXPORT void imgui_ImFontGlyphRangesBuilder_Clear(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx) {
  ImFontGlyphRangesBuilder_ctx->Clear();
}

FFI_EXPORT bool imgui_ImFontGlyphRangesBuilder_GetBit(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, size_t n) {
  return ImFontGlyphRangesBuilder_ctx->GetBit(n);
}

FFI_EXPORT void imgui_ImFontGlyphRangesBuilder_SetBit(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, size_t n) {
  ImFontGlyphRangesBuilder_ctx->SetBit(n);
}

FFI_EXPORT void imgui_ImFontGlyphRangesBuilder_AddChar(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, ImWchar c) {
  ImFontGlyphRangesBuilder_ctx->AddChar(c);
}

FFI_EXPORT void imgui_ImFontGlyphRangesBuilder_AddText(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, const char* text, const char* text_end) {
  ImFontGlyphRangesBuilder_ctx->AddText(text, text_end);
}

FFI_EXPORT void imgui_ImFontGlyphRangesBuilder_AddRanges(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, const ImWchar* ranges) {
  ImFontGlyphRangesBuilder_ctx->AddRanges(ranges);
}

FFI_EXPORT ImFont * imgui_ImFontAtlas_AddFont(ImFontAtlas* ImFontAtlas_ctx, const ImFontConfig* font_cfg) {
  return ImFontAtlas_ctx->AddFont(font_cfg);
}

FFI_EXPORT ImFont * imgui_ImFontAtlas_AddFontDefault(ImFontAtlas* ImFontAtlas_ctx, const ImFontConfig* font_cfg) {
  return ImFontAtlas_ctx->AddFontDefault(font_cfg);
}

FFI_EXPORT ImFont * imgui_ImFontAtlas_AddFontFromFileTTF(ImFontAtlas* ImFontAtlas_ctx, const char* filename, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges) {
  return ImFontAtlas_ctx->AddFontFromFileTTF(filename, size_pixels, font_cfg, glyph_ranges);
}

FFI_EXPORT ImFont * imgui_ImFontAtlas_AddFontFromMemoryTTF(ImFontAtlas* ImFontAtlas_ctx, void* font_data, int font_data_size, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges) {
  return ImFontAtlas_ctx->AddFontFromMemoryTTF(font_data, font_data_size, size_pixels, font_cfg, glyph_ranges);
}

FFI_EXPORT ImFont * imgui_ImFontAtlas_AddFontFromMemoryCompressedTTF(ImFontAtlas* ImFontAtlas_ctx, const void* compressed_font_data, int compressed_font_data_size, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges) {
  return ImFontAtlas_ctx->AddFontFromMemoryCompressedTTF(compressed_font_data, compressed_font_data_size, size_pixels, font_cfg, glyph_ranges);
}

FFI_EXPORT ImFont * imgui_ImFontAtlas_AddFontFromMemoryCompressedBase85TTF(ImFontAtlas* ImFontAtlas_ctx, const char* compressed_font_data_base85, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges) {
  return ImFontAtlas_ctx->AddFontFromMemoryCompressedBase85TTF(compressed_font_data_base85, size_pixels, font_cfg, glyph_ranges);
}

FFI_EXPORT void imgui_ImFontAtlas_RemoveFont(ImFontAtlas* ImFontAtlas_ctx, ImFont* font) {
  ImFontAtlas_ctx->RemoveFont(font);
}

FFI_EXPORT void imgui_ImFontAtlas_Clear(ImFontAtlas* ImFontAtlas_ctx) {
  ImFontAtlas_ctx->Clear();
}

FFI_EXPORT void imgui_ImFontAtlas_CompactCache(ImFontAtlas* ImFontAtlas_ctx) {
  ImFontAtlas_ctx->CompactCache();
}

FFI_EXPORT void imgui_ImFontAtlas_SetFontLoader(ImFontAtlas* ImFontAtlas_ctx, const ImFontLoader* font_loader) {
  ImFontAtlas_ctx->SetFontLoader(font_loader);
}

FFI_EXPORT void imgui_ImFontAtlas_ClearInputData(ImFontAtlas* ImFontAtlas_ctx) {
  ImFontAtlas_ctx->ClearInputData();
}

FFI_EXPORT void imgui_ImFontAtlas_ClearFonts(ImFontAtlas* ImFontAtlas_ctx) {
  ImFontAtlas_ctx->ClearFonts();
}

FFI_EXPORT void imgui_ImFontAtlas_ClearTexData(ImFontAtlas* ImFontAtlas_ctx) {
  ImFontAtlas_ctx->ClearTexData();
}

FFI_EXPORT const ImWchar * imgui_ImFontAtlas_GetGlyphRangesDefault(ImFontAtlas* ImFontAtlas_ctx) {
  return ImFontAtlas_ctx->GetGlyphRangesDefault();
}

FFI_EXPORT ImFontAtlasRectId imgui_ImFontAtlas_AddCustomRect(ImFontAtlas* ImFontAtlas_ctx, int width, int height, ImFontAtlasRect* out_r) {
  return ImFontAtlas_ctx->AddCustomRect(width, height, out_r);
}

FFI_EXPORT void imgui_ImFontAtlas_RemoveCustomRect(ImFontAtlas* ImFontAtlas_ctx, ImFontAtlasRectId id) {
  ImFontAtlas_ctx->RemoveCustomRect(id);
}

FFI_EXPORT bool imgui_ImFontAtlas_GetCustomRect(ImFontAtlas* ImFontAtlas_ctx, ImFontAtlasRectId id, ImFontAtlasRect* out_r) {
  return ImFontAtlas_ctx->GetCustomRect(id, out_r);
}

FFI_EXPORT void imgui_ImFontBaked_ClearOutputData(ImFontBaked* ImFontBaked_ctx) {
  ImFontBaked_ctx->ClearOutputData();
}

FFI_EXPORT ImFontGlyph * imgui_ImFontBaked_FindGlyph(ImFontBaked* ImFontBaked_ctx, ImWchar c) {
  return ImFontBaked_ctx->FindGlyph(c);
}

FFI_EXPORT ImFontGlyph * imgui_ImFontBaked_FindGlyphNoFallback(ImFontBaked* ImFontBaked_ctx, ImWchar c) {
  return ImFontBaked_ctx->FindGlyphNoFallback(c);
}

FFI_EXPORT float imgui_ImFontBaked_GetCharAdvance(ImFontBaked* ImFontBaked_ctx, ImWchar c) {
  return ImFontBaked_ctx->GetCharAdvance(c);
}

FFI_EXPORT bool imgui_ImFontBaked_IsGlyphLoaded(ImFontBaked* ImFontBaked_ctx, ImWchar c) {
  return ImFontBaked_ctx->IsGlyphLoaded(c);
}

FFI_EXPORT bool imgui_ImFont_IsGlyphInFont(ImFont* ImFont_ctx, ImWchar c) {
  return ImFont_ctx->IsGlyphInFont(c);
}

FFI_EXPORT bool imgui_ImFont_IsLoaded(ImFont* ImFont_ctx) {
  return ImFont_ctx->IsLoaded();
}

FFI_EXPORT const char * imgui_ImFont_GetDebugName(ImFont* ImFont_ctx) {
  return ImFont_ctx->GetDebugName();
}

FFI_EXPORT ImFontBaked * imgui_ImFont_GetFontBaked(ImFont* ImFont_ctx, float font_size, float density) {
  return ImFont_ctx->GetFontBaked(font_size, density);
}

FFI_EXPORT ImVec2_C imgui_ImFont_CalcTextSizeA(ImFont* ImFont_ctx, float size, float max_width, float wrap_width, const char* text_begin, const char* text_end, const char** out_remaining) {
  const ImVec2& res_cxx = ImFont_ctx->CalcTextSizeA(size, max_width, wrap_width, text_begin, text_end, out_remaining);
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT const char * imgui_ImFont_CalcWordWrapPosition(ImFont* ImFont_ctx, float size, const char* text, const char* text_end, float wrap_width) {
  return ImFont_ctx->CalcWordWrapPosition(size, text, text_end, wrap_width);
}

FFI_EXPORT void imgui_ImFont_RenderChar(ImFont* ImFont_ctx, ImDrawList* draw_list, float size, const ImVec2* pos, ImU32 col, ImWchar c, const ImVec4* cpu_fine_clip) {
  ImFont_ctx->RenderChar(draw_list, size, *pos, col, c, cpu_fine_clip);
}

FFI_EXPORT void imgui_ImFont_RenderText(ImFont* ImFont_ctx, ImDrawList* draw_list, float size, const ImVec2* pos, ImU32 col, const ImVec4* clip_rect, const char* text_begin, const char* text_end, float wrap_width, ImDrawTextFlags flags) {
  ImFont_ctx->RenderText(draw_list, size, *pos, col, *clip_rect, text_begin, text_end, wrap_width, flags);
}

FFI_EXPORT void imgui_ImFont_ClearOutputData(ImFont* ImFont_ctx) {
  ImFont_ctx->ClearOutputData();
}

FFI_EXPORT void imgui_ImFont_AddRemapChar(ImFont* ImFont_ctx, ImWchar from_codepoint, ImWchar to_codepoint) {
  ImFont_ctx->AddRemapChar(from_codepoint, to_codepoint);
}

FFI_EXPORT bool imgui_ImFont_IsGlyphRangeUnused(ImFont* ImFont_ctx, unsigned int c_begin, unsigned int c_last) {
  return ImFont_ctx->IsGlyphRangeUnused(c_begin, c_last);
}

FFI_EXPORT ImVec2_C imgui_ImGuiViewport_GetCenter(ImGuiViewport* ImGuiViewport_ctx) {
  const ImVec2& res_cxx = ImGuiViewport_ctx->GetCenter();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}

FFI_EXPORT ImVec2_C imgui_ImGuiViewport_GetWorkCenter(ImGuiViewport* ImGuiViewport_ctx) {
  const ImVec2& res_cxx = ImGuiViewport_ctx->GetWorkCenter();
  ImVec2_C res_c = {res_cxx.x, res_cxx.y};
  return res_c;
}



#undef FFI_EXPORT
} // extern C
