
///////////////////////////////////////////////////////////////////////////////
// this file is used for declaring C types for LuaJIT's FFI. Do not use it in C
///////////////////////////////////////////////////////////////////////////////

// !!!! DO NOT EDIT THIS FILE -- It was automatically generated by gen.py -- DO NOT EDIT THIS FILE !!!!

typedef struct ImVector {
    int   Size;
    int   Capacity;
    void* Data;
} ImVector;

typedef struct { float x, y; } ImVec2_C;
typedef struct { float x, y, z, w; } ImVec4_C;

// Typedef for ImTextureID for FFI, as ImGui uses ImU64
typedef unsigned long long ImTextureID;

typedef unsigned int        ImGuiID;
typedef signed char         ImS8;
typedef unsigned char       ImU8;
typedef signed short        ImS16;
typedef unsigned short      ImU16;
typedef signed int          ImS32;
typedef unsigned int        ImU32;
typedef signed   long long  ImS64;
typedef unsigned long long  ImU64;
typedef struct ImDrawCmd ImDrawCmd;
typedef struct ImDrawData ImDrawData;
typedef struct ImDrawList ImDrawList;
typedef struct ImDrawListSharedData ImDrawListSharedData;
typedef struct ImDrawListSplitter ImDrawListSplitter;
typedef struct ImDrawVert ImDrawVert;
typedef struct ImFont ImFont;
typedef struct ImFontAtlas ImFontAtlas;
typedef struct ImFontAtlasBuilder ImFontAtlasBuilder;
typedef struct ImFontAtlasRect ImFontAtlasRect;
typedef struct ImFontBaked ImFontBaked;
typedef struct ImFontConfig ImFontConfig;
typedef struct ImFontGlyph ImFontGlyph;
typedef struct ImFontGlyphRangesBuilder ImFontGlyphRangesBuilder;
typedef struct ImFontLoader ImFontLoader;
typedef struct ImTextureData ImTextureData;
typedef struct ImTextureRect ImTextureRect;
typedef struct ImColor ImColor;
typedef struct ImGuiContext ImGuiContext;
typedef struct ImGuiIO ImGuiIO;
typedef struct ImGuiInputTextCallbackData ImGuiInputTextCallbackData;
typedef struct ImGuiKeyData ImGuiKeyData;
typedef struct ImGuiListClipper ImGuiListClipper;
typedef struct ImGuiMultiSelectIO ImGuiMultiSelectIO;
typedef struct ImGuiPayload ImGuiPayload;
typedef struct ImGuiPlatformIO ImGuiPlatformIO;
typedef struct ImGuiPlatformImeData ImGuiPlatformImeData;
typedef struct ImGuiSelectionBasicStorage ImGuiSelectionBasicStorage;
typedef struct ImGuiSelectionExternalStorage ImGuiSelectionExternalStorage;
typedef struct ImGuiSelectionRequest ImGuiSelectionRequest;
typedef struct ImGuiSizeCallbackData ImGuiSizeCallbackData;
typedef struct ImGuiStorage ImGuiStorage;
typedef struct ImGuiStoragePair ImGuiStoragePair;
typedef struct ImGuiStyle ImGuiStyle;
typedef struct ImGuiTableSortSpecs ImGuiTableSortSpecs;
typedef struct ImGuiTableColumnSortSpecs ImGuiTableColumnSortSpecs;
typedef struct ImGuiTextBuffer ImGuiTextBuffer;
typedef struct ImGuiTextFilter ImGuiTextFilter;
typedef struct ImGuiViewport ImGuiViewport;
typedef int ImGuiDir;
typedef int ImGuiKey;
typedef int ImGuiMouseSource;
typedef unsigned char ImGuiSortDirection;
typedef int ImGuiCol;
typedef int ImGuiCond;
typedef int ImGuiDataType;
typedef int ImGuiMouseButton;
typedef int ImGuiMouseCursor;
typedef int ImGuiStyleVar;
typedef int ImGuiTableBgTarget;
typedef int ImDrawFlags;
typedef int ImDrawListFlags;
typedef int ImDrawTextFlags;
typedef int ImFontFlags;
typedef int ImFontAtlasFlags;
typedef int ImGuiBackendFlags;
typedef int ImGuiButtonFlags;
typedef int ImGuiChildFlags;
typedef int ImGuiColorEditFlags;
typedef int ImGuiConfigFlags;
typedef int ImGuiComboFlags;
typedef int ImGuiDragDropFlags;
typedef int ImGuiFocusedFlags;
typedef int ImGuiHoveredFlags;
typedef int ImGuiInputFlags;
typedef int ImGuiInputTextFlags;
typedef int ImGuiItemFlags;
typedef int ImGuiKeyChord;
typedef int ImGuiListClipperFlags;
typedef int ImGuiPopupFlags;
typedef int ImGuiMultiSelectFlags;
typedef int ImGuiSelectableFlags;
typedef int ImGuiSliderFlags;
typedef int ImGuiTabBarFlags;
typedef int ImGuiTabItemFlags;
typedef int ImGuiTableFlags;
typedef int ImGuiTableColumnFlags;
typedef int ImGuiTableRowFlags;
typedef int ImGuiTreeNodeFlags;
typedef int ImGuiViewportFlags;
typedef int ImGuiWindowFlags;
typedef unsigned int ImWchar32;
typedef unsigned short ImWchar16;
typedef ImWchar16 ImWchar;
typedef ImS64 ImGuiSelectionUserData;
typedef int     (*ImGuiInputTextCallback)(ImGuiInputTextCallbackData* data);
typedef void    (*ImGuiSizeCallback)(ImGuiSizeCallbackData* data);
typedef void*   (*ImGuiMemAllocFunc)(size_t sz, void* user_data);
typedef void    (*ImGuiMemFreeFunc)(void* ptr, void* user_data);
typedef ImU64 ImTextureID;
typedef struct ImTextureRef {
  ImTextureData* _TexData;
  ImTextureID _TexID;
} ImTextureRef;
// void imgui_ImTextureRef();
// void imgui_ImTextureRef(ImTextureID tex_id);
ImGuiContext * imgui_GetCurrentContext();
void imgui_SetCurrentContext(ImGuiContext* ctx);
ImGuiIO & imgui_GetIO();
ImGuiPlatformIO & imgui_GetPlatformIO();
ImGuiStyle & imgui_GetStyle();
void imgui_NewFrame();
void imgui_EndFrame();
void imgui_Render();
ImDrawData * imgui_GetDrawData();
void imgui_ShowDemoWindow(bool* p_open);
void imgui_ShowMetricsWindow(bool* p_open);
void imgui_ShowDebugLogWindow(bool* p_open);
void imgui_ShowIDStackToolWindow(bool* p_open);
void imgui_ShowAboutWindow(bool* p_open);
void imgui_ShowStyleEditor(ImGuiStyle* ref);
bool imgui_ShowStyleSelector(const char* label);
void imgui_ShowFontSelector(const char* label);
void imgui_ShowUserGuide();
const char * imgui_GetVersion();
void imgui_StyleColorsDark(ImGuiStyle* dst);
void imgui_StyleColorsLight(ImGuiStyle* dst);
void imgui_StyleColorsClassic(ImGuiStyle* dst);
bool imgui_Begin(const char* name, bool* p_open, ImGuiWindowFlags flags);
void imgui_End();
bool imgui_BeginChild1(const char* str_id, const ImVec2_C* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags);
bool imgui_BeginChild2(ImGuiID id, const ImVec2_C* size, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags);
void imgui_EndChild();
bool imgui_IsWindowAppearing();
bool imgui_IsWindowCollapsed();
bool imgui_IsWindowFocused(ImGuiFocusedFlags flags);
bool imgui_IsWindowHovered(ImGuiHoveredFlags flags);
ImDrawList * imgui_GetWindowDrawList();
ImVec2_C imgui_GetWindowPos();
ImVec2_C imgui_GetWindowSize();
float imgui_GetWindowWidth();
float imgui_GetWindowHeight();
void imgui_SetNextWindowPos(const ImVec2_C* pos, ImGuiCond cond, const ImVec2_C* pivot);
void imgui_SetNextWindowSize(const ImVec2_C* size, ImGuiCond cond);
void imgui_SetNextWindowSizeConstraints(const ImVec2_C* size_min, const ImVec2_C* size_max, ImGuiSizeCallback custom_callback, void* custom_callback_data);
void imgui_SetNextWindowContentSize(const ImVec2_C* size);
void imgui_SetNextWindowCollapsed(bool collapsed, ImGuiCond cond);
void imgui_SetNextWindowFocus();
void imgui_SetNextWindowScroll(const ImVec2_C* scroll);
void imgui_SetNextWindowBgAlpha(float alpha);
void imgui_SetWindowPos1(const ImVec2_C* pos, ImGuiCond cond);
void imgui_SetWindowSize1(const ImVec2_C* size, ImGuiCond cond);
void imgui_SetWindowCollapsed1(bool collapsed, ImGuiCond cond);
void imgui_SetWindowFocus1();
void imgui_SetWindowPos2(const char* name, const ImVec2_C* pos, ImGuiCond cond);
void imgui_SetWindowSize2(const char* name, const ImVec2_C* size, ImGuiCond cond);
void imgui_SetWindowCollapsed2(const char* name, bool collapsed, ImGuiCond cond);
void imgui_SetWindowFocus2(const char* name);
float imgui_GetScrollX();
float imgui_GetScrollY();
void imgui_SetScrollX(float scroll_x);
void imgui_SetScrollY(float scroll_y);
float imgui_GetScrollMaxX();
float imgui_GetScrollMaxY();
void imgui_SetScrollHereX(float center_x_ratio);
void imgui_SetScrollHereY(float center_y_ratio);
void imgui_SetScrollFromPosX(float local_x, float center_x_ratio);
void imgui_SetScrollFromPosY(float local_y, float center_y_ratio);
void imgui_PushFont(ImFont* font, float font_size_base_unscaled);
void imgui_PopFont();
ImFont * imgui_GetFont();
float imgui_GetFontSize();
ImFontBaked * imgui_GetFontBaked();
void imgui_PushStyleColor1(ImGuiCol idx, ImU32 col);
void imgui_PushStyleColor2(ImGuiCol idx, const ImVec4_C* col);
void imgui_PopStyleColor(int count);
void imgui_PushStyleVar1(ImGuiStyleVar idx, float val);
void imgui_PushStyleVar2(ImGuiStyleVar idx, const ImVec2_C* val);
void imgui_PushStyleVarX(ImGuiStyleVar idx, float val_x);
void imgui_PushStyleVarY(ImGuiStyleVar idx, float val_y);
void imgui_PopStyleVar(int count);
void imgui_PushItemFlag(ImGuiItemFlags option, bool enabled);
void imgui_PopItemFlag();
void imgui_PushItemWidth(float item_width);
void imgui_PopItemWidth();
void imgui_SetNextItemWidth(float item_width);
float imgui_CalcItemWidth();
void imgui_PushTextWrapPos(float wrap_local_pos_x);
void imgui_PopTextWrapPos();
ImVec2_C imgui_GetFontTexUvWhitePixel();
ImU32 imgui_GetColorU321(ImGuiCol idx, float alpha_mul);
ImU32 imgui_GetColorU322(const ImVec4_C* col);
ImU32 imgui_GetColorU323(ImU32 col, float alpha_mul);
const ImVec4_C & imgui_GetStyleColorVec4(ImGuiCol idx);
ImVec2_C imgui_GetCursorScreenPos();
void imgui_SetCursorScreenPos(const ImVec2_C* pos);
ImVec2_C imgui_GetContentRegionAvail();
ImVec2_C imgui_GetCursorPos();
float imgui_GetCursorPosX();
float imgui_GetCursorPosY();
void imgui_SetCursorPos(const ImVec2_C* local_pos);
void imgui_SetCursorPosX(float local_x);
void imgui_SetCursorPosY(float local_y);
ImVec2_C imgui_GetCursorStartPos();
void imgui_Separator();
void imgui_SameLine(float offset_from_start_x, float spacing);
void imgui_NewLine();
void imgui_Spacing();
void imgui_Dummy(const ImVec2_C* size);
void imgui_Indent(float indent_w);
void imgui_Unindent(float indent_w);
void imgui_BeginGroup();
void imgui_EndGroup();
void imgui_AlignTextToFramePadding();
float imgui_GetTextLineHeight();
float imgui_GetTextLineHeightWithSpacing();
float imgui_GetFrameHeight();
float imgui_GetFrameHeightWithSpacing();
void imgui_PushID1(const char* str_id);
void imgui_PushID2(const char* str_id_begin, const char* str_id_end);
void imgui_PushID3(const void* ptr_id);
void imgui_PushID4(int int_id);
void imgui_PopID();
ImGuiID imgui_GetID1(const char* str_id);
ImGuiID imgui_GetID2(const char* str_id_begin, const char* str_id_end);
ImGuiID imgui_GetID3(const void* ptr_id);
ImGuiID imgui_GetID4(int int_id);
void imgui_TextUnformatted(const char* text, const char* text_end);
void imgui_Text(const char* fmt, ...);
void imgui_TextV(const char* fmt, va_list args);
void imgui_TextColored(const ImVec4_C* col, const char* fmt, ...);
void imgui_TextColoredV(const ImVec4_C* col, const char* fmt, va_list args);
void imgui_TextDisabled(const char* fmt, ...);
void imgui_TextDisabledV(const char* fmt, va_list args);
void imgui_TextWrapped(const char* fmt, ...);
void imgui_TextWrappedV(const char* fmt, va_list args);
void imgui_LabelText(const char* label, const char* fmt, ...);
void imgui_LabelTextV(const char* label, const char* fmt, va_list args);
void imgui_BulletText(const char* fmt, ...);
void imgui_BulletTextV(const char* fmt, va_list args);
void imgui_SeparatorText(const char* label);
bool imgui_Button(const char* label, const ImVec2_C* size);
bool imgui_SmallButton(const char* label);
bool imgui_InvisibleButton(const char* str_id, const ImVec2_C* size, ImGuiButtonFlags flags);
bool imgui_ArrowButton(const char* str_id, ImGuiDir dir);
bool imgui_Checkbox(const char* label, bool* v);
bool imgui_CheckboxFlags1(const char* label, int* flags, int flags_value);
bool imgui_CheckboxFlags2(const char* label, unsigned int* flags, unsigned int flags_value);
bool imgui_RadioButton1(const char* label, bool active);
bool imgui_RadioButton2(const char* label, int* v, int v_button);
void imgui_ProgressBar(float fraction, const ImVec2_C* size_arg, const char* overlay);
void imgui_Bullet();
bool imgui_TextLink(const char* label);
bool imgui_TextLinkOpenURL(const char* label, const char* url);
void imgui_Image(ImTextureID tex_ref, const ImVec2_C* image_size, const ImVec2_C* uv0, const ImVec2_C* uv1);
void imgui_ImageWithBg(ImTextureID tex_ref, const ImVec2_C* image_size, const ImVec2_C* uv0, const ImVec2_C* uv1, const ImVec4_C* bg_col, const ImVec4_C* tint_col);
bool imgui_ImageButton(const char* str_id, ImTextureID tex_ref, const ImVec2_C* image_size, const ImVec2_C* uv0, const ImVec2_C* uv1, const ImVec4_C* bg_col, const ImVec4_C* tint_col);
bool imgui_BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags);
void imgui_EndCombo();
bool imgui_Combo1(const char* label, int* current_item, const char*const items[], int items_count, int popup_max_height_in_items);
bool imgui_Combo2(const char* label, int* current_item, const char* items_separated_by_zeros, int popup_max_height_in_items);
bool imgui_Combo3(const char* label, int* current_item, const char*(*getter)(void*, int), void* user_data, int items_count, int popup_max_height_in_items);
bool imgui_DragFloat(const char* label, float* v, float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragFloat2(const char* label, float v[2], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragFloat3(const char* label, float v[3], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragFloat4(const char* label, float v[4], float v_speed, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragFloatRange2(const char* label, float* v_current_min, float* v_current_max, float v_speed, float v_min, float v_max, const char* format, const char* format_max, ImGuiSliderFlags flags);
bool imgui_DragInt(const char* label, int* v, float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragInt2(const char* label, int v[2], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragInt3(const char* label, int v[3], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragInt4(const char* label, int v[4], float v_speed, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragIntRange2(const char* label, int* v_current_min, int* v_current_max, float v_speed, int v_min, int v_max, const char* format, const char* format_max, ImGuiSliderFlags flags);
bool imgui_DragScalar(const char* label, ImGuiDataType data_type, void* p_data, float v_speed, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags);
bool imgui_DragScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, float v_speed, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderFloat2(const char* label, float v[2], float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderFloat3(const char* label, float v[3], float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderFloat4(const char* label, float v[4], float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderAngle(const char* label, float* v_rad, float v_degrees_min, float v_degrees_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderInt(const char* label, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderInt2(const char* label, int v[2], int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderInt3(const char* label, int v[3], int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderInt4(const char* label, int v[4], int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags);
bool imgui_SliderScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags);
bool imgui_VSliderFloat(const char* label, const ImVec2_C* size, float* v, float v_min, float v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_VSliderInt(const char* label, const ImVec2_C* size, int* v, int v_min, int v_max, const char* format, ImGuiSliderFlags flags);
bool imgui_VSliderScalar(const char* label, const ImVec2_C* size, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format, ImGuiSliderFlags flags);
bool imgui_InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data);
bool imgui_InputTextMultiline(const char* label, char* buf, size_t buf_size, const ImVec2_C* size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data);
bool imgui_InputTextWithHint(const char* label, const char* hint, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data);
bool imgui_InputFloat(const char* label, float* v, float step, float step_fast, const char* format, ImGuiInputTextFlags flags);
bool imgui_InputFloat2(const char* label, float v[2], const char* format, ImGuiInputTextFlags flags);
bool imgui_InputFloat3(const char* label, float v[3], const char* format, ImGuiInputTextFlags flags);
bool imgui_InputFloat4(const char* label, float v[4], const char* format, ImGuiInputTextFlags flags);
bool imgui_InputInt(const char* label, int* v, int step, int step_fast, ImGuiInputTextFlags flags);
bool imgui_InputInt2(const char* label, int v[2], ImGuiInputTextFlags flags);
bool imgui_InputInt3(const char* label, int v[3], ImGuiInputTextFlags flags);
bool imgui_InputInt4(const char* label, int v[4], ImGuiInputTextFlags flags);
bool imgui_InputDouble(const char* label, double* v, double step, double step_fast, const char* format, ImGuiInputTextFlags flags);
bool imgui_InputScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_step, const void* p_step_fast, const char* format, ImGuiInputTextFlags flags);
bool imgui_InputScalarN(const char* label, ImGuiDataType data_type, void* p_data, int components, const void* p_step, const void* p_step_fast, const char* format, ImGuiInputTextFlags flags);
bool imgui_ColorEdit3(const char* label, float col[3], ImGuiColorEditFlags flags);
bool imgui_ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags);
bool imgui_ColorPicker3(const char* label, float col[3], ImGuiColorEditFlags flags);
bool imgui_ColorPicker4(const char* label, float col[4], ImGuiColorEditFlags flags, const float* ref_col);
bool imgui_ColorButton(const char* desc_id, const ImVec4_C* col, ImGuiColorEditFlags flags, const ImVec2_C* size);
void imgui_SetColorEditOptions(ImGuiColorEditFlags flags);
bool imgui_TreeNode1(const char* label);
bool imgui_TreeNode2(const char* str_id, const char* fmt, ...);
bool imgui_TreeNode3(const void* ptr_id, const char* fmt, ...);
bool imgui_TreeNodeV1(const char* str_id, const char* fmt, va_list args);
bool imgui_TreeNodeV2(const void* ptr_id, const char* fmt, va_list args);
bool imgui_TreeNodeEx1(const char* label, ImGuiTreeNodeFlags flags);
bool imgui_TreeNodeEx2(const char* str_id, ImGuiTreeNodeFlags flags, const char* fmt, ...);
bool imgui_TreeNodeEx3(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* fmt, ...);
bool imgui_TreeNodeExV1(const char* str_id, ImGuiTreeNodeFlags flags, const char* fmt, va_list args);
bool imgui_TreeNodeExV2(const void* ptr_id, ImGuiTreeNodeFlags flags, const char* fmt, va_list args);
void imgui_TreePush1(const char* str_id);
void imgui_TreePush2(const void* ptr_id);
void imgui_TreePop();
float imgui_GetTreeNodeToLabelSpacing();
bool imgui_CollapsingHeader1(const char* label, ImGuiTreeNodeFlags flags);
bool imgui_CollapsingHeader2(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags);
void imgui_SetNextItemOpen(bool is_open, ImGuiCond cond);
void imgui_SetNextItemStorageID(ImGuiID storage_id);
bool imgui_Selectable1(const char* label, bool selected, ImGuiSelectableFlags flags, const ImVec2_C* size);
bool imgui_Selectable2(const char* label, bool* p_selected, ImGuiSelectableFlags flags, const ImVec2_C* size);
ImGuiMultiSelectIO * imgui_BeginMultiSelect(ImGuiMultiSelectFlags flags, int selection_size, int items_count);
ImGuiMultiSelectIO * imgui_EndMultiSelect();
void imgui_SetNextItemSelectionUserData(ImGuiSelectionUserData selection_user_data);
bool imgui_IsItemToggledSelection();
bool imgui_BeginListBox(const char* label, const ImVec2_C* size);
void imgui_EndListBox();
bool imgui_ListBox1(const char* label, int* current_item, const char*const items[], int items_count, int height_in_items);
bool imgui_ListBox2(const char* label, int* current_item, const char*(*getter)(void*, int), void* user_data, int items_count, int height_in_items);
void imgui_PlotLines1(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2_C graph_size, int stride);
void imgui_PlotLines2(const char* label, float (*values_getter)(void*, int), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2_C graph_size);
void imgui_PlotHistogram1(const char* label, const float* values, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2_C graph_size, int stride);
void imgui_PlotHistogram2(const char* label, float (*values_getter)(void*, int), void* data, int values_count, int values_offset, const char* overlay_text, float scale_min, float scale_max, ImVec2_C graph_size);
void imgui_Value1(const char* prefix, bool b);
void imgui_Value2(const char* prefix, int v);
void imgui_Value3(const char* prefix, unsigned int v);
void imgui_Value4(const char* prefix, float v, const char* float_format);
bool imgui_BeginMenuBar();
void imgui_EndMenuBar();
bool imgui_BeginMainMenuBar();
void imgui_EndMainMenuBar();
bool imgui_BeginMenu(const char* label, bool enabled);
void imgui_EndMenu();
bool imgui_MenuItem1(const char* label, const char* shortcut, bool selected, bool enabled);
bool imgui_MenuItem2(const char* label, const char* shortcut, bool* p_selected, bool enabled);
bool imgui_BeginTooltip();
void imgui_EndTooltip();
void imgui_SetTooltip(const char* fmt, ...);
void imgui_SetTooltipV(const char* fmt, va_list args);
bool imgui_BeginItemTooltip();
void imgui_SetItemTooltip(const char* fmt, ...);
void imgui_SetItemTooltipV(const char* fmt, va_list args);
bool imgui_BeginPopup(const char* str_id, ImGuiWindowFlags flags);
bool imgui_BeginPopupModal(const char* name, bool* p_open, ImGuiWindowFlags flags);
void imgui_EndPopup();
void imgui_OpenPopup1(const char* str_id, ImGuiPopupFlags popup_flags);
void imgui_OpenPopup2(ImGuiID id, ImGuiPopupFlags popup_flags);
void imgui_OpenPopupOnItemClick(const char* str_id, ImGuiPopupFlags popup_flags);
void imgui_CloseCurrentPopup();
bool imgui_BeginPopupContextItem(const char* str_id, ImGuiPopupFlags popup_flags);
bool imgui_BeginPopupContextWindow(const char* str_id, ImGuiPopupFlags popup_flags);
bool imgui_BeginPopupContextVoid(const char* str_id, ImGuiPopupFlags popup_flags);
bool imgui_IsPopupOpen(const char* str_id, ImGuiPopupFlags flags);
bool imgui_BeginTable(const char* str_id, int columns, ImGuiTableFlags flags, const ImVec2_C* outer_size, float inner_width);
void imgui_EndTable();
void imgui_TableNextRow(ImGuiTableRowFlags row_flags, float min_row_height);
bool imgui_TableNextColumn();
bool imgui_TableSetColumnIndex(int column_n);
void imgui_TableSetupColumn(const char* label, ImGuiTableColumnFlags flags, float init_width_or_weight, ImGuiID user_id);
void imgui_TableSetupScrollFreeze(int cols, int rows);
void imgui_TableHeader(const char* label);
void imgui_TableHeadersRow();
void imgui_TableAngledHeadersRow();
ImGuiTableSortSpecs * imgui_TableGetSortSpecs();
int imgui_TableGetColumnCount();
int imgui_TableGetColumnIndex();
int imgui_TableGetRowIndex();
const char * imgui_TableGetColumnName(int column_n);
ImGuiTableColumnFlags imgui_TableGetColumnFlags(int column_n);
void imgui_TableSetColumnEnabled(int column_n, bool v);
int imgui_TableGetHoveredColumn();
void imgui_TableSetBgColor(ImGuiTableBgTarget target, ImU32 color, int column_n);
void imgui_Columns(int count, const char* id, bool borders);
void imgui_NextColumn();
int imgui_GetColumnIndex();
float imgui_GetColumnWidth(int column_index);
void imgui_SetColumnWidth(int column_index, float width);
float imgui_GetColumnOffset(int column_index);
void imgui_SetColumnOffset(int column_index, float offset_x);
int imgui_GetColumnsCount();
bool imgui_BeginTabBar(const char* str_id, ImGuiTabBarFlags flags);
void imgui_EndTabBar();
bool imgui_BeginTabItem(const char* label, bool* p_open, ImGuiTabItemFlags flags);
void imgui_EndTabItem();
bool imgui_TabItemButton(const char* label, ImGuiTabItemFlags flags);
void imgui_SetTabItemClosed(const char* tab_or_docked_window_label);
void imgui_LogToTTY(int auto_open_depth);
void imgui_LogToFile(int auto_open_depth, const char* filename);
void imgui_LogToClipboard(int auto_open_depth);
void imgui_LogFinish();
void imgui_LogButtons();
void imgui_LogText(const char* fmt, ...);
void imgui_LogTextV(const char* fmt, va_list args);
bool imgui_BeginDragDropSource(ImGuiDragDropFlags flags);
bool imgui_SetDragDropPayload(const char* type, const void* data, size_t sz, ImGuiCond cond);
void imgui_EndDragDropSource();
bool imgui_BeginDragDropTarget();
const ImGuiPayload * imgui_AcceptDragDropPayload(const char* type, ImGuiDragDropFlags flags);
void imgui_EndDragDropTarget();
const ImGuiPayload * imgui_GetDragDropPayload();
void imgui_BeginDisabled(bool disabled);
void imgui_EndDisabled();
void imgui_PushClipRect(const ImVec2_C* clip_rect_min, const ImVec2_C* clip_rect_max, bool intersect_with_current_clip_rect);
void imgui_PopClipRect();
void imgui_SetItemDefaultFocus();
void imgui_SetKeyboardFocusHere(int offset);
void imgui_SetNavCursorVisible(bool visible);
void imgui_SetNextItemAllowOverlap();
bool imgui_IsItemHovered(ImGuiHoveredFlags flags);
bool imgui_IsItemActive();
bool imgui_IsItemFocused();
bool imgui_IsItemClicked(ImGuiMouseButton mouse_button);
bool imgui_IsItemVisible();
bool imgui_IsItemEdited();
bool imgui_IsItemActivated();
bool imgui_IsItemDeactivated();
bool imgui_IsItemDeactivatedAfterEdit();
bool imgui_IsItemToggledOpen();
bool imgui_IsAnyItemHovered();
bool imgui_IsAnyItemActive();
bool imgui_IsAnyItemFocused();
ImGuiID imgui_GetItemID();
ImVec2_C imgui_GetItemRectMin();
ImVec2_C imgui_GetItemRectMax();
ImVec2_C imgui_GetItemRectSize();
ImGuiViewport * imgui_GetMainViewport();
ImDrawList * imgui_GetBackgroundDrawList();
ImDrawList * imgui_GetForegroundDrawList();
bool imgui_IsRectVisible1(const ImVec2_C* size);
bool imgui_IsRectVisible2(const ImVec2_C* rect_min, const ImVec2_C* rect_max);
double imgui_GetTime();
int imgui_GetFrameCount();
ImDrawListSharedData * imgui_GetDrawListSharedData();
const char * imgui_GetStyleColorName(ImGuiCol idx);
void imgui_SetStateStorage(ImGuiStorage* storage);
ImGuiStorage * imgui_GetStateStorage();
ImVec2_C imgui_CalcTextSize(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width);
ImVec4_C imgui_ColorConvertU32ToFloat4(ImU32 _in);
ImU32 imgui_ColorConvertFloat4ToU32(const ImVec4_C* _in);
void imgui_ColorConvertRGBtoHSV(float r, float g, float b, float* out_h, float* out_s, float* out_v);
void imgui_ColorConvertHSVtoRGB(float h, float s, float v, float* out_r, float* out_g, float* out_b);
bool imgui_IsKeyDown(ImGuiKey key);
bool imgui_IsKeyPressed(ImGuiKey key, bool _repeat);
bool imgui_IsKeyReleased(ImGuiKey key);
bool imgui_IsKeyChordPressed(ImGuiKeyChord key_chord);
int imgui_GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate);
const char * imgui_GetKeyName(ImGuiKey key);
void imgui_SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard);
bool imgui_Shortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags);
void imgui_SetNextItemShortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags);
void imgui_SetItemKeyOwner(ImGuiKey key);
bool imgui_IsMouseDown(ImGuiMouseButton button);
bool imgui_IsMouseClicked(ImGuiMouseButton button, bool _repeat);
bool imgui_IsMouseReleased(ImGuiMouseButton button);
bool imgui_IsMouseDoubleClicked(ImGuiMouseButton button);
bool imgui_IsMouseReleasedWithDelay(ImGuiMouseButton button, float delay);
int imgui_GetMouseClickedCount(ImGuiMouseButton button);
bool imgui_IsMouseHoveringRect(const ImVec2_C* r_min, const ImVec2_C* r_max, bool clip);
bool imgui_IsMousePosValid(const ImVec2_C* mouse_pos);
bool imgui_IsAnyMouseDown();
ImVec2_C imgui_GetMousePos();
ImVec2_C imgui_GetMousePosOnOpeningCurrentPopup();
bool imgui_IsMouseDragging(ImGuiMouseButton button, float lock_threshold);
ImVec2_C imgui_GetMouseDragDelta(ImGuiMouseButton button, float lock_threshold);
void imgui_ResetMouseDragDelta(ImGuiMouseButton button);
ImGuiMouseCursor imgui_GetMouseCursor();
void imgui_SetMouseCursor(ImGuiMouseCursor cursor_type);
void imgui_SetNextFrameWantCaptureMouse(bool want_capture_mouse);
const char * imgui_GetClipboardText();
void imgui_SetClipboardText(const char* text);
void imgui_DebugTextEncoding(const char* text);
void imgui_DebugFlashStyleColor(ImGuiCol idx);
void imgui_DebugStartItemPicker();
bool imgui_DebugCheckVersionAndDataLayout(const char* version_str, size_t sz_io, size_t sz_style, size_t sz_vec2, size_t sz_vec4, size_t sz_drawvert, size_t sz_drawidx);
void imgui_DebugLog(const char* fmt, ...);
void imgui_DebugLogV(const char* fmt, va_list args);
void imgui_GetAllocatorFunctions(ImGuiMemAllocFunc* p_alloc_func, ImGuiMemFreeFunc* p_free_func, void** p_user_data);

typedef enum {
  ImGuiWindowFlags_None,
  ImGuiWindowFlags_NoTitleBar = 1 << 0,
  ImGuiWindowFlags_NoResize = 1 << 1,
  ImGuiWindowFlags_NoMove = 1 << 2,
  ImGuiWindowFlags_NoScrollbar = 1 << 3,
  ImGuiWindowFlags_NoScrollWithMouse = 1 << 4,
  ImGuiWindowFlags_NoCollapse = 1 << 5,
  ImGuiWindowFlags_AlwaysAutoResize = 1 << 6,
  ImGuiWindowFlags_NoBackground = 1 << 7,
  ImGuiWindowFlags_NoSavedSettings = 1 << 8,
  ImGuiWindowFlags_NoMouseInputs = 1 << 9,
  ImGuiWindowFlags_MenuBar = 1 << 10,
  ImGuiWindowFlags_HorizontalScrollbar = 1 << 11,
  ImGuiWindowFlags_NoFocusOnAppearing = 1 << 12,
  ImGuiWindowFlags_NoBringToFrontOnFocus = 1 << 13,
  ImGuiWindowFlags_AlwaysVerticalScrollbar = 1 << 14,
  ImGuiWindowFlags_AlwaysHorizontalScrollbar = 1<< 15,
  ImGuiWindowFlags_NoNavInputs = 1 << 16,
  ImGuiWindowFlags_NoNavFocus = 1 << 17,
  ImGuiWindowFlags_UnsavedDocument = 1 << 18,
  ImGuiWindowFlags_NoNav = ImGuiWindowFlags_NoNavInputs | ImGuiWindowFlags_NoNavFocus,
  ImGuiWindowFlags_NoDecoration = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse,
  ImGuiWindowFlags_NoInputs = ImGuiWindowFlags_NoMouseInputs | ImGuiWindowFlags_NoNavInputs | ImGuiWindowFlags_NoNavFocus,
  ImGuiWindowFlags_ChildWindow = 1 << 24,
  ImGuiWindowFlags_Tooltip = 1 << 25,
  ImGuiWindowFlags_Popup = 1 << 26,
  ImGuiWindowFlags_Modal = 1 << 27,
  ImGuiWindowFlags_ChildMenu = 1 << 28
} ImGuiWindowFlags_;

typedef enum {
  ImGuiChildFlags_None,
  ImGuiChildFlags_Borders = 1 << 0,
  ImGuiChildFlags_AlwaysUseWindowPadding = 1 << 1,
  ImGuiChildFlags_ResizeX = 1 << 2,
  ImGuiChildFlags_ResizeY = 1 << 3,
  ImGuiChildFlags_AutoResizeX = 1 << 4,
  ImGuiChildFlags_AutoResizeY = 1 << 5,
  ImGuiChildFlags_AlwaysAutoResize = 1 << 6,
  ImGuiChildFlags_FrameStyle = 1 << 7,
  ImGuiChildFlags_NavFlattened = 1 << 8
} ImGuiChildFlags_;

typedef enum {
  ImGuiItemFlags_None,
  ImGuiItemFlags_NoTabStop = 1 << 0,
  ImGuiItemFlags_NoNav = 1 << 1,
  ImGuiItemFlags_NoNavDefaultFocus = 1 << 2,
  ImGuiItemFlags_ButtonRepeat = 1 << 3,
  ImGuiItemFlags_AutoClosePopups = 1 << 4,
  ImGuiItemFlags_AllowDuplicateId = 1 << 5
} ImGuiItemFlags_;

typedef enum {
  ImGuiInputTextFlags_None,
  ImGuiInputTextFlags_CharsDecimal = 1 << 0,
  ImGuiInputTextFlags_CharsHexadecimal = 1 << 1,
  ImGuiInputTextFlags_CharsScientific = 1 << 2,
  ImGuiInputTextFlags_CharsUppercase = 1 << 3,
  ImGuiInputTextFlags_CharsNoBlank = 1 << 4,
  ImGuiInputTextFlags_AllowTabInput = 1 << 5,
  ImGuiInputTextFlags_EnterReturnsTrue = 1 << 6,
  ImGuiInputTextFlags_EscapeClearsAll = 1 << 7,
  ImGuiInputTextFlags_CtrlEnterForNewLine = 1 << 8,
  ImGuiInputTextFlags_ReadOnly = 1 << 9,
  ImGuiInputTextFlags_Password = 1 << 10,
  ImGuiInputTextFlags_AlwaysOverwrite = 1 << 11,
  ImGuiInputTextFlags_AutoSelectAll = 1 << 12,
  ImGuiInputTextFlags_ParseEmptyRefVal = 1 << 13,
  ImGuiInputTextFlags_DisplayEmptyRefVal = 1 << 14,
  ImGuiInputTextFlags_NoHorizontalScroll = 1 << 15,
  ImGuiInputTextFlags_NoUndoRedo = 1 << 16,
  ImGuiInputTextFlags_ElideLeft = 1 << 17,
  ImGuiInputTextFlags_CallbackCompletion = 1 << 18,
  ImGuiInputTextFlags_CallbackHistory = 1 << 19,
  ImGuiInputTextFlags_CallbackAlways = 1 << 20,
  ImGuiInputTextFlags_CallbackCharFilter = 1 << 21,
  ImGuiInputTextFlags_CallbackResize = 1 << 22,
  ImGuiInputTextFlags_CallbackEdit = 1 << 23,
  ImGuiInputTextFlags_WordWrap = 1 << 24
} ImGuiInputTextFlags_;

typedef enum {
  ImGuiTreeNodeFlags_None,
  ImGuiTreeNodeFlags_Selected = 1 << 0,
  ImGuiTreeNodeFlags_Framed = 1 << 1,
  ImGuiTreeNodeFlags_AllowOverlap = 1 << 2,
  ImGuiTreeNodeFlags_NoTreePushOnOpen = 1 << 3,
  ImGuiTreeNodeFlags_NoAutoOpenOnLog = 1 << 4,
  ImGuiTreeNodeFlags_DefaultOpen = 1 << 5,
  ImGuiTreeNodeFlags_OpenOnDoubleClick = 1 << 6,
  ImGuiTreeNodeFlags_OpenOnArrow = 1 << 7,
  ImGuiTreeNodeFlags_Leaf = 1 << 8,
  ImGuiTreeNodeFlags_Bullet = 1 << 9,
  ImGuiTreeNodeFlags_FramePadding = 1 << 10,
  ImGuiTreeNodeFlags_SpanAvailWidth = 1 << 11,
  ImGuiTreeNodeFlags_SpanFullWidth = 1 << 12,
  ImGuiTreeNodeFlags_SpanLabelWidth = 1 << 13,
  ImGuiTreeNodeFlags_SpanAllColumns = 1 << 14,
  ImGuiTreeNodeFlags_LabelSpanAllColumns = 1 << 15,
  ImGuiTreeNodeFlags_NavLeftJumpsToParent = 1 << 17,
  ImGuiTreeNodeFlags_CollapsingHeader = ImGuiTreeNodeFlags_Framed | ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_NoAutoOpenOnLog,
  ImGuiTreeNodeFlags_DrawLinesNone = 1 << 18,
  ImGuiTreeNodeFlags_DrawLinesFull = 1 << 19,
  ImGuiTreeNodeFlags_DrawLinesToNodes = 1 << 20
} ImGuiTreeNodeFlags_;

typedef enum {
  ImGuiPopupFlags_None,
  ImGuiPopupFlags_MouseButtonLeft,
  ImGuiPopupFlags_MouseButtonRight,
  ImGuiPopupFlags_MouseButtonMiddle,
  ImGuiPopupFlags_MouseButtonMask_,
  ImGuiPopupFlags_MouseButtonDefault_,
  ImGuiPopupFlags_NoReopen = 1 << 5,
  ImGuiPopupFlags_NoOpenOverExistingPopup = 1 << 7,
  ImGuiPopupFlags_NoOpenOverItems = 1 << 8,
  ImGuiPopupFlags_AnyPopupId = 1 << 10,
  ImGuiPopupFlags_AnyPopupLevel = 1 << 11,
  ImGuiPopupFlags_AnyPopup = ImGuiPopupFlags_AnyPopupId | ImGuiPopupFlags_AnyPopupLevel
} ImGuiPopupFlags_;

typedef enum {
  ImGuiSelectableFlags_None,
  ImGuiSelectableFlags_NoAutoClosePopups = 1 << 0,
  ImGuiSelectableFlags_SpanAllColumns = 1 << 1,
  ImGuiSelectableFlags_AllowDoubleClick = 1 << 2,
  ImGuiSelectableFlags_Disabled = 1 << 3,
  ImGuiSelectableFlags_AllowOverlap = 1 << 4,
  ImGuiSelectableFlags_Highlight = 1 << 5,
  ImGuiSelectableFlags_SelectOnNav = 1 << 6
} ImGuiSelectableFlags_;

typedef enum {
  ImGuiComboFlags_None,
  ImGuiComboFlags_PopupAlignLeft = 1 << 0,
  ImGuiComboFlags_HeightSmall = 1 << 1,
  ImGuiComboFlags_HeightRegular = 1 << 2,
  ImGuiComboFlags_HeightLarge = 1 << 3,
  ImGuiComboFlags_HeightLargest = 1 << 4,
  ImGuiComboFlags_NoArrowButton = 1 << 5,
  ImGuiComboFlags_NoPreview = 1 << 6,
  ImGuiComboFlags_WidthFitPreview = 1 << 7,
  ImGuiComboFlags_HeightMask_ = ImGuiComboFlags_HeightSmall | ImGuiComboFlags_HeightRegular | ImGuiComboFlags_HeightLarge | ImGuiComboFlags_HeightLargest
} ImGuiComboFlags_;

typedef enum {
  ImGuiTabBarFlags_None,
  ImGuiTabBarFlags_Reorderable = 1 << 0,
  ImGuiTabBarFlags_AutoSelectNewTabs = 1 << 1,
  ImGuiTabBarFlags_TabListPopupButton = 1 << 2,
  ImGuiTabBarFlags_NoCloseWithMiddleMouseButton = 1 << 3,
  ImGuiTabBarFlags_NoTabListScrollingButtons = 1 << 4,
  ImGuiTabBarFlags_NoTooltip = 1 << 5,
  ImGuiTabBarFlags_DrawSelectedOverline = 1 << 6,
  ImGuiTabBarFlags_FittingPolicyMixed = 1 << 7,
  ImGuiTabBarFlags_FittingPolicyShrink = 1 << 8,
  ImGuiTabBarFlags_FittingPolicyScroll = 1 << 9,
  ImGuiTabBarFlags_FittingPolicyMask_ = ImGuiTabBarFlags_FittingPolicyMixed | ImGuiTabBarFlags_FittingPolicyShrink | ImGuiTabBarFlags_FittingPolicyScroll,
  ImGuiTabBarFlags_FittingPolicyDefault_
} ImGuiTabBarFlags_;

typedef enum {
  ImGuiTabItemFlags_None,
  ImGuiTabItemFlags_UnsavedDocument = 1 << 0,
  ImGuiTabItemFlags_SetSelected = 1 << 1,
  ImGuiTabItemFlags_NoCloseWithMiddleMouseButton = 1 << 2,
  ImGuiTabItemFlags_NoPushId = 1 << 3,
  ImGuiTabItemFlags_NoTooltip = 1 << 4,
  ImGuiTabItemFlags_NoReorder = 1 << 5,
  ImGuiTabItemFlags_Leading = 1 << 6,
  ImGuiTabItemFlags_Trailing = 1 << 7,
  ImGuiTabItemFlags_NoAssumedClosure = 1 << 8
} ImGuiTabItemFlags_;

typedef enum {
  ImGuiFocusedFlags_None,
  ImGuiFocusedFlags_ChildWindows = 1 << 0,
  ImGuiFocusedFlags_RootWindow = 1 << 1,
  ImGuiFocusedFlags_AnyWindow = 1 << 2,
  ImGuiFocusedFlags_NoPopupHierarchy = 1 << 3,
  ImGuiFocusedFlags_RootAndChildWindows = ImGuiFocusedFlags_RootWindow | ImGuiFocusedFlags_ChildWindows
} ImGuiFocusedFlags_;

typedef enum {
  ImGuiHoveredFlags_None,
  ImGuiHoveredFlags_ChildWindows = 1 << 0,
  ImGuiHoveredFlags_RootWindow = 1 << 1,
  ImGuiHoveredFlags_AnyWindow = 1 << 2,
  ImGuiHoveredFlags_NoPopupHierarchy = 1 << 3,
  ImGuiHoveredFlags_AllowWhenBlockedByPopup = 1 << 5,
  ImGuiHoveredFlags_AllowWhenBlockedByActiveItem = 1 << 7,
  ImGuiHoveredFlags_AllowWhenOverlappedByItem = 1 << 8,
  ImGuiHoveredFlags_AllowWhenOverlappedByWindow = 1 << 9,
  ImGuiHoveredFlags_AllowWhenDisabled = 1 << 10,
  ImGuiHoveredFlags_NoNavOverride = 1 << 11,
  ImGuiHoveredFlags_AllowWhenOverlapped = ImGuiHoveredFlags_AllowWhenOverlappedByItem | ImGuiHoveredFlags_AllowWhenOverlappedByWindow,
  ImGuiHoveredFlags_RectOnly = ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_AllowWhenOverlapped,
  ImGuiHoveredFlags_RootAndChildWindows = ImGuiHoveredFlags_RootWindow | ImGuiHoveredFlags_ChildWindows,
  ImGuiHoveredFlags_ForTooltip = 1 << 12,
  ImGuiHoveredFlags_Stationary = 1 << 13,
  ImGuiHoveredFlags_DelayNone = 1 << 14,
  ImGuiHoveredFlags_DelayShort = 1 << 15,
  ImGuiHoveredFlags_DelayNormal = 1 << 16,
  ImGuiHoveredFlags_NoSharedDelay = 1 << 17
} ImGuiHoveredFlags_;

typedef enum {
  ImGuiDragDropFlags_None,
  ImGuiDragDropFlags_SourceNoPreviewTooltip = 1 << 0,
  ImGuiDragDropFlags_SourceNoDisableHover = 1 << 1,
  ImGuiDragDropFlags_SourceNoHoldToOpenOthers = 1 << 2,
  ImGuiDragDropFlags_SourceAllowNullID = 1 << 3,
  ImGuiDragDropFlags_SourceExtern = 1 << 4,
  ImGuiDragDropFlags_PayloadAutoExpire = 1 << 5,
  ImGuiDragDropFlags_PayloadNoCrossContext = 1 << 6,
  ImGuiDragDropFlags_PayloadNoCrossProcess = 1 << 7,
  ImGuiDragDropFlags_AcceptBeforeDelivery = 1 << 10,
  ImGuiDragDropFlags_AcceptNoDrawDefaultRect = 1 << 11,
  ImGuiDragDropFlags_AcceptNoPreviewTooltip = 1 << 12,
  ImGuiDragDropFlags_AcceptPeekOnly = ImGuiDragDropFlags_AcceptBeforeDelivery | ImGuiDragDropFlags_AcceptNoDrawDefaultRect
} ImGuiDragDropFlags_;

typedef enum {
  ImGuiDataType_S8,
  ImGuiDataType_U8,
  ImGuiDataType_S16,
  ImGuiDataType_U16,
  ImGuiDataType_S32,
  ImGuiDataType_U32,
  ImGuiDataType_S64,
  ImGuiDataType_U64,
  ImGuiDataType_Float,
  ImGuiDataType_Double,
  ImGuiDataType_Bool,
  ImGuiDataType_String,
  ImGuiDataType_COUNT
} ImGuiDataType_;

typedef enum {
  ImGuiDir_None,
  ImGuiDir_Left,
  ImGuiDir_Right,
  ImGuiDir_Up,
  ImGuiDir_Down,
  ImGuiDir_COUNT
} ImGuiDir;

typedef enum {
  ImGuiSortDirection_None = 0,
  ImGuiSortDirection_Ascending = 1,
  ImGuiSortDirection_Descending = 2
} ImGuiSortDirection;

typedef enum {
  ImGuiKey_None,
  ImGuiKey_NamedKey_BEGIN,
  ImGuiKey_Tab,
  ImGuiKey_LeftArrow,
  ImGuiKey_RightArrow,
  ImGuiKey_UpArrow,
  ImGuiKey_DownArrow,
  ImGuiKey_PageUp,
  ImGuiKey_PageDown,
  ImGuiKey_Home,
  ImGuiKey_End,
  ImGuiKey_Insert,
  ImGuiKey_Delete,
  ImGuiKey_Backspace,
  ImGuiKey_Space,
  ImGuiKey_Enter,
  ImGuiKey_Escape,
  ImGuiKey_LeftCtrl,
  ImGuiKey_LeftShift,
  ImGuiKey_LeftAlt,
  ImGuiKey_LeftSuper,
  ImGuiKey_RightCtrl,
  ImGuiKey_RightShift,
  ImGuiKey_RightAlt,
  ImGuiKey_RightSuper,
  ImGuiKey_Menu,
  ImGuiKey_0,
  ImGuiKey_1,
  ImGuiKey_2,
  ImGuiKey_3,
  ImGuiKey_4,
  ImGuiKey_5,
  ImGuiKey_6,
  ImGuiKey_7,
  ImGuiKey_8,
  ImGuiKey_9,
  ImGuiKey_A,
  ImGuiKey_B,
  ImGuiKey_C,
  ImGuiKey_D,
  ImGuiKey_E,
  ImGuiKey_F,
  ImGuiKey_G,
  ImGuiKey_H,
  ImGuiKey_I,
  ImGuiKey_J,
  ImGuiKey_K,
  ImGuiKey_L,
  ImGuiKey_M,
  ImGuiKey_N,
  ImGuiKey_O,
  ImGuiKey_P,
  ImGuiKey_Q,
  ImGuiKey_R,
  ImGuiKey_S,
  ImGuiKey_T,
  ImGuiKey_U,
  ImGuiKey_V,
  ImGuiKey_W,
  ImGuiKey_X,
  ImGuiKey_Y,
  ImGuiKey_Z,
  ImGuiKey_F1,
  ImGuiKey_F2,
  ImGuiKey_F3,
  ImGuiKey_F4,
  ImGuiKey_F5,
  ImGuiKey_F6,
  ImGuiKey_F7,
  ImGuiKey_F8,
  ImGuiKey_F9,
  ImGuiKey_F10,
  ImGuiKey_F11,
  ImGuiKey_F12,
  ImGuiKey_F13,
  ImGuiKey_F14,
  ImGuiKey_F15,
  ImGuiKey_F16,
  ImGuiKey_F17,
  ImGuiKey_F18,
  ImGuiKey_F19,
  ImGuiKey_F20,
  ImGuiKey_F21,
  ImGuiKey_F22,
  ImGuiKey_F23,
  ImGuiKey_F24,
  ImGuiKey_Apostrophe,
  ImGuiKey_Comma,
  ImGuiKey_Minus,
  ImGuiKey_Period,
  ImGuiKey_Slash,
  ImGuiKey_Semicolon,
  ImGuiKey_Equal,
  ImGuiKey_LeftBracket,
  ImGuiKey_Backslash,
  ImGuiKey_RightBracket,
  ImGuiKey_GraveAccent,
  ImGuiKey_CapsLock,
  ImGuiKey_ScrollLock,
  ImGuiKey_NumLock,
  ImGuiKey_PrintScreen,
  ImGuiKey_Pause,
  ImGuiKey_Keypad0,
  ImGuiKey_Keypad1,
  ImGuiKey_Keypad2,
  ImGuiKey_Keypad3,
  ImGuiKey_Keypad4,
  ImGuiKey_Keypad5,
  ImGuiKey_Keypad6,
  ImGuiKey_Keypad7,
  ImGuiKey_Keypad8,
  ImGuiKey_Keypad9,
  ImGuiKey_KeypadDecimal,
  ImGuiKey_KeypadDivide,
  ImGuiKey_KeypadMultiply,
  ImGuiKey_KeypadSubtract,
  ImGuiKey_KeypadAdd,
  ImGuiKey_KeypadEnter,
  ImGuiKey_KeypadEqual,
  ImGuiKey_AppBack,
  ImGuiKey_AppForward,
  ImGuiKey_Oem102,
  ImGuiKey_GamepadStart,
  ImGuiKey_GamepadBack,
  ImGuiKey_GamepadFaceLeft,
  ImGuiKey_GamepadFaceRight,
  ImGuiKey_GamepadFaceUp,
  ImGuiKey_GamepadFaceDown,
  ImGuiKey_GamepadDpadLeft,
  ImGuiKey_GamepadDpadRight,
  ImGuiKey_GamepadDpadUp,
  ImGuiKey_GamepadDpadDown,
  ImGuiKey_GamepadL1,
  ImGuiKey_GamepadR1,
  ImGuiKey_GamepadL2,
  ImGuiKey_GamepadR2,
  ImGuiKey_GamepadL3,
  ImGuiKey_GamepadR3,
  ImGuiKey_GamepadLStickLeft,
  ImGuiKey_GamepadLStickRight,
  ImGuiKey_GamepadLStickUp,
  ImGuiKey_GamepadLStickDown,
  ImGuiKey_GamepadRStickLeft,
  ImGuiKey_GamepadRStickRight,
  ImGuiKey_GamepadRStickUp,
  ImGuiKey_GamepadRStickDown,
  ImGuiKey_MouseLeft,
  ImGuiKey_MouseRight,
  ImGuiKey_MouseMiddle,
  ImGuiKey_MouseX1,
  ImGuiKey_MouseX2,
  ImGuiKey_MouseWheelX,
  ImGuiKey_MouseWheelY,
  ImGuiKey_ReservedForModCtrl,
  ImGuiKey_ReservedForModShift,
  ImGuiKey_ReservedForModAlt,
  ImGuiKey_ReservedForModSuper,
  ImGuiKey_NamedKey_END,
  ImGuiKey_NamedKey_COUNT = ImGuiKey_NamedKey_END - ImGuiKey_NamedKey_BEGIN,
  ImGuiMod_None,
  ImGuiMod_Ctrl = 1 << 12,
  ImGuiMod_Shift = 1 << 13,
  ImGuiMod_Alt = 1 << 14,
  ImGuiMod_Super = 1 << 15,
  ImGuiMod_Mask_
} ImGuiKey;

typedef enum {
  ImGuiInputFlags_None,
  ImGuiInputFlags_Repeat = 1 << 0,
  ImGuiInputFlags_RouteActive = 1 << 10,
  ImGuiInputFlags_RouteFocused = 1 << 11,
  ImGuiInputFlags_RouteGlobal = 1 << 12,
  ImGuiInputFlags_RouteAlways = 1 << 13,
  ImGuiInputFlags_RouteOverFocused = 1 << 14,
  ImGuiInputFlags_RouteOverActive = 1 << 15,
  ImGuiInputFlags_RouteUnlessBgFocused = 1 << 16,
  ImGuiInputFlags_RouteFromRootWindow = 1 << 17,
  ImGuiInputFlags_Tooltip = 1 << 18
} ImGuiInputFlags_;

typedef enum {
  ImGuiConfigFlags_None,
  ImGuiConfigFlags_NavEnableKeyboard = 1 << 0,
  ImGuiConfigFlags_NavEnableGamepad = 1 << 1,
  ImGuiConfigFlags_NoMouse = 1 << 4,
  ImGuiConfigFlags_NoMouseCursorChange = 1 << 5,
  ImGuiConfigFlags_NoKeyboard = 1 << 6,
  ImGuiConfigFlags_IsSRGB = 1 << 20,
  ImGuiConfigFlags_IsTouchScreen = 1 << 21
} ImGuiConfigFlags_;

typedef enum {
  ImGuiBackendFlags_None,
  ImGuiBackendFlags_HasGamepad = 1 << 0,
  ImGuiBackendFlags_HasMouseCursors = 1 << 1,
  ImGuiBackendFlags_HasSetMousePos = 1 << 2,
  ImGuiBackendFlags_RendererHasVtxOffset = 1 << 3,
  ImGuiBackendFlags_RendererHasTextures = 1 << 4
} ImGuiBackendFlags_;

typedef enum {
  ImGuiCol_Text,
  ImGuiCol_TextDisabled,
  ImGuiCol_WindowBg,
  ImGuiCol_ChildBg,
  ImGuiCol_PopupBg,
  ImGuiCol_Border,
  ImGuiCol_BorderShadow,
  ImGuiCol_FrameBg,
  ImGuiCol_FrameBgHovered,
  ImGuiCol_FrameBgActive,
  ImGuiCol_TitleBg,
  ImGuiCol_TitleBgActive,
  ImGuiCol_TitleBgCollapsed,
  ImGuiCol_MenuBarBg,
  ImGuiCol_ScrollbarBg,
  ImGuiCol_ScrollbarGrab,
  ImGuiCol_ScrollbarGrabHovered,
  ImGuiCol_ScrollbarGrabActive,
  ImGuiCol_CheckMark,
  ImGuiCol_SliderGrab,
  ImGuiCol_SliderGrabActive,
  ImGuiCol_Button,
  ImGuiCol_ButtonHovered,
  ImGuiCol_ButtonActive,
  ImGuiCol_Header,
  ImGuiCol_HeaderHovered,
  ImGuiCol_HeaderActive,
  ImGuiCol_Separator,
  ImGuiCol_SeparatorHovered,
  ImGuiCol_SeparatorActive,
  ImGuiCol_ResizeGrip,
  ImGuiCol_ResizeGripHovered,
  ImGuiCol_ResizeGripActive,
  ImGuiCol_InputTextCursor,
  ImGuiCol_TabHovered,
  ImGuiCol_Tab,
  ImGuiCol_TabSelected,
  ImGuiCol_TabSelectedOverline,
  ImGuiCol_TabDimmed,
  ImGuiCol_TabDimmedSelected,
  ImGuiCol_TabDimmedSelectedOverline,
  ImGuiCol_PlotLines,
  ImGuiCol_PlotLinesHovered,
  ImGuiCol_PlotHistogram,
  ImGuiCol_PlotHistogramHovered,
  ImGuiCol_TableHeaderBg,
  ImGuiCol_TableBorderStrong,
  ImGuiCol_TableBorderLight,
  ImGuiCol_TableRowBg,
  ImGuiCol_TableRowBgAlt,
  ImGuiCol_TextLink,
  ImGuiCol_TextSelectedBg,
  ImGuiCol_TreeLines,
  ImGuiCol_DragDropTarget,
  ImGuiCol_NavCursor,
  ImGuiCol_NavWindowingHighlight,
  ImGuiCol_NavWindowingDimBg,
  ImGuiCol_ModalWindowDimBg,
  ImGuiCol_COUNT
} ImGuiCol_;

typedef enum {
  ImGuiStyleVar_Alpha,
  ImGuiStyleVar_DisabledAlpha,
  ImGuiStyleVar_WindowPadding,
  ImGuiStyleVar_WindowRounding,
  ImGuiStyleVar_WindowBorderSize,
  ImGuiStyleVar_WindowMinSize,
  ImGuiStyleVar_WindowTitleAlign,
  ImGuiStyleVar_ChildRounding,
  ImGuiStyleVar_ChildBorderSize,
  ImGuiStyleVar_PopupRounding,
  ImGuiStyleVar_PopupBorderSize,
  ImGuiStyleVar_FramePadding,
  ImGuiStyleVar_FrameRounding,
  ImGuiStyleVar_FrameBorderSize,
  ImGuiStyleVar_ItemSpacing,
  ImGuiStyleVar_ItemInnerSpacing,
  ImGuiStyleVar_IndentSpacing,
  ImGuiStyleVar_CellPadding,
  ImGuiStyleVar_ScrollbarSize,
  ImGuiStyleVar_ScrollbarRounding,
  ImGuiStyleVar_ScrollbarPadding,
  ImGuiStyleVar_GrabMinSize,
  ImGuiStyleVar_GrabRounding,
  ImGuiStyleVar_ImageBorderSize,
  ImGuiStyleVar_TabRounding,
  ImGuiStyleVar_TabBorderSize,
  ImGuiStyleVar_TabMinWidthBase,
  ImGuiStyleVar_TabMinWidthShrink,
  ImGuiStyleVar_TabBarBorderSize,
  ImGuiStyleVar_TabBarOverlineSize,
  ImGuiStyleVar_TableAngledHeadersAngle,
  ImGuiStyleVar_TableAngledHeadersTextAlign,
  ImGuiStyleVar_TreeLinesSize,
  ImGuiStyleVar_TreeLinesRounding,
  ImGuiStyleVar_ButtonTextAlign,
  ImGuiStyleVar_SelectableTextAlign,
  ImGuiStyleVar_SeparatorTextBorderSize,
  ImGuiStyleVar_SeparatorTextAlign,
  ImGuiStyleVar_SeparatorTextPadding,
  ImGuiStyleVar_COUNT
} ImGuiStyleVar_;

typedef enum {
  ImGuiButtonFlags_None,
  ImGuiButtonFlags_MouseButtonLeft = 1 << 0,
  ImGuiButtonFlags_MouseButtonRight = 1 << 1,
  ImGuiButtonFlags_MouseButtonMiddle = 1 << 2,
  ImGuiButtonFlags_MouseButtonMask_ = ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_MouseButtonMiddle,
  ImGuiButtonFlags_EnableNav = 1 << 3
} ImGuiButtonFlags_;

typedef enum {
  ImGuiColorEditFlags_None,
  ImGuiColorEditFlags_NoAlpha = 1 << 1,
  ImGuiColorEditFlags_NoPicker = 1 << 2,
  ImGuiColorEditFlags_NoOptions = 1 << 3,
  ImGuiColorEditFlags_NoSmallPreview = 1 << 4,
  ImGuiColorEditFlags_NoInputs = 1 << 5,
  ImGuiColorEditFlags_NoTooltip = 1 << 6,
  ImGuiColorEditFlags_NoLabel = 1 << 7,
  ImGuiColorEditFlags_NoSidePreview = 1 << 8,
  ImGuiColorEditFlags_NoDragDrop = 1 << 9,
  ImGuiColorEditFlags_NoBorder = 1 << 10,
  ImGuiColorEditFlags_AlphaOpaque = 1 << 11,
  ImGuiColorEditFlags_AlphaNoBg = 1 << 12,
  ImGuiColorEditFlags_AlphaPreviewHalf = 1 << 13,
  ImGuiColorEditFlags_AlphaBar = 1 << 16,
  ImGuiColorEditFlags_HDR = 1 << 19,
  ImGuiColorEditFlags_DisplayRGB = 1 << 20,
  ImGuiColorEditFlags_DisplayHSV = 1 << 21,
  ImGuiColorEditFlags_DisplayHex = 1 << 22,
  ImGuiColorEditFlags_Uint8 = 1 << 23,
  ImGuiColorEditFlags_Float = 1 << 24,
  ImGuiColorEditFlags_PickerHueBar = 1 << 25,
  ImGuiColorEditFlags_PickerHueWheel = 1 << 26,
  ImGuiColorEditFlags_InputRGB = 1 << 27,
  ImGuiColorEditFlags_InputHSV = 1 << 28,
  ImGuiColorEditFlags_DefaultOptions_ = ImGuiColorEditFlags_Uint8 | ImGuiColorEditFlags_DisplayRGB | ImGuiColorEditFlags_InputRGB | ImGuiColorEditFlags_PickerHueBar,
  ImGuiColorEditFlags_AlphaMask_ = ImGuiColorEditFlags_NoAlpha | ImGuiColorEditFlags_AlphaOpaque | ImGuiColorEditFlags_AlphaNoBg | ImGuiColorEditFlags_AlphaPreviewHalf,
  ImGuiColorEditFlags_DisplayMask_ = ImGuiColorEditFlags_DisplayRGB | ImGuiColorEditFlags_DisplayHSV | ImGuiColorEditFlags_DisplayHex,
  ImGuiColorEditFlags_DataTypeMask_ = ImGuiColorEditFlags_Uint8 | ImGuiColorEditFlags_Float,
  ImGuiColorEditFlags_PickerMask_ = ImGuiColorEditFlags_PickerHueWheel | ImGuiColorEditFlags_PickerHueBar,
  ImGuiColorEditFlags_InputMask_ = ImGuiColorEditFlags_InputRGB | ImGuiColorEditFlags_InputHSV
} ImGuiColorEditFlags_;

typedef enum {
  ImGuiSliderFlags_None,
  ImGuiSliderFlags_Logarithmic = 1 << 5,
  ImGuiSliderFlags_NoRoundToFormat = 1 << 6,
  ImGuiSliderFlags_NoInput = 1 << 7,
  ImGuiSliderFlags_WrapAround = 1 << 8,
  ImGuiSliderFlags_ClampOnInput = 1 << 9,
  ImGuiSliderFlags_ClampZeroRange = 1 << 10,
  ImGuiSliderFlags_NoSpeedTweaks = 1 << 11,
  ImGuiSliderFlags_AlwaysClamp = ImGuiSliderFlags_ClampOnInput | ImGuiSliderFlags_ClampZeroRange,
  ImGuiSliderFlags_InvalidMask_
} ImGuiSliderFlags_;

typedef enum {
  ImGuiMouseButton_Left,
  ImGuiMouseButton_Right,
  ImGuiMouseButton_Middle,
  ImGuiMouseButton_COUNT
} ImGuiMouseButton_;

typedef enum {
  ImGuiMouseCursor_None,
  ImGuiMouseCursor_Arrow,
  ImGuiMouseCursor_TextInput,
  ImGuiMouseCursor_ResizeAll,
  ImGuiMouseCursor_ResizeNS,
  ImGuiMouseCursor_ResizeEW,
  ImGuiMouseCursor_ResizeNESW,
  ImGuiMouseCursor_ResizeNWSE,
  ImGuiMouseCursor_Hand,
  ImGuiMouseCursor_Wait,
  ImGuiMouseCursor_Progress,
  ImGuiMouseCursor_NotAllowed,
  ImGuiMouseCursor_COUNT
} ImGuiMouseCursor_;

typedef enum {
  ImGuiMouseSource_Mouse,
  ImGuiMouseSource_TouchScreen,
  ImGuiMouseSource_Pen,
  ImGuiMouseSource_COUNT
} ImGuiMouseSource;

typedef enum {
  ImGuiCond_None,
  ImGuiCond_Always = 1 << 0,
  ImGuiCond_Once = 1 << 1,
  ImGuiCond_FirstUseEver = 1 << 2,
  ImGuiCond_Appearing = 1 << 3
} ImGuiCond_;

typedef enum {
  ImGuiTableFlags_None,
  ImGuiTableFlags_Resizable = 1 << 0,
  ImGuiTableFlags_Reorderable = 1 << 1,
  ImGuiTableFlags_Hideable = 1 << 2,
  ImGuiTableFlags_Sortable = 1 << 3,
  ImGuiTableFlags_NoSavedSettings = 1 << 4,
  ImGuiTableFlags_ContextMenuInBody = 1 << 5,
  ImGuiTableFlags_RowBg = 1 << 6,
  ImGuiTableFlags_BordersInnerH = 1 << 7,
  ImGuiTableFlags_BordersOuterH = 1 << 8,
  ImGuiTableFlags_BordersInnerV = 1 << 9,
  ImGuiTableFlags_BordersOuterV = 1 << 10,
  ImGuiTableFlags_BordersH = ImGuiTableFlags_BordersInnerH | ImGuiTableFlags_BordersOuterH,
  ImGuiTableFlags_BordersV = ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_BordersOuterV,
  ImGuiTableFlags_BordersInner = ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_BordersInnerH,
  ImGuiTableFlags_BordersOuter = ImGuiTableFlags_BordersOuterV | ImGuiTableFlags_BordersOuterH,
  ImGuiTableFlags_Borders = ImGuiTableFlags_BordersInner | ImGuiTableFlags_BordersOuter,
  ImGuiTableFlags_NoBordersInBody = 1 << 11,
  ImGuiTableFlags_NoBordersInBodyUntilResize = 1 << 12,
  ImGuiTableFlags_SizingFixedFit = 1 << 13,
  ImGuiTableFlags_SizingFixedSame = 2 << 13,
  ImGuiTableFlags_SizingStretchProp = 3 << 13,
  ImGuiTableFlags_SizingStretchSame = 4 << 13,
  ImGuiTableFlags_NoHostExtendX = 1 << 16,
  ImGuiTableFlags_NoHostExtendY = 1 << 17,
  ImGuiTableFlags_NoKeepColumnsVisible = 1 << 18,
  ImGuiTableFlags_PreciseWidths = 1 << 19,
  ImGuiTableFlags_NoClip = 1 << 20,
  ImGuiTableFlags_PadOuterX = 1 << 21,
  ImGuiTableFlags_NoPadOuterX = 1 << 22,
  ImGuiTableFlags_NoPadInnerX = 1 << 23,
  ImGuiTableFlags_ScrollX = 1 << 24,
  ImGuiTableFlags_ScrollY = 1 << 25,
  ImGuiTableFlags_SortMulti = 1 << 26,
  ImGuiTableFlags_SortTristate = 1 << 27,
  ImGuiTableFlags_HighlightHoveredColumn = 1 << 28,
  ImGuiTableFlags_SizingMask_ = ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_SizingFixedSame | ImGuiTableFlags_SizingStretchProp | ImGuiTableFlags_SizingStretchSame
} ImGuiTableFlags_;

typedef enum {
  ImGuiTableColumnFlags_None,
  ImGuiTableColumnFlags_Disabled = 1 << 0,
  ImGuiTableColumnFlags_DefaultHide = 1 << 1,
  ImGuiTableColumnFlags_DefaultSort = 1 << 2,
  ImGuiTableColumnFlags_WidthStretch = 1 << 3,
  ImGuiTableColumnFlags_WidthFixed = 1 << 4,
  ImGuiTableColumnFlags_NoResize = 1 << 5,
  ImGuiTableColumnFlags_NoReorder = 1 << 6,
  ImGuiTableColumnFlags_NoHide = 1 << 7,
  ImGuiTableColumnFlags_NoClip = 1 << 8,
  ImGuiTableColumnFlags_NoSort = 1 << 9,
  ImGuiTableColumnFlags_NoSortAscending = 1 << 10,
  ImGuiTableColumnFlags_NoSortDescending = 1 << 11,
  ImGuiTableColumnFlags_NoHeaderLabel = 1 << 12,
  ImGuiTableColumnFlags_NoHeaderWidth = 1 << 13,
  ImGuiTableColumnFlags_PreferSortAscending = 1 << 14,
  ImGuiTableColumnFlags_PreferSortDescending = 1 << 15,
  ImGuiTableColumnFlags_IndentEnable = 1 << 16,
  ImGuiTableColumnFlags_IndentDisable = 1 << 17,
  ImGuiTableColumnFlags_AngledHeader = 1 << 18,
  ImGuiTableColumnFlags_IsEnabled = 1 << 24,
  ImGuiTableColumnFlags_IsVisible = 1 << 25,
  ImGuiTableColumnFlags_IsSorted = 1 << 26,
  ImGuiTableColumnFlags_IsHovered = 1 << 27,
  ImGuiTableColumnFlags_WidthMask_ = ImGuiTableColumnFlags_WidthStretch | ImGuiTableColumnFlags_WidthFixed,
  ImGuiTableColumnFlags_IndentMask_ = ImGuiTableColumnFlags_IndentEnable | ImGuiTableColumnFlags_IndentDisable,
  ImGuiTableColumnFlags_StatusMask_ = ImGuiTableColumnFlags_IsEnabled | ImGuiTableColumnFlags_IsVisible | ImGuiTableColumnFlags_IsSorted | ImGuiTableColumnFlags_IsHovered,
  ImGuiTableColumnFlags_NoDirectResize_ = 1 << 30
} ImGuiTableColumnFlags_;

typedef enum {
  ImGuiTableRowFlags_None,
  ImGuiTableRowFlags_Headers = 1 << 0
} ImGuiTableRowFlags_;

typedef enum {
  ImGuiTableBgTarget_None,
  ImGuiTableBgTarget_RowBg0,
  ImGuiTableBgTarget_RowBg1,
  ImGuiTableBgTarget_CellBg
} ImGuiTableBgTarget_;
typedef struct ImGuiTableSortSpecs {
  const ImGuiTableColumnSortSpecs* Specs;
  int SpecsCount;
  bool SpecsDirty;
} ImGuiTableSortSpecs;
// void imgui_ImGuiTableSortSpecs();
typedef struct ImGuiTableColumnSortSpecs {
  ImGuiID ColumnUserID;
  ImS16 ColumnIndex;
  ImS16 SortOrder;
  ImGuiSortDirection SortDirection;
} ImGuiTableColumnSortSpecs;
// void imgui_ImGuiTableColumnSortSpecs();
typedef struct ImNewWrapper {
} ImNewWrapper;
typedef struct ImGuiStyle {
  float FontSizeBase;
  float FontScaleMain;
  float FontScaleDpi;
  float Alpha;
  float DisabledAlpha;
  ImVec2_C WindowPadding;
  float WindowRounding;
  float WindowBorderSize;
  float WindowBorderHoverPadding;
  ImVec2_C WindowMinSize;
  ImVec2_C WindowTitleAlign;
  ImGuiDir WindowMenuButtonPosition;
  float ChildRounding;
  float ChildBorderSize;
  float PopupRounding;
  float PopupBorderSize;
  ImVec2_C FramePadding;
  float FrameRounding;
  float FrameBorderSize;
  ImVec2_C ItemSpacing;
  ImVec2_C ItemInnerSpacing;
  ImVec2_C CellPadding;
  ImVec2_C TouchExtraPadding;
  float IndentSpacing;
  float ColumnsMinSpacing;
  float ScrollbarSize;
  float ScrollbarRounding;
  float ScrollbarPadding;
  float GrabMinSize;
  float GrabRounding;
  float LogSliderDeadzone;
  float ImageBorderSize;
  float TabRounding;
  float TabBorderSize;
  float TabMinWidthBase;
  float TabMinWidthShrink;
  float TabCloseButtonMinWidthSelected;
  float TabCloseButtonMinWidthUnselected;
  float TabBarBorderSize;
  float TabBarOverlineSize;
  float TableAngledHeadersAngle;
  ImVec2_C TableAngledHeadersTextAlign;
  ImGuiTreeNodeFlags TreeLinesFlags;
  float TreeLinesSize;
  float TreeLinesRounding;
  ImGuiDir ColorButtonPosition;
  ImVec2_C ButtonTextAlign;
  ImVec2_C SelectableTextAlign;
  float SeparatorTextBorderSize;
  ImVec2_C SeparatorTextAlign;
  ImVec2_C SeparatorTextPadding;
  ImVec2_C DisplayWindowPadding;
  ImVec2_C DisplaySafeAreaPadding;
  float MouseCursorScale;
  bool AntiAliasedLines;
  bool AntiAliasedLinesUseTex;
  bool AntiAliasedFill;
  float CurveTessellationTol;
  float CircleTessellationMaxError;
  ImVec4_C Colors[58];
  float HoverStationaryDelay;
  float HoverDelayShort;
  float HoverDelayNormal;
  ImGuiHoveredFlags HoverFlagsForTooltipMouse;
  ImGuiHoveredFlags HoverFlagsForTooltipNav;
  float _MainScale;
  float _NextFrameFontSizeBase;
} ImGuiStyle;
// void imgui_ImGuiStyle();
void imgui_ImGuiStyle_ScaleAllSizes(ImGuiStyle* ImGuiStyle_ctx, float scale_factor);
typedef struct ImGuiKeyData {
  bool Down;
  float DownDuration;
  float DownDurationPrev;
  float AnalogValue;
} ImGuiKeyData;
typedef struct ImGuiIO {
  ImGuiConfigFlags ConfigFlags;
  ImGuiBackendFlags BackendFlags;
  ImVec2_C DisplaySize;
  ImVec2_C DisplayFramebufferScale;
  float DeltaTime;
  float IniSavingRate;
  const char* IniFilename;
  const char* LogFilename;
  void* UserData;
  ImFontAtlas* Fonts;
  ImFont* FontDefault;
  bool FontAllowUserScaling;
  bool ConfigNavSwapGamepadButtons;
  bool ConfigNavMoveSetMousePos;
  bool ConfigNavCaptureKeyboard;
  bool ConfigNavEscapeClearFocusItem;
  bool ConfigNavEscapeClearFocusWindow;
  bool ConfigNavCursorVisibleAuto;
  bool ConfigNavCursorVisibleAlways;
  bool MouseDrawCursor;
  bool ConfigMacOSXBehaviors;
  bool ConfigInputTrickleEventQueue;
  bool ConfigInputTextCursorBlink;
  bool ConfigInputTextEnterKeepActive;
  bool ConfigDragClickToInputText;
  bool ConfigWindowsResizeFromEdges;
  bool ConfigWindowsMoveFromTitleBarOnly;
  bool ConfigWindowsCopyContentsWithCtrlC;
  bool ConfigScrollbarScrollByPage;
  float ConfigMemoryCompactTimer;
  float MouseDoubleClickTime;
  float MouseDoubleClickMaxDist;
  float MouseDragThreshold;
  float KeyRepeatDelay;
  float KeyRepeatRate;
  bool ConfigErrorRecovery;
  bool ConfigErrorRecoveryEnableAssert;
  bool ConfigErrorRecoveryEnableDebugLog;
  bool ConfigErrorRecoveryEnableTooltip;
  bool ConfigDebugIsDebuggerPresent;
  bool ConfigDebugHighlightIdConflicts;
  bool ConfigDebugHighlightIdConflictsShowItemPicker;
  bool ConfigDebugBeginReturnValueOnce;
  bool ConfigDebugBeginReturnValueLoop;
  bool ConfigDebugIgnoreFocusLoss;
  bool ConfigDebugIniSettings;
  const char* BackendPlatformName;
  const char* BackendRendererName;
  void* BackendPlatformUserData;
  void* BackendRendererUserData;
  void* BackendLanguageUserData;
  bool WantCaptureMouse;
  bool WantCaptureKeyboard;
  bool WantTextInput;
  bool WantSetMousePos;
  bool WantSaveIniSettings;
  bool NavActive;
  bool NavVisible;
  float Framerate;
  int MetricsRenderVertices;
  int MetricsRenderIndices;
  int MetricsRenderWindows;
  int MetricsActiveWindows;
  ImVec2_C MouseDelta;
  ImGuiContext* Ctx;
  ImVec2_C MousePos;
  bool MouseDown[5];
  float MouseWheel;
  float MouseWheelH;
  ImGuiMouseSource MouseSource;
  bool KeyCtrl;
  bool KeyShift;
  bool KeyAlt;
  bool KeySuper;
  ImGuiKeyChord KeyMods;
  ImGuiKeyData KeysData[155];
  bool WantCaptureMouseUnlessPopupClose;
  ImVec2_C MousePosPrev;
  ImVec2_C MouseClickedPos[5];
  double MouseClickedTime[5];
  bool MouseClicked[5];
  bool MouseDoubleClicked[5];
  ImU16 MouseClickedCount[5];
  ImU16 MouseClickedLastCount[5];
  bool MouseReleased[5];
  double MouseReleasedTime[5];
  bool MouseDownOwned[5];
  bool MouseDownOwnedUnlessPopupClose[5];
  bool MouseWheelRequestAxisSwap;
  bool MouseCtrlLeftAsRightClick;
  float MouseDownDuration[5];
  float MouseDownDurationPrev[5];
  float MouseDragMaxDistanceSqr[5];
  float PenPressure;
  bool AppFocusLost;
  bool AppAcceptingEvents;
  ImWchar16 InputQueueSurrogate;
  ImVector InputQueueCharacters;
} ImGuiIO;
void imgui_ImGuiIO_AddKeyEvent(ImGuiIO* ImGuiIO_ctx, ImGuiKey key, bool down);
void imgui_ImGuiIO_AddKeyAnalogEvent(ImGuiIO* ImGuiIO_ctx, ImGuiKey key, bool down, float v);
void imgui_ImGuiIO_AddMousePosEvent(ImGuiIO* ImGuiIO_ctx, float x, float y);
void imgui_ImGuiIO_AddMouseButtonEvent(ImGuiIO* ImGuiIO_ctx, int button, bool down);
void imgui_ImGuiIO_AddMouseWheelEvent(ImGuiIO* ImGuiIO_ctx, float wheel_x, float wheel_y);
void imgui_ImGuiIO_AddMouseSourceEvent(ImGuiIO* ImGuiIO_ctx, ImGuiMouseSource source);
void imgui_ImGuiIO_AddFocusEvent(ImGuiIO* ImGuiIO_ctx, bool focused);
void imgui_ImGuiIO_AddInputCharacter(ImGuiIO* ImGuiIO_ctx, unsigned int c);
void imgui_ImGuiIO_AddInputCharacterUTF16(ImGuiIO* ImGuiIO_ctx, ImWchar16 c);
void imgui_ImGuiIO_AddInputCharactersUTF8(ImGuiIO* ImGuiIO_ctx, const char* str);
void imgui_ImGuiIO_SetKeyEventNativeData(ImGuiIO* ImGuiIO_ctx, ImGuiKey key, int native_keycode, int native_scancode, int native_legacy_index);
void imgui_ImGuiIO_SetAppAcceptingEvents(ImGuiIO* ImGuiIO_ctx, bool accepting_events);
void imgui_ImGuiIO_ClearEventsQueue(ImGuiIO* ImGuiIO_ctx);
void imgui_ImGuiIO_ClearInputKeys(ImGuiIO* ImGuiIO_ctx);
void imgui_ImGuiIO_ClearInputMouse(ImGuiIO* ImGuiIO_ctx);
// void imgui_ImGuiIO();
typedef struct ImGuiInputTextCallbackData {
  ImGuiContext* Ctx;
  ImGuiInputTextFlags EventFlag;
  ImGuiInputTextFlags Flags;
  void* UserData;
  ImWchar EventChar;
  ImGuiKey EventKey;
  char* Buf;
  int BufTextLen;
  int BufSize;
  bool BufDirty;
  int CursorPos;
  int SelectionStart;
  int SelectionEnd;
} ImGuiInputTextCallbackData;
// void imgui_ImGuiInputTextCallbackData();
void imgui_ImGuiInputTextCallbackData_DeleteChars(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx, int pos, int bytes_count);
void imgui_ImGuiInputTextCallbackData_InsertChars(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx, int pos, const char* text, const char* text_end);
void imgui_ImGuiInputTextCallbackData_SelectAll(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx);
void imgui_ImGuiInputTextCallbackData_ClearSelection(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx);
bool imgui_ImGuiInputTextCallbackData_HasSelection(ImGuiInputTextCallbackData* ImGuiInputTextCallbackData_ctx);
typedef struct ImGuiSizeCallbackData {
  void* UserData;
  ImVec2_C Pos;
  ImVec2_C CurrentSize;
  ImVec2_C DesiredSize;
} ImGuiSizeCallbackData;
typedef struct ImGuiPayload {
  void* Data;
  int DataSize;
  ImGuiID SourceId;
  ImGuiID SourceParentId;
  int DataFrameCount;
  char DataType[33];
  bool Preview;
  bool Delivery;
} ImGuiPayload;
// void imgui_ImGuiPayload();
void imgui_ImGuiPayload_Clear(ImGuiPayload* ImGuiPayload_ctx);
bool imgui_ImGuiPayload_IsDataType(ImGuiPayload* ImGuiPayload_ctx, const char* type);
bool imgui_ImGuiPayload_IsPreview(ImGuiPayload* ImGuiPayload_ctx);
bool imgui_ImGuiPayload_IsDelivery(ImGuiPayload* ImGuiPayload_ctx);
typedef struct ImGuiTextFilter {
  
struct ImGuiTextRange {
    const char* b;
    const char* e;
  };
  char InputBuf[256];
  ImVector Filters;
  int CountGrep;
} ImGuiTextFilter;
// void imgui_ImGuiTextFilter(const char* default_filter);
bool imgui_ImGuiTextFilter_Draw(ImGuiTextFilter* ImGuiTextFilter_ctx, const char* label, float width);
bool imgui_ImGuiTextFilter_PassFilter(ImGuiTextFilter* ImGuiTextFilter_ctx, const char* text, const char* text_end);
void imgui_ImGuiTextFilter_Build(ImGuiTextFilter* ImGuiTextFilter_ctx);
void imgui_ImGuiTextFilter_Clear(ImGuiTextFilter* ImGuiTextFilter_ctx);
bool imgui_ImGuiTextFilter_IsActive(ImGuiTextFilter* ImGuiTextFilter_ctx);
typedef struct ImGuiTextBuffer {
  ImVector Buf;
} ImGuiTextBuffer;
// void imgui_ImGuiTextBuffer();
const char * imgui_ImGuiTextBuffer_begin(ImGuiTextBuffer* ImGuiTextBuffer_ctx);
const char * imgui_ImGuiTextBuffer_end(ImGuiTextBuffer* ImGuiTextBuffer_ctx);
int imgui_ImGuiTextBuffer_size(ImGuiTextBuffer* ImGuiTextBuffer_ctx);
bool imgui_ImGuiTextBuffer_empty(ImGuiTextBuffer* ImGuiTextBuffer_ctx);
void imgui_ImGuiTextBuffer_clear(ImGuiTextBuffer* ImGuiTextBuffer_ctx);
void imgui_ImGuiTextBuffer_resize(ImGuiTextBuffer* ImGuiTextBuffer_ctx, int size);
void imgui_ImGuiTextBuffer_reserve(ImGuiTextBuffer* ImGuiTextBuffer_ctx, int capacity);
const char * imgui_ImGuiTextBuffer_c_str(ImGuiTextBuffer* ImGuiTextBuffer_ctx);
void imgui_ImGuiTextBuffer_append(ImGuiTextBuffer* ImGuiTextBuffer_ctx, const char* str, const char* str_end);
void imgui_ImGuiTextBuffer_appendfv(ImGuiTextBuffer* ImGuiTextBuffer_ctx, const char* fmt, va_list args);
typedef struct ImGuiStoragePair {
  ImGuiID key;
  

union {
    int val_i;
    float val_f;
    void* val_p;
  };
} ImGuiStoragePair;
// void imgui_ImGuiStoragePair(ImGuiID _key, int _val);
// void imgui_ImGuiStoragePair(ImGuiID _key, float _val);
// void imgui_ImGuiStoragePair(ImGuiID _key, void* _val);
typedef struct ImGuiStorage {
  ImVector Data;
} ImGuiStorage;
void imgui_ImGuiStorage_Clear(ImGuiStorage* ImGuiStorage_ctx);
int imgui_ImGuiStorage_GetInt(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, int default_val);
void imgui_ImGuiStorage_SetInt(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, int val);
bool imgui_ImGuiStorage_GetBool(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, bool default_val);
void imgui_ImGuiStorage_SetBool(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, bool val);
float imgui_ImGuiStorage_GetFloat(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, float default_val);
void imgui_ImGuiStorage_SetFloat(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, float val);
void * imgui_ImGuiStorage_GetVoidPtr(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key);
void imgui_ImGuiStorage_SetVoidPtr(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, void* val);
int * imgui_ImGuiStorage_GetIntRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, int default_val);
bool * imgui_ImGuiStorage_GetBoolRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, bool default_val);
float * imgui_ImGuiStorage_GetFloatRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, float default_val);
void ** imgui_ImGuiStorage_GetVoidPtrRef(ImGuiStorage* ImGuiStorage_ctx, ImGuiID key, void* default_val);
void imgui_ImGuiStorage_BuildSortByKey(ImGuiStorage* ImGuiStorage_ctx);
void imgui_ImGuiStorage_SetAllInt(ImGuiStorage* ImGuiStorage_ctx, int val);

typedef enum {
  ImGuiListClipperFlags_None,
  ImGuiListClipperFlags_NoSetTableRowCounters = 1 << 0
} ImGuiListClipperFlags_;
typedef struct ImGuiListClipper {
  ImGuiContext* Ctx;
  int DisplayStart;
  int DisplayEnd;
  int ItemsCount;
  float ItemsHeight;
  double StartPosY;
  double StartSeekOffsetY;
  void* TempData;
  ImGuiListClipperFlags Flags;
} ImGuiListClipper;
// void imgui_ImGuiListClipper();
void imgui_ImGuiListClipper_Begin(ImGuiListClipper* ImGuiListClipper_ctx, int items_count, float items_height);
void imgui_ImGuiListClipper_End(ImGuiListClipper* ImGuiListClipper_ctx);
bool imgui_ImGuiListClipper_Step(ImGuiListClipper* ImGuiListClipper_ctx);
void imgui_ImGuiListClipper_IncludeItemByIndex(ImGuiListClipper* ImGuiListClipper_ctx, int item_index);
void imgui_ImGuiListClipper_IncludeItemsByIndex(ImGuiListClipper* ImGuiListClipper_ctx, int item_begin, int item_end);
void imgui_ImGuiListClipper_SeekCursorForItem(ImGuiListClipper* ImGuiListClipper_ctx, int item_index);
typedef struct ImColor {
  ImVec4_C Value;
} ImColor;
// void imgui_ImColor();
// void imgui_ImColor(float r, float g, float b, float a);
// void imgui_ImColor(const ImVec4_C* col);
// void imgui_ImColor(int r, int g, int b, int a);
// void imgui_ImColor(ImU32 rgba);
void imgui_ImColor_SetHSV(ImColor* ImColor_ctx, float h, float s, float v, float a);
ImColor imgui_ImColor_HSV(ImColor* ImColor_ctx, float h, float s, float v, float a);

typedef enum {
  ImGuiMultiSelectFlags_None,
  ImGuiMultiSelectFlags_SingleSelect = 1 << 0,
  ImGuiMultiSelectFlags_NoSelectAll = 1 << 1,
  ImGuiMultiSelectFlags_NoRangeSelect = 1 << 2,
  ImGuiMultiSelectFlags_NoAutoSelect = 1 << 3,
  ImGuiMultiSelectFlags_NoAutoClear = 1 << 4,
  ImGuiMultiSelectFlags_NoAutoClearOnReselect = 1 << 5,
  ImGuiMultiSelectFlags_BoxSelect1d = 1 << 6,
  ImGuiMultiSelectFlags_BoxSelect2d = 1 << 7,
  ImGuiMultiSelectFlags_BoxSelectNoScroll = 1 << 8,
  ImGuiMultiSelectFlags_ClearOnEscape = 1 << 9,
  ImGuiMultiSelectFlags_ClearOnClickVoid = 1 << 10,
  ImGuiMultiSelectFlags_ScopeWindow = 1 << 11,
  ImGuiMultiSelectFlags_ScopeRect = 1 << 12,
  ImGuiMultiSelectFlags_SelectOnClick = 1 << 13,
  ImGuiMultiSelectFlags_SelectOnClickRelease = 1 << 14,
  ImGuiMultiSelectFlags_NavWrapX = 1 << 16
} ImGuiMultiSelectFlags_;
typedef struct ImGuiMultiSelectIO {
  ImVector Requests;
  ImGuiSelectionUserData RangeSrcItem;
  ImGuiSelectionUserData NavIdItem;
  bool NavIdSelected;
  bool RangeSrcReset;
  int ItemsCount;
} ImGuiMultiSelectIO;

typedef enum {
  ImGuiSelectionRequestType_None,
  ImGuiSelectionRequestType_SetAll,
  ImGuiSelectionRequestType_SetRange
} ImGuiSelectionRequestType;
typedef struct ImGuiSelectionRequest {
  ImGuiSelectionRequestType Type;
  bool Selected;
  ImS8 RangeDirection;
  ImGuiSelectionUserData RangeFirstItem;
  ImGuiSelectionUserData RangeLastItem;
} ImGuiSelectionRequest;
typedef struct ImGuiSelectionBasicStorage {
  int Size;
  bool PreserveOrder;
  void* UserData;
  void* AdapterIndexToStorageId; // complex callback: ImGuiID (*)(ImGuiSelectionBasicStorage *, int) - 
  int _SelectionOrder;
  ImGuiStorage _Storage;
} ImGuiSelectionBasicStorage;
// void imgui_ImGuiSelectionBasicStorage();
void imgui_ImGuiSelectionBasicStorage_ApplyRequests(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiMultiSelectIO* ms_io);
bool imgui_ImGuiSelectionBasicStorage_Contains(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiID id);
void imgui_ImGuiSelectionBasicStorage_Clear(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx);
void imgui_ImGuiSelectionBasicStorage_Swap(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiSelectionBasicStorage* r);
void imgui_ImGuiSelectionBasicStorage_SetItemSelected(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, ImGuiID id, bool selected);
bool imgui_ImGuiSelectionBasicStorage_GetNextSelectedItem(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, void** opaque_it, ImGuiID* out_id);
ImGuiID imgui_ImGuiSelectionBasicStorage_GetStorageIdFromIndex(ImGuiSelectionBasicStorage* ImGuiSelectionBasicStorage_ctx, int idx);
typedef struct ImGuiSelectionExternalStorage {
  void* UserData;
  void* AdapterSetItemSelected; // complex callback: void (*)(ImGuiSelectionExternalStorage *, int, bool) - 
} ImGuiSelectionExternalStorage;
// void imgui_ImGuiSelectionExternalStorage();
void imgui_ImGuiSelectionExternalStorage_ApplyRequests(ImGuiSelectionExternalStorage* ImGuiSelectionExternalStorage_ctx, ImGuiMultiSelectIO* ms_io);
typedef unsigned short ImDrawIdx;
typedef void (*ImDrawCallback)(const ImDrawList* parent_list, const ImDrawCmd* cmd);
typedef struct ImDrawCmd {
  ImVec4_C ClipRect;
  ImTextureID TexRef;
  unsigned int VtxOffset;
  unsigned int IdxOffset;
  unsigned int ElemCount;
  ImDrawCallback UserCallback;
  void* UserCallbackData;
  int UserCallbackDataSize;
  int UserCallbackDataOffset;
} ImDrawCmd;
// void imgui_ImDrawCmd();
typedef struct ImDrawVert {
  ImVec2_C pos;
  ImVec2_C uv;
  ImU32 col;
} ImDrawVert;
typedef struct ImDrawCmdHeader {
  ImVec4_C ClipRect;
  ImTextureID TexRef;
  unsigned int VtxOffset;
} ImDrawCmdHeader;
typedef struct ImDrawListSplitter {
  int _Current;
  int _Count;
  ImVector _Channels;
} ImDrawListSplitter;
// void imgui_ImDrawListSplitter();
void imgui_ImDrawListSplitter_Clear(ImDrawListSplitter* ImDrawListSplitter_ctx);
void imgui_ImDrawListSplitter_ClearFreeMemory(ImDrawListSplitter* ImDrawListSplitter_ctx);
void imgui_ImDrawListSplitter_Split(ImDrawListSplitter* ImDrawListSplitter_ctx, ImDrawList* draw_list, int count);
void imgui_ImDrawListSplitter_Merge(ImDrawListSplitter* ImDrawListSplitter_ctx, ImDrawList* draw_list);
void imgui_ImDrawListSplitter_SetCurrentChannel(ImDrawListSplitter* ImDrawListSplitter_ctx, ImDrawList* draw_list, int channel_idx);

typedef enum {
  ImDrawFlags_None,
  ImDrawFlags_Closed = 1 << 0,
  ImDrawFlags_RoundCornersTopLeft = 1 << 4,
  ImDrawFlags_RoundCornersTopRight = 1 << 5,
  ImDrawFlags_RoundCornersBottomLeft = 1 << 6,
  ImDrawFlags_RoundCornersBottomRight = 1 << 7,
  ImDrawFlags_RoundCornersNone = 1 << 8,
  ImDrawFlags_RoundCornersTop = ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersTopRight,
  ImDrawFlags_RoundCornersBottom = ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersBottomRight,
  ImDrawFlags_RoundCornersLeft = ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersTopLeft,
  ImDrawFlags_RoundCornersRight = ImDrawFlags_RoundCornersBottomRight | ImDrawFlags_RoundCornersTopRight,
  ImDrawFlags_RoundCornersAll = ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersTopRight | ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersBottomRight,
  ImDrawFlags_RoundCornersDefault_,
  ImDrawFlags_RoundCornersMask_ = ImDrawFlags_RoundCornersAll | ImDrawFlags_RoundCornersNone
} ImDrawFlags_;

typedef enum {
  ImDrawListFlags_None,
  ImDrawListFlags_AntiAliasedLines = 1 << 0,
  ImDrawListFlags_AntiAliasedLinesUseTex = 1 << 1,
  ImDrawListFlags_AntiAliasedFill = 1 << 2,
  ImDrawListFlags_AllowVtxOffset = 1 << 3
} ImDrawListFlags_;
typedef struct ImDrawList {
  ImVector CmdBuffer;
  ImVector IdxBuffer;
  ImVector VtxBuffer;
  ImDrawListFlags Flags;
  unsigned int _VtxCurrentIdx;
  ImDrawListSharedData* _Data;
  ImDrawVert* _VtxWritePtr;
  ImDrawIdx* _IdxWritePtr;
  ImVector _Path;
  ImDrawCmdHeader _CmdHeader;
  ImDrawListSplitter _Splitter;
  ImVector _ClipRectStack;
  ImVector _TextureStack;
  ImVector _CallbacksDataBuf;
  float _FringeScale;
  const char* _OwnerName;
} ImDrawList;
// void imgui_ImDrawList(ImDrawListSharedData* shared_data);
void imgui_ImDrawList_PushClipRect(ImDrawList* ImDrawList_ctx, const ImVec2_C* clip_rect_min, const ImVec2_C* clip_rect_max, bool intersect_with_current_clip_rect);
void imgui_ImDrawList_PushClipRectFullScreen(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList_PopClipRect(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList_PushTexture(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref);
void imgui_ImDrawList_PopTexture(ImDrawList* ImDrawList_ctx);
ImVec2_C imgui_ImDrawList_GetClipRectMin(ImDrawList* ImDrawList_ctx);
ImVec2_C imgui_ImDrawList_GetClipRectMax(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList_AddLine(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, ImU32 col, float thickness);
void imgui_ImDrawList_AddRect(ImDrawList* ImDrawList_ctx, const ImVec2_C* p_min, const ImVec2_C* p_max, ImU32 col, float rounding, ImDrawFlags flags, float thickness);
void imgui_ImDrawList_AddRectFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* p_min, const ImVec2_C* p_max, ImU32 col, float rounding, ImDrawFlags flags);
void imgui_ImDrawList_AddRectFilledMultiColor(ImDrawList* ImDrawList_ctx, const ImVec2_C* p_min, const ImVec2_C* p_max, ImU32 col_upr_left, ImU32 col_upr_right, ImU32 col_bot_right, ImU32 col_bot_left);
void imgui_ImDrawList_AddQuad(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, const ImVec2_C* p4, ImU32 col, float thickness);
void imgui_ImDrawList_AddQuadFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, const ImVec2_C* p4, ImU32 col);
void imgui_ImDrawList_AddTriangle(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, ImU32 col, float thickness);
void imgui_ImDrawList_AddTriangleFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, ImU32 col);
void imgui_ImDrawList_AddCircle(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, ImU32 col, int num_segments, float thickness);
void imgui_ImDrawList_AddCircleFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, ImU32 col, int num_segments);
void imgui_ImDrawList_AddNgon(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, ImU32 col, int num_segments, float thickness);
void imgui_ImDrawList_AddNgonFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, ImU32 col, int num_segments);
void imgui_ImDrawList_AddEllipse(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, const ImVec2_C* radius, ImU32 col, float rot, int num_segments, float thickness);
void imgui_ImDrawList_AddEllipseFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, const ImVec2_C* radius, ImU32 col, float rot, int num_segments);
void imgui_ImDrawList_AddText1(ImDrawList* ImDrawList_ctx, const ImVec2_C* pos, ImU32 col, const char* text_begin, const char* text_end);
void imgui_ImDrawList_AddText2(ImDrawList* ImDrawList_ctx, ImFont* font, float font_size, const ImVec2_C* pos, ImU32 col, const char* text_begin, const char* text_end, float wrap_width, const ImVec4_C* cpu_fine_clip_rect);
void imgui_ImDrawList_AddBezierCubic(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, const ImVec2_C* p4, ImU32 col, float thickness, int num_segments);
void imgui_ImDrawList_AddBezierQuadratic(ImDrawList* ImDrawList_ctx, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, ImU32 col, float thickness, int num_segments);
void imgui_ImDrawList_AddPolyline(ImDrawList* ImDrawList_ctx, const ImVec2_C* points, int num_points, ImU32 col, ImDrawFlags flags, float thickness);
void imgui_ImDrawList_AddConvexPolyFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* points, int num_points, ImU32 col);
void imgui_ImDrawList_AddConcavePolyFilled(ImDrawList* ImDrawList_ctx, const ImVec2_C* points, int num_points, ImU32 col);
void imgui_ImDrawList_AddImage(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref, const ImVec2_C* p_min, const ImVec2_C* p_max, const ImVec2_C* uv_min, const ImVec2_C* uv_max, ImU32 col);
void imgui_ImDrawList_AddImageQuad(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref, const ImVec2_C* p1, const ImVec2_C* p2, const ImVec2_C* p3, const ImVec2_C* p4, const ImVec2_C* uv1, const ImVec2_C* uv2, const ImVec2_C* uv3, const ImVec2_C* uv4, ImU32 col);
void imgui_ImDrawList_AddImageRounded(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref, const ImVec2_C* p_min, const ImVec2_C* p_max, const ImVec2_C* uv_min, const ImVec2_C* uv_max, ImU32 col, float rounding, ImDrawFlags flags);
void imgui_ImDrawList_PathClear(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList_PathLineTo(ImDrawList* ImDrawList_ctx, const ImVec2_C* pos);
void imgui_ImDrawList_PathLineToMergeDuplicate(ImDrawList* ImDrawList_ctx, const ImVec2_C* pos);
void imgui_ImDrawList_PathFillConvex(ImDrawList* ImDrawList_ctx, ImU32 col);
void imgui_ImDrawList_PathFillConcave(ImDrawList* ImDrawList_ctx, ImU32 col);
void imgui_ImDrawList_PathStroke(ImDrawList* ImDrawList_ctx, ImU32 col, ImDrawFlags flags, float thickness);
void imgui_ImDrawList_PathArcTo(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, float a_min, float a_max, int num_segments);
void imgui_ImDrawList_PathArcToFast(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, int a_min_of_12, int a_max_of_12);
void imgui_ImDrawList_PathEllipticalArcTo(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, const ImVec2_C* radius, float rot, float a_min, float a_max, int num_segments);
void imgui_ImDrawList_PathBezierCubicCurveTo(ImDrawList* ImDrawList_ctx, const ImVec2_C* p2, const ImVec2_C* p3, const ImVec2_C* p4, int num_segments);
void imgui_ImDrawList_PathBezierQuadraticCurveTo(ImDrawList* ImDrawList_ctx, const ImVec2_C* p2, const ImVec2_C* p3, int num_segments);
void imgui_ImDrawList_PathRect(ImDrawList* ImDrawList_ctx, const ImVec2_C* rect_min, const ImVec2_C* rect_max, float rounding, ImDrawFlags flags);
void imgui_ImDrawList_AddCallback(ImDrawList* ImDrawList_ctx, ImDrawCallback callback, void* userdata, size_t userdata_size);
void imgui_ImDrawList_AddDrawCmd(ImDrawList* ImDrawList_ctx);
ImDrawList * imgui_ImDrawList_CloneOutput(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList_ChannelsSplit(ImDrawList* ImDrawList_ctx, int count);
void imgui_ImDrawList_ChannelsMerge(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList_ChannelsSetCurrent(ImDrawList* ImDrawList_ctx, int n);
void imgui_ImDrawList_PrimReserve(ImDrawList* ImDrawList_ctx, int idx_count, int vtx_count);
void imgui_ImDrawList_PrimUnreserve(ImDrawList* ImDrawList_ctx, int idx_count, int vtx_count);
void imgui_ImDrawList_PrimRect(ImDrawList* ImDrawList_ctx, const ImVec2_C* a, const ImVec2_C* b, ImU32 col);
void imgui_ImDrawList_PrimRectUV(ImDrawList* ImDrawList_ctx, const ImVec2_C* a, const ImVec2_C* b, const ImVec2_C* uv_a, const ImVec2_C* uv_b, ImU32 col);
void imgui_ImDrawList_PrimQuadUV(ImDrawList* ImDrawList_ctx, const ImVec2_C* a, const ImVec2_C* b, const ImVec2_C* c, const ImVec2_C* d, const ImVec2_C* uv_a, const ImVec2_C* uv_b, const ImVec2_C* uv_c, const ImVec2_C* uv_d, ImU32 col);
void imgui_ImDrawList_PrimWriteVtx(ImDrawList* ImDrawList_ctx, const ImVec2_C* pos, const ImVec2_C* uv, ImU32 col);
void imgui_ImDrawList_PrimWriteIdx(ImDrawList* ImDrawList_ctx, ImDrawIdx idx);
void imgui_ImDrawList_PrimVtx(ImDrawList* ImDrawList_ctx, const ImVec2_C* pos, const ImVec2_C* uv, ImU32 col);
void imgui_ImDrawList__SetDrawListSharedData(ImDrawList* ImDrawList_ctx, ImDrawListSharedData* data);
void imgui_ImDrawList__ResetForNewFrame(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__ClearFreeMemory(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__PopUnusedDrawCmd(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__TryMergeDrawCmds(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__OnChangedClipRect(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__OnChangedTexture(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__OnChangedVtxOffset(ImDrawList* ImDrawList_ctx);
void imgui_ImDrawList__SetTexture(ImDrawList* ImDrawList_ctx, ImTextureID tex_ref);
int imgui_ImDrawList__CalcCircleAutoSegmentCount(ImDrawList* ImDrawList_ctx, float radius);
void imgui_ImDrawList__PathArcToFastEx(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, int a_min_sample, int a_max_sample, int a_step);
void imgui_ImDrawList__PathArcToN(ImDrawList* ImDrawList_ctx, const ImVec2_C* center, float radius, float a_min, float a_max, int num_segments);
typedef struct ImDrawData {
  bool Valid;
  int CmdListsCount;
  int TotalIdxCount;
  int TotalVtxCount;
  ImVector CmdLists;
  ImVec2_C DisplayPos;
  ImVec2_C DisplaySize;
  ImVec2_C FramebufferScale;
  ImGuiViewport* OwnerViewport;
  ImVector Textures;
} ImDrawData;
// void imgui_ImDrawData();
void imgui_ImDrawData_Clear(ImDrawData* ImDrawData_ctx);
void imgui_ImDrawData_AddDrawList(ImDrawData* ImDrawData_ctx, ImDrawList* draw_list);
void imgui_ImDrawData_DeIndexAllBuffers(ImDrawData* ImDrawData_ctx);
void imgui_ImDrawData_ScaleClipRects(ImDrawData* ImDrawData_ctx, const ImVec2_C* fb_scale);

typedef enum {
  ImTextureFormat_RGBA32,
  ImTextureFormat_Alpha8
} ImTextureFormat;

typedef enum {
  ImTextureStatus_OK,
  ImTextureStatus_Destroyed,
  ImTextureStatus_WantCreate,
  ImTextureStatus_WantUpdates,
  ImTextureStatus_WantDestroy
} ImTextureStatus;
typedef struct ImTextureRect {
  unsigned short x;
  unsigned short y;
  unsigned short w;
  unsigned short h;
} ImTextureRect;
typedef struct ImTextureData {
  int UniqueID;
  ImTextureStatus Status;
  void* BackendUserData;
  ImTextureID TexID;
  ImTextureFormat Format;
  int Width;
  int Height;
  int BytesPerPixel;
  unsigned char* Pixels;
  ImTextureRect UsedRect;
  ImTextureRect UpdateRect;
  ImVector Updates;
  int UnusedFrames;
  unsigned short RefCount;
  bool UseColors;
  bool WantDestroyNextFrame;
} ImTextureData;
// void imgui_ImTextureData();
void imgui_ImTextureData_Create(ImTextureData* ImTextureData_ctx, ImTextureFormat format, int w, int h);
void imgui_ImTextureData_DestroyPixels(ImTextureData* ImTextureData_ctx);
void * imgui_ImTextureData_GetPixels(ImTextureData* ImTextureData_ctx);
void * imgui_ImTextureData_GetPixelsAt(ImTextureData* ImTextureData_ctx, int x, int y);
int imgui_ImTextureData_GetSizeInBytes(ImTextureData* ImTextureData_ctx);
int imgui_ImTextureData_GetPitch(ImTextureData* ImTextureData_ctx);
ImTextureRef imgui_ImTextureData_GetTexRef(ImTextureData* ImTextureData_ctx);
void imgui_ImTextureData_SetTexID(ImTextureData* ImTextureData_ctx, ImTextureID tex_id);
void imgui_ImTextureData_SetStatus(ImTextureData* ImTextureData_ctx, ImTextureStatus status);
typedef struct ImFontConfig {
  char Name[40];
  void* FontData;
  int FontDataSize;
  bool FontDataOwnedByAtlas;
  bool MergeMode;
  bool PixelSnapH;
  bool PixelSnapV;
  ImS8 OversampleH;
  ImS8 OversampleV;
  ImWchar EllipsisChar;
  float SizePixels;
  const ImWchar* GlyphRanges;
  const ImWchar* GlyphExcludeRanges;
  ImVec2_C GlyphOffset;
  float GlyphMinAdvanceX;
  float GlyphMaxAdvanceX;
  float GlyphExtraAdvanceX;
  ImU32 FontNo;
  unsigned int FontLoaderFlags;
  float RasterizerMultiply;
  float RasterizerDensity;
  ImFontFlags Flags;
  ImFont* DstFont;
  const ImFontLoader* FontLoader;
  void* FontLoaderData;
} ImFontConfig;
// void imgui_ImFontConfig();
typedef struct ImFontGlyph {
  unsigned int Colored;
  unsigned int Visible;
  unsigned int SourceIdx;
  unsigned int Codepoint;
  float AdvanceX;
  float X0;
  float Y0;
  float X1;
  float Y1;
  float U0;
  float V0;
  float U1;
  float V1;
  int PackId;
} ImFontGlyph;
// void imgui_ImFontGlyph();
typedef struct ImFontGlyphRangesBuilder {
  ImVector UsedChars;
} ImFontGlyphRangesBuilder;
// void imgui_ImFontGlyphRangesBuilder();
void imgui_ImFontGlyphRangesBuilder_Clear(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx);
bool imgui_ImFontGlyphRangesBuilder_GetBit(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, size_t n);
void imgui_ImFontGlyphRangesBuilder_SetBit(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, size_t n);
void imgui_ImFontGlyphRangesBuilder_AddChar(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, ImWchar c);
void imgui_ImFontGlyphRangesBuilder_AddText(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, const char* text, const char* text_end);
void imgui_ImFontGlyphRangesBuilder_AddRanges(ImFontGlyphRangesBuilder* ImFontGlyphRangesBuilder_ctx, const ImWchar* ranges);
typedef int ImFontAtlasRectId;
typedef struct ImFontAtlasRect {
  unsigned short x;
  unsigned short y;
  unsigned short w;
  unsigned short h;
  ImVec2_C uv0;
  ImVec2_C uv1;
} ImFontAtlasRect;
// void imgui_ImFontAtlasRect();

typedef enum {
  ImFontAtlasFlags_None,
  ImFontAtlasFlags_NoPowerOfTwoHeight = 1 << 0,
  ImFontAtlasFlags_NoMouseCursors = 1 << 1,
  ImFontAtlasFlags_NoBakedLines = 1 << 2
} ImFontAtlasFlags_;
typedef struct ImFontAtlas {
  ImFontAtlasFlags Flags;
  ImTextureFormat TexDesiredFormat;
  int TexGlyphPadding;
  int TexMinWidth;
  int TexMinHeight;
  int TexMaxWidth;
  int TexMaxHeight;
  void* UserData;
  ImTextureID TexRef;
  ImTextureData* TexData;
  ImVector TexList;
  bool Locked;
  bool RendererHasTextures;
  bool TexIsBuilt;
  bool TexPixelsUseColors;
  ImVec2_C TexUvScale;
  ImVec2_C TexUvWhitePixel;
  ImVector Fonts;
  ImVector Sources;
  ImVec4_C TexUvLines[33];
  int TexNextUniqueID;
  int FontNextUniqueID;
  ImVector DrawListSharedDatas;
  ImFontAtlasBuilder* Builder;
  const ImFontLoader* FontLoader;
  const char* FontLoaderName;
  void* FontLoaderData;
  unsigned int FontLoaderFlags;
  int RefCount;
  ImGuiContext* OwnerContext;
} ImFontAtlas;
// void imgui_ImFontAtlas();
ImFont * imgui_ImFontAtlas_AddFont(ImFontAtlas* ImFontAtlas_ctx, const ImFontConfig* font_cfg);
ImFont * imgui_ImFontAtlas_AddFontDefault(ImFontAtlas* ImFontAtlas_ctx, const ImFontConfig* font_cfg);
ImFont * imgui_ImFontAtlas_AddFontFromFileTTF(ImFontAtlas* ImFontAtlas_ctx, const char* filename, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges);
ImFont * imgui_ImFontAtlas_AddFontFromMemoryTTF(ImFontAtlas* ImFontAtlas_ctx, void* font_data, int font_data_size, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges);
ImFont * imgui_ImFontAtlas_AddFontFromMemoryCompressedTTF(ImFontAtlas* ImFontAtlas_ctx, const void* compressed_font_data, int compressed_font_data_size, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges);
ImFont * imgui_ImFontAtlas_AddFontFromMemoryCompressedBase85TTF(ImFontAtlas* ImFontAtlas_ctx, const char* compressed_font_data_base85, float size_pixels, const ImFontConfig* font_cfg, const ImWchar* glyph_ranges);
void imgui_ImFontAtlas_RemoveFont(ImFontAtlas* ImFontAtlas_ctx, ImFont* font);
void imgui_ImFontAtlas_Clear(ImFontAtlas* ImFontAtlas_ctx);
void imgui_ImFontAtlas_CompactCache(ImFontAtlas* ImFontAtlas_ctx);
void imgui_ImFontAtlas_SetFontLoader(ImFontAtlas* ImFontAtlas_ctx, const ImFontLoader* font_loader);
void imgui_ImFontAtlas_ClearInputData(ImFontAtlas* ImFontAtlas_ctx);
void imgui_ImFontAtlas_ClearFonts(ImFontAtlas* ImFontAtlas_ctx);
void imgui_ImFontAtlas_ClearTexData(ImFontAtlas* ImFontAtlas_ctx);
const ImWchar * imgui_ImFontAtlas_GetGlyphRangesDefault(ImFontAtlas* ImFontAtlas_ctx);
ImFontAtlasRectId imgui_ImFontAtlas_AddCustomRect(ImFontAtlas* ImFontAtlas_ctx, int width, int height, ImFontAtlasRect* out_r);
void imgui_ImFontAtlas_RemoveCustomRect(ImFontAtlas* ImFontAtlas_ctx, ImFontAtlasRectId id);
bool imgui_ImFontAtlas_GetCustomRect(ImFontAtlas* ImFontAtlas_ctx, ImFontAtlasRectId id, ImFontAtlasRect* out_r);
typedef struct ImFontBaked {
  ImVector IndexAdvanceX;
  float FallbackAdvanceX;
  float Size;
  float RasterizerDensity;
  ImVector IndexLookup;
  ImVector Glyphs;
  int FallbackGlyphIndex;
  float Ascent;
  float Descent;
  unsigned int MetricsTotalSurface;
  unsigned int WantDestroy;
  unsigned int LoadNoFallback;
  unsigned int LoadNoRenderOnLayout;
  int LastUsedFrame;
  ImGuiID BakedId;
  ImFont* ContainerFont;
  void* FontLoaderDatas;
} ImFontBaked;
// void imgui_ImFontBaked();
void imgui_ImFontBaked_ClearOutputData(ImFontBaked* ImFontBaked_ctx);
ImFontGlyph * imgui_ImFontBaked_FindGlyph(ImFontBaked* ImFontBaked_ctx, ImWchar c);
ImFontGlyph * imgui_ImFontBaked_FindGlyphNoFallback(ImFontBaked* ImFontBaked_ctx, ImWchar c);
float imgui_ImFontBaked_GetCharAdvance(ImFontBaked* ImFontBaked_ctx, ImWchar c);
bool imgui_ImFontBaked_IsGlyphLoaded(ImFontBaked* ImFontBaked_ctx, ImWchar c);

typedef enum {
  ImFontFlags_None,
  ImFontFlags_NoLoadError = 1 << 1,
  ImFontFlags_NoLoadGlyphs = 1 << 2,
  ImFontFlags_LockBakedSizes = 1 << 3
} ImFontFlags_;
typedef struct ImFont {
  ImFontBaked* LastBaked;
  ImFontAtlas* ContainerAtlas;
  ImFontFlags Flags;
  float CurrentRasterizerDensity;
  ImGuiID FontId;
  float LegacySize;
  ImVector Sources;
  ImWchar EllipsisChar;
  ImWchar FallbackChar;
  ImU8 Used8kPagesMap[1];
  bool EllipsisAutoBake;
  ImGuiStorage RemapPairs;
} ImFont;
// void imgui_ImFont();
bool imgui_ImFont_IsGlyphInFont(ImFont* ImFont_ctx, ImWchar c);
bool imgui_ImFont_IsLoaded(ImFont* ImFont_ctx);
const char * imgui_ImFont_GetDebugName(ImFont* ImFont_ctx);
ImFontBaked * imgui_ImFont_GetFontBaked(ImFont* ImFont_ctx, float font_size, float density);
ImVec2_C imgui_ImFont_CalcTextSizeA(ImFont* ImFont_ctx, float size, float max_width, float wrap_width, const char* text_begin, const char* text_end, const char** out_remaining);
const char * imgui_ImFont_CalcWordWrapPosition(ImFont* ImFont_ctx, float size, const char* text, const char* text_end, float wrap_width);
void imgui_ImFont_RenderChar(ImFont* ImFont_ctx, ImDrawList* draw_list, float size, const ImVec2_C* pos, ImU32 col, ImWchar c, const ImVec4_C* cpu_fine_clip);
void imgui_ImFont_RenderText(ImFont* ImFont_ctx, ImDrawList* draw_list, float size, const ImVec2_C* pos, ImU32 col, const ImVec4_C* clip_rect, const char* text_begin, const char* text_end, float wrap_width, ImDrawTextFlags flags);
void imgui_ImFont_ClearOutputData(ImFont* ImFont_ctx);
void imgui_ImFont_AddRemapChar(ImFont* ImFont_ctx, ImWchar from_codepoint, ImWchar to_codepoint);
bool imgui_ImFont_IsGlyphRangeUnused(ImFont* ImFont_ctx, unsigned int c_begin, unsigned int c_last);

typedef enum {
  ImGuiViewportFlags_None,
  ImGuiViewportFlags_IsPlatformWindow = 1 << 0,
  ImGuiViewportFlags_IsPlatformMonitor = 1 << 1,
  ImGuiViewportFlags_OwnedByApp = 1 << 2
} ImGuiViewportFlags_;
typedef struct ImGuiViewport {
  ImGuiID ID;
  ImGuiViewportFlags Flags;
  ImVec2_C Pos;
  ImVec2_C Size;
  ImVec2_C FramebufferScale;
  ImVec2_C WorkPos;
  ImVec2_C WorkSize;
  void* PlatformHandle;
  void* PlatformHandleRaw;
} ImGuiViewport;
// void imgui_ImGuiViewport();
ImVec2_C imgui_ImGuiViewport_GetCenter(ImGuiViewport* ImGuiViewport_ctx);
ImVec2_C imgui_ImGuiViewport_GetWorkCenter(ImGuiViewport* ImGuiViewport_ctx);
typedef struct ImGuiPlatformIO {
  void* Platform_GetClipboardTextFn; // complex callback: const char *(*)(ImGuiContext *) - 
  void* Platform_SetClipboardTextFn; // complex callback: void (*)(ImGuiContext *, const char *) - 
  void* Platform_ClipboardUserData;
  void* Platform_OpenInShellFn; // complex callback: bool (*)(ImGuiContext *, const char *) - 
  void* Platform_OpenInShellUserData;
  void* Platform_SetImeDataFn; // complex callback: void (*)(ImGuiContext *, ImGuiViewport *, ImGuiPlatformImeData *) - 
  void* Platform_ImeUserData;
  ImWchar Platform_LocaleDecimalPoint;
  int Renderer_TextureMaxWidth;
  int Renderer_TextureMaxHeight;
  void* Renderer_RenderState;
  ImVector Textures;
} ImGuiPlatformIO;
// void imgui_ImGuiPlatformIO();
typedef struct ImGuiPlatformImeData {
  bool WantVisible;
  bool WantTextInput;
  ImVec2_C InputPos;
  float InputLineHeight;
  ImGuiID ViewportId;
} ImGuiPlatformImeData;
// void imgui_ImGuiPlatformImeData();
